<?xml version="1.0"?>
<project
    xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 https://maven.apache.org/xsd/maven-4.0.0.xsd"
    xmlns="http://maven.apache.org/POM/4.0.0"
    xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance">
    <modelVersion>4.0.0</modelVersion>
    <parent>
        <groupId>com.delorean-aixm</groupId>
        <artifactId>delorean-aixm</artifactId>
        <version>0.2.0</version>
        <relativePath>../pom.xml</relativePath>
    </parent>
    <artifactId>delorean-cli-aixm52</artifactId>
    <name>Delorean CLI AIXM 5.2</name>
    <dependencies>
        <dependency>
            <groupId>com.delorean-aixm</groupId>
            <artifactId>delorean-core</artifactId>
        </dependency>

        <dependency>
            <groupId>com.delorean-aixm</groupId>
            <artifactId>delorean-cli</artifactId>
            <version>${project.version}</version>
        </dependency>

        <dependency>
            <groupId>info.picocli</groupId>
            <artifactId>picocli</artifactId>
            <version>4.7.7</version>
        </dependency>

        <dependency>
            <groupId>com.delorean-aixm</groupId>
            <artifactId>delorean-aixm-52</artifactId>
            <version>${project.version}</version>
        </dependency>
    </dependencies>
    <build>
        <plugins>
            <plugin>
                <groupId>org.apache.maven.plugins</groupId>
                <artifactId>maven-shade-plugin</artifactId>
                <version>3.5.1</version>
                <executions>
                    <execution>
                        <phase>package</phase>
                        <goals>
                            <goal>shade</goal>
                        </goals>
                        <configuration>
                            <transformers>
                                <transformer
                                    implementation="org.apache.maven.plugins.shade.resource.ManifestResourceTransformer">
                                    <mainClass>com.delorean.aixm.cli.DeloreanCLIAIXM52</mainClass>
                                </transformer>
                            </transformers>
                        </configuration>
                    </execution>
                </executions>
            </plugin>
        </plugins>
    </build>
</project>