-- Required extension
CREATE EXTENSION IF NOT EXISTS "uuid-ossp";
CREATE EXTENSION IF NOT EXISTS "postgis";

-- Required schema for AIXM 5.1
CREATE SCHEMA IF NOT EXISTS aerial_refuelling;
CREATE SCHEMA IF NOT EXISTS airport_heliport;
CREATE SCHEMA IF NOT EXISTS airspace;
CREATE SCHEMA IF NOT EXISTS gml;
CREATE SCHEMA IF NOT EXISTS holding;
CREATE SCHEMA IF NOT EXISTS navaids_point;
CREATE SCHEMA IF NOT EXISTS note;
CREATE SCHEMA IF NOT EXISTS obstacle;
CREATE SCHEMA IF NOT EXISTS organisation;
CREATE SCHEMA IF NOT EXISTS procedure;
CREATE SCHEMA IF NOT EXISTS route;
CREATE SCHEMA IF NOT EXISTS rules_procedure;
CREATE SCHEMA IF NOT EXISTS service;
CREATE SCHEMA IF NOT EXISTS shared;
CREATE SCHEMA IF NOT EXISTS surveillance;
CREATE SCHEMA IF NOT EXISTS aixm;