import './pages.css'
import { useState, useEffect, useRef } from "preact/hooks";
import Helmet from "preact-helmet";
import hljs from "highlight.js";
import "highlight.js/styles/github-dark.css"; 

import Form1Img from "../../images/form-1.jpg";
import Form4Img from "../../images/form-4.jpg";
import { Figure } from '../util/Figure';

export function QGIS ({ onNavigate }) {
  useEffect(() => {
    hljs.highlightAll(); 
  }, []);
  
  return (
<main className="relative z-10 max-w-6xl mx-auto px-6 py-24 space-y-16 leading-relaxed text-lg">
    <Helmet
    defaultTitle="Delorean AIXM"
    titleTemplate="%s - QGIS Integration"
    >
    <title>QGIS Integration</title>
    <meta 
        name="description" 
        content="Discover how Delorean AIXM integrates with QGIS to visualize and interact with aeronautical data. Learn how extended GML geometries are transformed into PostGIS-compatible layers for interactive GIS workflows."
    />
    <meta 
        name="keywords" 
        content="Delorean, AIXM, QGIS, GML, PostGIS, Digital aeronautical data, GIS, AIM, SWIM, Aviation data"
    />
    <meta property="og:title" content="Delorean AIXM - QGIS Integration" />
    <meta property="og:description" content="Explore how Delorean AIXM connects with QGIS to render complex aeronautical data, enabling interactive GIS analysis and visualization of AIXM features and geometries." />
    <meta property="og:type" content="website" />
    <meta property="og:url" content="https://delorean-aixm.io/features/qgis" />
    </Helmet>
  <section className="space-y-4">
    <h1 className="text-4xl font-bold tracking-tight">QGIS Interaction</h1>
    <p>
      The Delorean QGIS project contains all the AIXM features and objects, 
      which are grouped by theme. Additionally, all the data is already temporally 
      formatted and the geometry is rendered. To display the attributes of features 
      or objects, you can either open the attribute table or identify the feature. 
      Make sure you open these pages in Form View to leverage the views generated by Delorean.
    </p>
    <div className="gap-8">
        <div className="lg:basis-1/3 flex flex-col space-y-4 text-base leading-relaxed">
            <h2 className="text-4xl font-bold tracking-tight">Delorean Form display</h2>
            <p>
                When you open a feature form, you can see the timeslice content with the resolved features attached to it (the identifier), 
                the attributes of the feature, the resolved annotations and the timesheets, as well as all the links to other objects or features.
            </p>
      </div>
      <div className="lg:basis-2/3 flex justify-center">
        <Figure
          src={Form1Img}
          alt="Delorean Form representation of a airport ARP feature"
          caption="Figure 1 — Delorean form representation of an airport ARP feature."
          className="w-full max-w-full"
        />
      </div>

    </div>
    <div className="gap-8">
        <div className="lg:basis-1/3 flex flex-col space-y-4 text-base leading-relaxed">
            <h2 className="text-4xl font-bold tracking-tight">Delorean Form navigation</h2>
            <p>
                To navigate from one feature or object to another, Delorean formats the layer with built-in 
                actions to open the associated features or objects by walking the AIXM dependency tree.
            </p>
      </div>
      <div className="lg:basis-2/3 flex justify-center">
        <Figure
          src={Form4Img}
          alt="Delorean Form navigation to associated features"
          caption="Figure 2 — Delorean Form navigation to associated features."
          className="w-full max-w-full"
        />
      </div>

    </div>
  </section>
</main>
  );
}