change:
  - where:
      filePath: delorean-aixm-51\src\main\java\com\aixm\delorean\aixm51\schema\message\BasicMessageMemberAIXMPropertyType.java
      method: getAbstractAIXMFeatureValue
    updates:
      - old: JoinTable
        new: [
          '@jakarta.persistence.JoinColumn(name = "feature_hjid", referencedColumnName = "hjid")'
        ]

  - where: 
      filePath: delorean-aixm-51\src\main\java\com\aixm\delorean\aixm51\schema\AbstractAIXMTimeSliceType.java
      method: getFeatureLifetime 
    updates:
      - old: Transient
        new: [
          '@jakarta.persistence.Embedded',
          '@jakarta.persistence.AttributeOverrides({ @jakarta.persistence.AttributeOverride(name = "beginPosition", column = @jakarta.persistence.Column(name = "feature_lifetime_begin", columnDefinition = "TIMESTAMPTZ")), @jakarta.persistence.AttributeOverride(name = "endPosition", column = @jakarta.persistence.Column(name = "feature_lifetime_end", columnDefinition = "TIMESTAMPTZ")),@jakarta.persistence.AttributeOverride(name = "timePeriodId", column = @jakarta.persistence.Column(name = "feature_lifetime_hjid"))})'
        ]

  - where: 
      filePath: delorean-aixm-51\src\main\java\com\aixm\delorean\aixm51\schema\AbstractAIXMTimeSliceType.java
      method: getTimeSliceMetadata 
    updates:
      - old: ManyToOne
        new: []
      - old: JoinTable
        new: [
          '@jakarta.persistence.OneToOne(cascade = jakarta.persistence.CascadeType.ALL, fetch = jakarta.persistence.FetchType.EAGER)',
          '@jakarta.persistence.JoinColumn(name = "time_slice_metadata_hjid", referencedColumnName = "hjid")'
        ]
        
  - where: 
      filePath: delorean-aixm-51\src\main\java\com\aixm\delorean\aixm51\schema\AIXMPointPropertyType.java
      method: getPoint 
    updates:
      - old: Transient
        new: 
          - '@jakarta.persistence.OneToOne(cascade = jakarta.persistence.CascadeType.ALL, fetch = jakarta.persistence.FetchType.EAGER)'
          - '@jakarta.persistence.JoinColumn(name = "point_hjid", referencedColumnName = "hjid")'
  - where: 
      filePath: delorean-aixm-51\src\main\java\com\aixm\delorean\aixm51\schema\AIXMElevatedPointPropertyType.java
      method: getElevatedPoint
    updates:
      - old: Transient
        new: [
          '@jakarta.persistence.OneToOne(cascade = jakarta.persistence.CascadeType.ALL, fetch = jakarta.persistence.FetchType.EAGER)',
          '@jakarta.persistence.JoinColumn(name = "elevated_point_hjid", referencedColumnName = "hjid")'
        ]

  - where: 
      filePath: delorean-aixm-51\src\main\java\com\aixm\delorean\aixm51\schema\AIXMCurvePropertyType.java
      method: getCurve 
    updates:
      - old: Transient
        new: [
          '@jakarta.persistence.OneToOne(cascade = jakarta.persistence.CascadeType.ALL, fetch = jakarta.persistence.FetchType.EAGER)',
          '@jakarta.persistence.JoinColumn(name = "curve_hjid", referencedColumnName = "hjid")'
        ]

  - where: 
      filePath: delorean-aixm-51\src\main\java\com\aixm\delorean\aixm51\schema\AIXMElevatedCurvePropertyType.java
      method: getElevatedCurve 
    updates:
      - old: Transient
        new: [
          '@jakarta.persistence.OneToOne(cascade = jakarta.persistence.CascadeType.ALL, fetch = jakarta.persistence.FetchType.EAGER)',
          '@jakarta.persistence.JoinColumn(name = "elevated_curve_hjid", referencedColumnName = "hjid")'
        ]

  - where: 
      filePath: delorean-aixm-51\src\main\java\com\aixm\delorean\aixm51\schema\AIXMSurfacePropertyType.java
      method: getSurface 
    updates:
      - old: Transient
        new: [
          '@jakarta.persistence.OneToOne(cascade = jakarta.persistence.CascadeType.ALL, fetch = jakarta.persistence.FetchType.EAGER)',
          '@jakarta.persistence.JoinColumn(name = "surface_hjid", referencedColumnName = "hjid")'
        ]   

  - where: 
      filePath: delorean-aixm-51\src\main\java\com\aixm\delorean\aixm51\schema\AIXMElevatedSurfacePropertyType.java
      method: getElevatedSurface 
    updates:
      - old: Transient
        new: [
          '@jakarta.persistence.OneToOne(cascade = jakarta.persistence.CascadeType.ALL, fetch = jakarta.persistence.FetchType.EAGER)',
          '@jakarta.persistence.JoinColumn(name = "elevated_surface_hjid", referencedColumnName = "hjid")'
        ]

  - where: 
      filePath: delorean-aixm-51\src\main\java\com\aixm\delorean\aixm51\schema\DateTimeType.java
      field: value 
    updates:
      - old: XmlValue
        new: []
      - old: XmlJavaTypeAdapter
        new: [
          '@jakarta.xml.bind.annotation.XmlValue',
          '@jakarta.xml.bind.annotation.adapters.XmlJavaTypeAdapter(com.delorean.aixm.core.time.adapter.XMLGregorianCalendarAdapter.class)'
        ]

  - where: 
      filePath: delorean-aixm-51\src\main\java\com\aixm\delorean\aixm51\schema\DateTimeType.java
      method: getValue 
    updates:
      - old: Transient
        new: [
          '@jakarta.persistence.Basic'
        ]

  - where: 
      filePath: delorean-aixm-51\src\main\java\com\aixm\delorean\aixm51\schema\DateType.java
      field: value 
    updates:
      - old: XmlValue
        new: []
      - old: XmlJavaTypeAdapter
        new: [
          '@jakarta.xml.bind.annotation.XmlValue',
          '@jakarta.xml.bind.annotation.adapters.XmlJavaTypeAdapter(com.delorean.aixm.core.time.adapter.XMLGregorianCalendarAdapter.class)'
        ]

  - where: 
      filePath: delorean-aixm-51\src\main\java\com\aixm\delorean\aixm51\schema\DateType.java
      method: getValue 
    updates:
      - old: Transient
        new: [
          '@jakarta.persistence.Basic'
        ]

  - where: 
      filePath: delorean-aixm-51\src\main\java\com\aixm\delorean\aixm51\schema\AbstractAIXMFeatureType.java
      method: getFeatureMetadata 
    updates:
      - old: ManyToOne
        new: []
      - old: JoinTable
        new: [
          '@jakarta.persistence.OneToOne(cascade = jakarta.persistence.CascadeType.ALL, fetch = jakarta.persistence.FetchType.EAGER)',
          '@jakarta.persistence.JoinColumn(name = "feature_metadata_hjid", referencedColumnName = "hjid")'
        ]

  - where: 
      filePath: delorean-aixm-51\src\main\java\com\aixm\delorean\aixm51\schema\SegmentPointPropertyType.java
      method: getAbstractSegmentPointValue 
    updates:
      - old: ManyToOne
        new: []
      - old: JoinTable
        new: [
          '@jakarta.persistence.OneToOne(cascade = jakarta.persistence.CascadeType.ALL, fetch = jakarta.persistence.FetchType.EAGER)',
          '@jakarta.persistence.JoinColumn(name = "segment_point_hjid", referencedColumnName = "hjid")'
        ]

  - where: 
      filePath: delorean-aixm-51\src\main\java\com\aixm\delorean\aixm51\schema\DirectFlightPropertyType.java
      method: getAbstractDirectFlightValue 
    updates:
      - old: ManyToOne
        new: []
      - old: JoinTable
        new: [
          '@jakarta.persistence.OneToOne(cascade = jakarta.persistence.CascadeType.ALL, fetch = jakarta.persistence.FetchType.EAGER)',
          '@jakarta.persistence.JoinColumn(name = "direct_flight_hjid", referencedColumnName = "hjid")'
        ]

  - where: 
      filePath: delorean-aixm-51\src\main\java\com\aixm\delorean\aixm51\schema\PropertiesWithSchedulePropertyType.java
      method: getAbstractPropertiesWithScheduleValue 
    updates:
      - old: ManyToOne
        new: []
      - old: JoinTable
        new: [
          '@jakarta.persistence.OneToOne(cascade = jakarta.persistence.CascadeType.ALL, fetch = jakarta.persistence.FetchType.EAGER)',
          '@jakarta.persistence.JoinColumn(name = "properties_with_schedule_hjid", referencedColumnName = "hjid")'
        ]
        
  - where: 
      filePath: delorean-aixm-51\src\main\java\com\aixm\delorean\aixm51\schema\SurfaceContaminationPropertyType.java
      method: getAbstractSurfaceContaminationValue 
    updates:
      - old: ManyToOne
        new: []
      - old: JoinTable
        new: [
          '@jakarta.persistence.OneToOne(cascade = jakarta.persistence.CascadeType.ALL, fetch = jakarta.persistence.FetchType.EAGER)',
          '@jakarta.persistence.JoinColumn(name = "surface_contamination_hjid", referencedColumnName = "hjid")'
        ]
        
  - where: 
      filePath: delorean-aixm-51\src\main\java\com\aixm\delorean\aixm51\schema\UsageConditionPropertyType.java
      method: getAbstractUsageConditionValue 
    updates:
      - old: ManyToOne
        new: []
      - old: JoinTable
        new: [
          '@jakarta.persistence.OneToOne(cascade = jakarta.persistence.CascadeType.ALL, fetch = jakarta.persistence.FetchType.EAGER)',
          '@jakarta.persistence.JoinColumn(name = "usage_condition_hjid", referencedColumnName = "hjid")'
        ]

  - where: 
      filePath: delorean-aixm-51\src\main\java\com\aixm\delorean\aixm51\schema\MessageMetadataPropertyType.java
      method: getMdMetadata 
    updates:
      - old: Transient
        new: [
          '@org.hibernate.annotations.JdbcTypeCode(org.hibernate.type.SqlTypes.JSON)',
          '@jakarta.persistence.Column(name = "md_metadata", columnDefinition = "JSONB")'
          ]

  - where: 
      filePath: delorean-aixm-51\src\main\java\com\aixm\delorean\aixm51\schema\FeatureMetadataPropertyType.java
      method: getMdMetadata 
    updates:
      - old: Transient
        new: [
          '@org.hibernate.annotations.JdbcTypeCode(org.hibernate.type.SqlTypes.JSON)',
          '@jakarta.persistence.Column(name = "md_metadata", columnDefinition = "JSONB")'
          ]

  - where: 
      filePath: delorean-aixm-51\src\main\java\com\aixm\delorean\aixm51\schema\FeatureTimeSliceMetadataPropertyType.java
      method: getMdMetadata 
    updates:
      - old: Transient
        new: [
          '@org.hibernate.annotations.JdbcTypeCode(org.hibernate.type.SqlTypes.JSON)',
          '@jakarta.persistence.Column(name = "md_metadata", columnDefinition = "JSONB")'
          ]

delete:
  - filePath: delorean-aixm-51\src\main\java\com\aixm\delorean\aixm51\schema\Adapter1.java
  - filePath: delorean-aixm-51\src\main\java\com\aixm\delorean\aixm51\schema\Adapter2.java
  - filePath: delorean-aixm-51\src\main\java\com\aixm\delorean\aixm51\schema\Adapter3.java
  - filePath: delorean-aixm-51\src\main\java\com\aixm\delorean\aixm51\schema\Adapter4.java
  - filePath: delorean-aixm-51\src\main\java\com\aixm\delorean\aixm51\schema\Adapter5.java
  - filePath: delorean-aixm-51\src\main\java\com\aixm\delorean\aixm51\schema\Adapter6.java
  - filePath: delorean-aixm-51\src\main\java\com\aixm\delorean\aixm51\schema\Adapter7.java
  - filePath: delorean-aixm-51\src\main\java\com\aixm\delorean\aixm51\schema\Adapter8.java
  - filePath: delorean-aixm-51\src\main\java\com\aixm\delorean\aixm51\schema\Adapter9.java
  - filePath: delorean-aixm-51\src\main\java\com\aixm\delorean\aixm51\schema\Adapter10.java
  - filePath: delorean-aixm-51\src\main\java\com\aixm\delorean\aixm51\schema\XHTMLTypeAnyItem.java
  - filePath: delorean-aixm-51\src\main\java\com\aixm\delorean\aixm51\schema\XHTMLType.java
  - filePath: delorean-aixm-51\src\main\java\com\aixm\delorean\core\org\gml\v_3_2\Adapter1.java
  - filePath: delorean-aixm-51\src\main\java\org\w3\_2001\xmlschema\Adapter1.java
  - filePath: delorean-aixm-51\src\main\java\org\w3\_2001\xmlschema\Adapter2.java
  - filePath: delorean-aixm-51\src\main\java\com\aixm\delorean\core
  - filePath: delorean-aixm-51\src\main\java\org\w3

regex:
  - filePath: delorean-aixm-51\src\main\java\com\aixm\delorean\aixm51\schema\message\package-info.java
    regex: "(?s)^.*$"
    replacement: |
      @jakarta.xml.bind.annotation.XmlSchema(
          namespace = "http://www.aixm.aero/schema/5.1/message",
          xmlns = {@jakarta.xml.bind.annotation.XmlNs(prefix = "message", namespaceURI = "http://www.aixm.aero/schema/5.1/message")},
          elementFormDefault = jakarta.xml.bind.annotation.XmlNsForm.QUALIFIED
      )
      package com.delorean.aixm.aixm51.schema.message;

  - filePath: delorean-aixm-51\src\main\java\com\aixm\delorean\aixm51\schema\package-info.java
    regex: "(?s)^.*$"
    replacement: |
      @jakarta.xml.bind.annotation.XmlSchema(
          namespace = "http://www.aixm.aero/schema/5.1",
          xmlns = {@jakarta.xml.bind.annotation.XmlNs(prefix = "aixm", namespaceURI = "http://www.aixm.aero/schema/5.1")},
          elementFormDefault = jakarta.xml.bind.annotation.XmlNsForm.QUALIFIED
      )
      package com.delorean.aixm.aixm51.schema;

  - filePath: delorean-aixm-51\src\main\java\com\aixm\delorean\aixm51\schema\DateTimeType.java
    regex: import org.w3._2001.xmlschema.Adapter1;
    replacement: |
  
  - filePath: delorean-aixm-51\src\main\java\com\aixm\delorean\aixm51\schema\DateType.java
    regex: import org.w3._2001.xmlschema.Adapter2;
    replacement: |

copy:
  - from: delorean-aixm-51\src\main\post-jaxb\XHTMLType.java
    to: delorean-aixm-51\src\main\java\com\aixm\delorean\aixm51\schema\XHTMLType.java
