CREATE INDEX IF NOT EXISTS IDX_POINT_HJID ON GML.POINT (HJID);

CREATE INDEX IF NOT EXISTS IDX_POINT_HJID_GEOM_COVER ON GML.POINT (HJID) INCLUDE (GEOM);

CREATE INDEX IF NOT EXISTS IDX_POINT_GEOM ON GML.POINT USING GIST (GEOM);

CREATE INDEX IF NOT EXISTS IDX_POINT_GML_POINT_HJID ON GML.GML_POINT (GML_POINT_HJID);

CREATE INDEX IF NOT EXISTS IDX_GML_POINT_INDEX ON GML.GML_POINT (INDEX);

CREATE INDEX IF NOT EXISTS IDX_GML_POINT_PARENT_LINK ON GML.GML_POINT (GML_POINT_HJID, HJID) INCLUDE (INDEX);

CREATE INDEX IF NOT EXISTS IDX_AIXM_POINT_HJID ON GML.AIXM_POINT (HJID);

CREATE INDEX IF NOT EXISTS IDX_AIXM_ELEVATED_POINT_HJID ON GML.AIXM_ELEVATED_POINT (HJID);

CREATE INDEX IF NOT EXISTS IDX_AIXM_POINT_PT_HJID ON GML.AIXM_POINT_PT (HJID);

CREATE INDEX IF NOT EXISTS IDX_AIXM_ELEVATEDPOINT_PT_POINT_HJID ON GML.AIXM_POINT_PT (POINT_HJID);

CREATE INDEX IF NOT EXISTS IDX_AIXM_ELEVATEDPOINT_PT_HJID ON GML.AIXM_ELEVATEDPOINT_PT (HJID);

CREATE INDEX IF NOT EXISTS IDX_AIXM_ELEVATEDPOINT_PT_ELEVATED_POINT_HJID ON GML.AIXM_ELEVATEDPOINT_PT (ELEVATED_POINT_HJID);

CREATE MATERIALIZED VIEW GML.AIXM_POINT_PT_VIEW AS (
    SELECT
		GML.AIXM_POINT_PT.HJID,
		GML.POINT.ID,
		GML.AIXM_POINT.HORIZONTALACCURACY,
		GML.AIXM_POINT.HORIZONTALACCURACY_UOM,
        GML.AIXM_POINT.HORIZONTALACCURACY_ACCURACY,
		GML.AIXM_POINT.HORIZONTALACCURACY_NILREASON,
		NOTE.NOTE_P.HJID AS ANNOTATION_HJID,
		GML.POINT.GEOM AS GEOM
	FROM
		GML.AIXM_POINT_PT
		INNER JOIN GML.AIXM_POINT ON GML.AIXM_POINT_PT.POINT_HJID = GML.AIXM_POINT.HJID
		INNER JOIN GML.POINT ON GML.AIXM_POINT.HJID = GML.POINT.HJID
		LEFT JOIN GML.AIXM_POINT_ANNOTATION_LINK ON GML.AIXM_POINT.HJID = GML.AIXM_POINT_ANNOTATION_LINK.AIXM_POINT_HJID
		LEFT JOIN NOTE.NOTE_P ON GML.AIXM_POINT_ANNOTATION_LINK.ANNOTATION_HJID = NOTE.NOTE_P.HJID
);

CREATE INDEX IF NOT EXISTS IDX_AIXM_POINT_PT_HJID ON GML.AIXM_POINT_PT_VIEW (HJID);

CREATE INDEX IF NOT EXISTS IDX_AIXM_POINT_PT_GEOM ON GML.AIXM_POINT_PT_VIEW USING GIST (GEOM);

CREATE MATERIALIZED VIEW GML.AIXM_ELEVATED_POINT_PT_VIEW AS (
	SELECT
		GML.AIXM_ELEVATEDPOINT_PT.HJID,
        GML.POINT.ID,
		GML.AIXM_ELEVATED_POINT.HORIZONTALACCURACY,
		GML.AIXM_ELEVATED_POINT.HORIZONTALACCURACY_UOM,
        GML.AIXM_ELEVATED_POINT.HORIZONTALACCURACY_ACCURACY,
		GML.AIXM_ELEVATED_POINT.HORIZONTALACCURACY_NILREASON,
		GML.AIXM_ELEVATED_POINT.GEOIDUNDULATION,
		GML.AIXM_ELEVATED_POINT.GEOIDUNDULATION_NILREASON,
        GML.AIXM_ELEVATED_POINT.verticaldatum,
        GML.AIXM_ELEVATED_POINT.verticaldatum_nilreason,
		GML.AIXM_ELEVATED_POINT.ELEVATION,
		GML.AIXM_ELEVATED_POINT.ELEVATION_UOM,
        GML.AIXM_ELEVATED_POINT.ELEVATION_ACCURACY,
		GML.AIXM_ELEVATED_POINT.ELEVATION_NILREASON,
		NOTE.NOTE_P.HJID AS ANNOTATION_HJID,
		POINT.GEOM AS GEOM
	FROM
		GML.AIXM_ELEVATEDPOINT_PT
		INNER JOIN GML.AIXM_ELEVATED_POINT ON GML.AIXM_ELEVATEDPOINT_PT.ELEVATED_POINT_HJID = GML.AIXM_ELEVATED_POINT.HJID
		INNER JOIN GML.POINT ON GML.AIXM_ELEVATED_POINT.HJID = GML.POINT.HJID
		LEFT JOIN GML.AIXM_ELEVATED_POINT_ANNOTATION_LINK ON GML.AIXM_ELEVATED_POINT.HJID = GML.AIXM_ELEVATED_POINT_ANNOTATION_LINK.AIXM_ELEVATED_POINT_HJID
		LEFT JOIN NOTE.NOTE_P ON GML.AIXM_ELEVATED_POINT_ANNOTATION_LINK.ANNOTATION_HJID = NOTE.NOTE_P.HJID
);

CREATE INDEX IF NOT EXISTS IDX_AIXM_ELEVATED_POINT_PT_HJID ON GML.AIXM_ELEVATED_POINT_PT_VIEW (HJID);

CREATE INDEX IF NOT EXISTS IDX_AIXM_ELEVATED_POINT_PT_GEOM ON GML.AIXM_POINT_PT_VIEW USING GIST (GEOM);

CREATE INDEX IF NOT EXISTS IDX_ARC_HJID ON GML.ARC (HJID);

CREATE INDEX IF NOT EXISTS IDX_ARC_INDEX ON GML.ARC (INDEX);

CREATE INDEX IF NOT EXISTS IDX_ARC_GML_POINT_HJID ON GML.ARC (GML_POINT_HJID);

CREATE INDEX IF NOT EXISTS IDX_ARC_CURVE_HJID ON GML.ARC (CURVE_HJID);

CREATE INDEX IF NOT EXISTS IDX_ARC_BULK_COVERING ON GML.ARC (CURVE_HJID, HJID) INCLUDE (GML_POINT_HJID, INDEX);

CREATE INDEX IF NOT EXISTS IDX_CIRCLE_HJID ON GML.CIRCLE (HJID);

CREATE INDEX IF NOT EXISTS IDX_CIRCLE_INDEX ON GML.CIRCLE (INDEX);

CREATE INDEX IF NOT EXISTS IDX_CIRCLE_GML_POINT_HJID ON GML.CIRCLE (GML_POINT_HJID);

CREATE INDEX IF NOT EXISTS IDX_CIRCLE_CURVE_HJID ON GML.CIRCLE (CURVE_HJID);

CREATE INDEX IF NOT EXISTS IDX_CIRCLE_BULK_COVERING ON GML.CIRCLE (CURVE_HJID, HJID) INCLUDE (GML_POINT_HJID, INDEX);

CREATE INDEX IF NOT EXISTS IDX_GEODESIC_HJID ON GML.GEODESIC (HJID);

CREATE INDEX IF NOT EXISTS IDX_GEODESIC_INDEX ON GML.GEODESIC (INDEX);

CREATE INDEX IF NOT EXISTS IDX_GEODESIC_CURVE_HJID ON GML.GEODESIC (CURVE_HJID);

CREATE INDEX IF NOT EXISTS IDX_GEODESIC_GEOM ON GML.GEODESIC USING GIST (GEOM);

CREATE INDEX IF NOT EXISTS IDX_GEODESIC_BULK_COVERING ON GML.GEODESIC (CURVE_HJID, HJID, INDEX);

CREATE INDEX IF NOT EXISTS IDX_LINESTRING_HJID ON GML.LINESTRING (HJID);

CREATE INDEX IF NOT EXISTS IDX_LINESTRING_INDEX ON GML.LINESTRING (INDEX);

CREATE INDEX IF NOT EXISTS IDX_LINESTRING_CURVE_HJID ON GML.LINESTRING (CURVE_HJID);

CREATE INDEX IF NOT EXISTS IDX_LINESTRING_GEOM ON GML.LINESTRING USING GIST (GEOM);

CREATE INDEX IF NOT EXISTS IDX_LINESTRING_BULK_COVERING ON GML.LINESTRING (CURVE_HJID, HJID, INDEX);

CREATE INDEX IF NOT EXISTS IDX_CURVE_HJID ON GML.CURVE (HJID);

CREATE INDEX IF NOT EXISTS IDX_CURVE_ID_COVERING ON GML.CURVE (ID, HJID);

CREATE INDEX IF NOT EXISTS IDX_GML_CURVE_HREF_SUBSTRING ON GML.GML_CURVE (
	SUBSTRING(
		HREF
		FROM
			'([a-f0-9]{8}-[a-f0-9]{4}-[a-f0-9]{4}-[a-f0-9]{4}-[a-f0-9]{12})$'
	)
)
WHERE
	GEOMETRIC_TYPE = 'REF';

CREATE INDEX IF NOT EXISTS IDX_GML_CURVE_HJID ON GML.GML_CURVE (HJID);

CREATE INDEX IF NOT EXISTS IDX_GML_CURVE_INDEX ON GML.GML_CURVE (INDEX);

CREATE INDEX IF NOT EXISTS IDX_AIXM_CURVE_HJID ON GML.AIXM_CURVE (HJID);

CREATE INDEX IF NOT EXISTS IDX_AIXM_ELEVATED_CURVE_HJID ON GML.AIXM_ELEVATED_CURVE (HJID);

CREATE INDEX IF NOT EXISTS IDX_AIXM_CURVE_PT_HJID ON GML.AIXM_CURVE_PT (HJID);

CREATE INDEX IF NOT EXISTS IDX_AIXM_CURVE_PT_CURVE_HJID ON GML.AIXM_CURVE_PT (CURVE_HJID);

CREATE INDEX IF NOT EXISTS IDX_AIXM_CURVE_PT_COVERING ON GML.AIXM_CURVE_PT (HJID, CURVE_HJID);

CREATE INDEX IF NOT EXISTS IDX_AIXM_ELEVATEDCURVE_PT_HJID ON GML.AIXM_ELEVATEDCURVE_PT (HJID);

CREATE INDEX IF NOT EXISTS IDX_AIXM_ELEVATEDCURVE_PT_CURVE_HJID ON GML.AIXM_ELEVATEDCURVE_PT (ELEVATED_CURVE_HJID);

CREATE INDEX IF NOT EXISTS IDX_AIXM_ELEVATEDCURVE_PT_COVERING ON GML.AIXM_ELEVATEDCURVE_PT (HJID, ELEVATED_CURVE_HJID);

CREATE MATERIALIZED VIEW GML.CURVE_VIEW AS (
	WITH
		NORMALIZED_CIRCLE AS (
			SELECT
				CIRCLE.HJID,
				CIRCLE.CURVE_HJID,
				CIRCLE.INDEX,
				POINT.GEOM::GEOGRAPHY AS GEOM,
				CASE CIRCLE.RADIUS_UOM
					WHEN 0 THEN CIRCLE.RADIUS_VALUE
					WHEN 1 THEN CIRCLE.RADIUS_VALUE * 1000::NUMERIC
					WHEN 2 THEN CIRCLE.RADIUS_VALUE * 0.3048
					WHEN 3 THEN CIRCLE.RADIUS_VALUE * 1609.344
					WHEN 4 THEN CIRCLE.RADIUS_VALUE * 1852::NUMERIC
					ELSE NULL::NUMERIC
				END AS RADIUS_M
			FROM
				GML.CIRCLE
				JOIN GML.GML_POINT ON CIRCLE.GML_POINT_HJID = GML_POINT.HJID
				JOIN GML.POINT ON POINT.HJID = GML_POINT.HJID
		),
		NORMALIZED_ARC AS (
			SELECT
				ARC.HJID,
				ARC.CURVE_HJID,
				ARC.INDEX,
				POINT.GEOM::GEOGRAPHY AS CENTER_GEOG,
				CASE ARC.RADIUS_UOM
					WHEN 0 THEN ARC.RADIUS_VALUE
					WHEN 1 THEN ARC.RADIUS_VALUE * 1000::NUMERIC
					WHEN 2 THEN ARC.RADIUS_VALUE * 0.3048
					WHEN 3 THEN ARC.RADIUS_VALUE * 1609.344
					WHEN 4 THEN ARC.RADIUS_VALUE * 1852::NUMERIC
					ELSE NULL::NUMERIC
				END AS RADIUS_M,
				CASE ARC.START_ANGLE_UOM
					WHEN 0 THEN RADIANS(ARC.START_ANGLE_VALUE::DOUBLE PRECISION)
					WHEN 1 THEN ARC.START_ANGLE_VALUE::DOUBLE PRECISION
					ELSE NULL::DOUBLE PRECISION
				END AS START_ANGLE_RAD,
				(
					CASE ARC.END_ANGLE_UOM
						WHEN 0 THEN RADIANS(ARC.END_ANGLE_VALUE::DOUBLE PRECISION)
						WHEN 1 THEN ARC.END_ANGLE_VALUE::DOUBLE PRECISION
						ELSE NULL::DOUBLE PRECISION
					END - CASE ARC.START_ANGLE_UOM
						WHEN 0 THEN RADIANS(ARC.START_ANGLE_VALUE::DOUBLE PRECISION)
						WHEN 1 THEN ARC.START_ANGLE_VALUE::DOUBLE PRECISION
						ELSE NULL::DOUBLE PRECISION
					END
				) / 32::DOUBLE PRECISION AS STEP_SIZE_RAD
			FROM
				GML.ARC
				JOIN GML.GML_POINT ON ARC.GML_POINT_HJID = GML_POINT.HJID
				JOIN GML.POINT ON POINT.HJID = GML_POINT.HJID
		),
		SEGMENT AS (
			SELECT
				GEODESIC.HJID,
				GEODESIC.CURVE_HJID,
				GEODESIC.INDEX,
				ST_SEGMENTIZE (
					ST_MAKELINE (
						POINT.GEOM
						ORDER BY
							GEODESIC.INDEX,
							GML_POINT.INDEX
					)::GEOGRAPHY,
					1000::DOUBLE PRECISION
				)::GEOMETRY AS GEOM
			FROM
				GML.GEODESIC
				JOIN GML.GML_POINT ON GEODESIC.HJID = GML_POINT.GML_POINT_HJID
				JOIN GML.POINT ON GML_POINT.HJID = POINT.HJID
			GROUP BY
				GEODESIC.HJID
			UNION ALL
			SELECT
				GEODESIC.HJID,
				GEODESIC.CURVE_HJID,
				GEODESIC.INDEX,
				ST_SEGMENTIZE (GEODESIC.GEOM::GEOGRAPHY, 1000::DOUBLE PRECISION)::GEOMETRY AS GEOM
			FROM
				GML.GEODESIC
			WHERE
				GEODESIC.POS_LIST <> ''::TEXT
			UNION ALL
			SELECT
				LINESTRING.HJID,
				LINESTRING.CURVE_HJID,
				LINESTRING.INDEX,
				ST_MAKELINE (
					POINT.GEOM
					ORDER BY
						LINESTRING.INDEX,
						GML_POINT.INDEX
				) AS GEOM
			FROM
				GML.LINESTRING
				JOIN GML.GML_POINT ON LINESTRING.HJID = GML_POINT.GML_POINT_HJID
				JOIN GML.POINT ON GML_POINT.HJID = POINT.HJID
			GROUP BY
				LINESTRING.HJID
			UNION ALL
			SELECT
				LINESTRING.HJID,
				LINESTRING.CURVE_HJID,
				LINESTRING.INDEX,
				LINESTRING.GEOM
			FROM
				GML.LINESTRING
			WHERE
				LINESTRING.POS_LIST <> ''::TEXT
			UNION ALL
			SELECT
				NORMALIZED_CIRCLE.HJID,
				NORMALIZED_CIRCLE.CURVE_HJID,
				NORMALIZED_CIRCLE.INDEX,
				ST_BOUNDARY (
					ST_BUFFER (
						NORMALIZED_CIRCLE.GEOM,
						NORMALIZED_CIRCLE.RADIUS_M::DOUBLE PRECISION,
						'quad_segs=16'::TEXT
					)::GEOMETRY
				) AS GEOM
			FROM
				NORMALIZED_CIRCLE
			UNION ALL
			SELECT
				NORMALIZED_ARC.HJID,
				NORMALIZED_ARC.CURVE_HJID,
				NORMALIZED_ARC.INDEX,
				ST_MAKELINE (
					S.PT
					ORDER BY
						S.INCREMENT
				) AS GEOM
			FROM
				NORMALIZED_ARC
				CROSS JOIN LATERAL (
					SELECT
						INCREMENT.INCREMENT,
						ST_PROJECT (
							NORMALIZED_ARC.CENTER_GEOG,
							NORMALIZED_ARC.RADIUS_M::DOUBLE PRECISION,
							NORMALIZED_ARC.START_ANGLE_RAD + NORMALIZED_ARC.STEP_SIZE_RAD * INCREMENT.INCREMENT::DOUBLE PRECISION
						)::GEOMETRY AS PT
					FROM
						GENERATE_SERIES(0, 32) INCREMENT (INCREMENT)
				) S
			GROUP BY
				NORMALIZED_ARC.HJID,
				NORMALIZED_ARC.CURVE_HJID,
				NORMALIZED_ARC.INDEX
		)
	SELECT
		CURVE.ID,
		CURVE.HJID,
		ST_MAKELINE (
			ST_SNAPTOGRID (SEGMENT.GEOM, 0.00001::DOUBLE PRECISION)
			ORDER BY
				SEGMENT.INDEX
		) AS GEOM
	FROM
		SEGMENT
		JOIN GML.CURVE ON SEGMENT.CURVE_HJID = CURVE.HJID
	GROUP BY
		CURVE.ID,
		CURVE.HJID
);

CREATE INDEX IF NOT EXISTS IDX_CURVE_VIEW_HJID ON GML.CURVE_VIEW (HJID);

CREATE INDEX IF NOT EXISTS IDX_CURVE_VIEW_GEOM ON GML.CURVE_VIEW USING GIST (GEOM);

CREATE MATERIALIZED VIEW GML.AIXM_ELEVATED_CURVE_PT_VIEW AS (
	SELECT
		AIXM_ELEVATEDCURVE_PT.HJID,
		GML.CURVE_VIEW.ID,
		AIXM_ELEVATED_CURVE.ELEVATION,
		AIXM_ELEVATED_CURVE.ELEVATION_UOM,
        AIXM_ELEVATED_CURVE.ELEVATION_ACCURACY,
		AIXM_ELEVATED_CURVE.ELEVATION_NILREASON,
		AIXM_ELEVATED_CURVE.GEOIDUNDULATION,
		AIXM_ELEVATED_CURVE.GEOIDUNDULATION_UOM,
        AIXM_ELEVATED_CURVE.GEOIDUNDULATION_ACCURACY,
		AIXM_ELEVATED_CURVE.GEOIDUNDULATION_NILREASON,
		AIXM_ELEVATED_CURVE.VERTICALDATUM,
		AIXM_ELEVATED_CURVE.VERTICALDATUM_NILREASON,
		AIXM_ELEVATED_CURVE.HORIZONTALACCURACY,
		AIXM_ELEVATED_CURVE.HORIZONTALACCURACY_UOM,
        AIXM_ELEVATED_CURVE.HORIZONTALACCURACY_ACCURACY,
		AIXM_ELEVATED_CURVE.HORIZONTALACCURACY_NILREASON,
		NOTE_P.HJID AS ANNOTATION_HJID,
		GML.CURVE_VIEW.GEOM
	FROM
		GML.AIXM_ELEVATEDCURVE_PT
		INNER JOIN GML.AIXM_ELEVATED_CURVE ON AIXM_ELEVATEDCURVE_PT.ELEVATED_CURVE_HJID = AIXM_ELEVATED_CURVE.HJID
		INNER JOIN GML.CURVE_VIEW ON AIXM_ELEVATED_CURVE.HJID = GML.CURVE_VIEW.HJID
		LEFT JOIN GML.AIXM_ELEVATED_CURVE_ANNOTATION_LINK ON AIXM_ELEVATED_CURVE.HJID = AIXM_ELEVATED_CURVE_ANNOTATION_LINK.AIXM_ELEVATED_CURVE_HJID
		LEFT JOIN NOTE.NOTE_P ON AIXM_ELEVATED_CURVE_ANNOTATION_LINK.ANNOTATION_HJID = NOTE_P.HJID
);

CREATE INDEX IF NOT EXISTS IDX_AIXM_ELEVATED_CURVE_PT_HJID ON GML.AIXM_ELEVATED_CURVE_PT_VIEW (HJID);

CREATE INDEX IF NOT EXISTS IDX_AIXM_ELEVATED_CURVE_PT_GEOM ON GML.AIXM_ELEVATED_CURVE_PT_VIEW USING GIST (GEOM);

CREATE MATERIALIZED VIEW GML.AIXM_CURVE_PT_VIEW AS (
	SELECT
		AIXM_CURVE_PT.HJID,
		GML.CURVE_VIEW.ID,
		AIXM_CURVE.HORIZONTALACCURACY,
		AIXM_CURVE.HORIZONTALACCURACY_UOM,
        AIXM_CURVE.HORIZONTALACCURACY_ACCURACY,
		AIXM_CURVE.HORIZONTALACCURACY_NILREASON,
		NOTE_P.HJID AS ANNOTATION_HJID,
		GML.CURVE_VIEW.GEOM
	FROM
		GML.AIXM_CURVE_PT
		INNER JOIN GML.AIXM_CURVE ON AIXM_CURVE_PT.CURVE_HJID = AIXM_CURVE.HJID
		INNER JOIN GML.CURVE_VIEW ON AIXM_CURVE.HJID = GML.CURVE_VIEW.HJID
		LEFT JOIN GML.AIXM_CURVE_ANNOTATION_LINK ON AIXM_CURVE.HJID = AIXM_CURVE_ANNOTATION_LINK.AIXM_CURVE_HJID
		LEFT JOIN NOTE.NOTE_P ON AIXM_CURVE_ANNOTATION_LINK.ANNOTATION_HJID = NOTE_P.HJID
);

CREATE INDEX IF NOT EXISTS IDX_AIXM_CURVE_PT_HJID ON GML.AIXM_CURVE_PT_VIEW (HJID);

CREATE INDEX IF NOT EXISTS IDX_AIXM_CURVE_PT_GEOM ON GML.AIXM_CURVE_PT_VIEW USING GIST (GEOM);

CREATE INDEX IF NOT EXISTS IDX_RING_HJID ON GML.RING (HJID);

CREATE INDEX IF NOT EXISTS IDX_RING_INDEX ON GML.RING (INDEX);

CREATE INDEX IF NOT EXISTS IDX_RING_HJID_INDEX ON GML.RING (HJID) INCLUDE (INDEX);

CREATE INDEX IF NOT EXISTS IDX_RING_INTERIOR_HJID ON GML.RING (INTERIOR_HJID);

CREATE INDEX IF NOT EXISTS IDX_RING_GML_CURVE_LINK_GML_CURVE_HJID ON GML.RING_GML_CURVE_LINK (GML_CURVE_HJID);

CREATE INDEX IF NOT EXISTS IDX_RING_GML_CURVE_LINK_RING_HJID ON GML.RING_GML_CURVE_LINK (RING_HJID);

CREATE INDEX IF NOT EXISTS IDX_RING_GML_CURVE_LINK_COMPOSITE ON GML.RING_GML_CURVE_LINK (GML_CURVE_HJID, RING_HJID);

CREATE INDEX IF NOT EXISTS IDX_POLYGON_HJID ON GML.POLYGON (HJID);

CREATE INDEX IF NOT EXISTS IDX_POLYGON_INDEX ON GML.POLYGON (INDEX);

CREATE INDEX IF NOT EXISTS IDX_INDEX_EXTERIOR_HJID ON GML.POLYGON (EXTERIOR_HJID);

CREATE INDEX IF NOT EXISTS IDX_INDEX_POLYGON_HJID ON GML.POLYGON (POLYGON_HJID);

CREATE INDEX IF NOT EXISTS IDX_SURFACE_HJID ON GML.SURFACE (HJID);

CREATE MATERIALIZED VIEW GML.SURFACE_VIEW AS (
	WITH
		UNION_CURVE AS (
			SELECT
				UNIFIED.RING_HJID,
				UNIFIED.RING_INDEX,
				UNIFIED.INTERIOR_HJID,
				CURVE_VIEW.ID AS CURVE_ID,
				UNIFIED.CURVE_HJID,
				UNIFIED.CURVE_INDEX,
				CURVE_VIEW.GEOM,
				UNIFIED.TYPE
			FROM
				(
					SELECT
						RING.HJID AS RING_HJID,
						RING.INDEX AS RING_INDEX,
						RING.INTERIOR_HJID,
						GML_CURVE.HJID AS CURVE_HJID,
						GML_CURVE.INDEX AS CURVE_INDEX,
						GML_CURVE.HJID AS TARGET_LOOKUP_HJID,
						GML_CURVE.GEOMETRIC_TYPE AS TYPE
					FROM
						GML.RING
						JOIN GML.RING_GML_CURVE_LINK ON RING.HJID = RING_GML_CURVE_LINK.RING_HJID
						JOIN GML.GML_CURVE ON GML_CURVE.HJID = RING_GML_CURVE_LINK.GML_CURVE_HJID
					WHERE
						GML_CURVE.GEOMETRIC_TYPE::TEXT = 'GML'::TEXT
					UNION ALL
					SELECT
						RING.HJID AS RING_HJID,
						RING.INDEX AS RING_INDEX,
						RING.INTERIOR_HJID,
						GML_CURVE.HJID AS CURVE_HJID,
						GML_CURVE.INDEX AS CURVE_INDEX,
						AIXM_CURVE.HJID AS TARGET_LOOKUP_HJID,
						GML_CURVE.GEOMETRIC_TYPE AS TYPE
					FROM
						GML.RING
						JOIN GML.RING_GML_CURVE_LINK ON RING.HJID = RING_GML_CURVE_LINK.RING_HJID
						JOIN GML.GML_CURVE ON GML_CURVE.HJID = RING_GML_CURVE_LINK.GML_CURVE_HJID
						CROSS JOIN LATERAL (
							SELECT
								"substring" (
									GML_CURVE.HREF::TEXT,
									'([a-f0-9]{8}-[a-f0-9]{4}-[a-f0-9]{4}-[a-f0-9]{4}-[a-f0-9]{12})$'::TEXT
								) AS HREF_SUB
						) SUB
						JOIN AIXM.AIXM_FEATURE ON SUB.HREF_SUB = AIXM_FEATURE.IDENTIFIER::TEXT
						JOIN AIRSPACE.GEOBORDER_F ON AIXM_FEATURE.HJID = GEOBORDER_F.HJID
						JOIN AIRSPACE.GEOBORDER_TP ON GEOBORDER_F.HJID = GEOBORDER_TP.TIMESLICE_HJID
						JOIN AIRSPACE.GEOBORDER_T ON GEOBORDER_TP.GEOBORDERTIMESLICE_HJID = GEOBORDER_T.HJID
						JOIN AIXM.AIXM_TIMESLICE ON GEOBORDER_T.HJID = AIXM_TIMESLICE.HJID
						JOIN AIRSPACE.GBRDRTMSLCTP_BRDR_LINK ON GEOBORDER_T.HJID = GBRDRTMSLCTP_BRDR_LINK.GEOBORDER_T_HJID
						JOIN GML.AIXM_CURVE_PT ON GBRDRTMSLCTP_BRDR_LINK.BORDER_HJID = AIXM_CURVE_PT.HJID
						JOIN GML.AIXM_CURVE ON AIXM_CURVE_PT.CURVE_HJID = AIXM_CURVE.HJID
					WHERE
						GML_CURVE.GEOMETRIC_TYPE::TEXT = 'REF'::TEXT
				) UNIFIED
				JOIN GML.CURVE_VIEW ON UNIFIED.TARGET_LOOKUP_HJID = CURVE_VIEW.HJID
		),
		ORDERED_CURVE AS (
			SELECT
				UNION_CURVE.RING_HJID,
				UNION_CURVE.RING_INDEX,
				UNION_CURVE.INTERIOR_HJID,
				UNION_CURVE.CURVE_ID,
				UNION_CURVE.CURVE_HJID,
				UNION_CURVE.CURVE_INDEX,
				UNION_CURVE.TYPE,
				UNION_CURVE.GEOM,
				COUNT(*) OVER (
					PARTITION BY
						UNION_CURVE.RING_HJID
				) AS CURVE_COUNT,
				COALESCE(
					LAG(UNION_CURVE.GEOM) OVER (
						PARTITION BY
							UNION_CURVE.RING_HJID
						ORDER BY
							UNION_CURVE.CURVE_INDEX
					),
					LAST_VALUE(UNION_CURVE.GEOM) OVER (
						PARTITION BY
							UNION_CURVE.RING_HJID
						ORDER BY
							UNION_CURVE.CURVE_INDEX ROWS BETWEEN UNBOUNDED PRECEDING
							AND UNBOUNDED FOLLOWING
					)
				) AS PREV_GEOM,
				COALESCE(
					LAG(UNION_CURVE.TYPE) OVER (
						PARTITION BY
							UNION_CURVE.RING_HJID
						ORDER BY
							UNION_CURVE.CURVE_INDEX
					),
					LAST_VALUE(UNION_CURVE.TYPE) OVER (
						PARTITION BY
							UNION_CURVE.RING_HJID
						ORDER BY
							UNION_CURVE.CURVE_INDEX ROWS BETWEEN UNBOUNDED PRECEDING
							AND UNBOUNDED FOLLOWING
					)
				) AS PREV_TYPE,
				COALESCE(
					LEAD(UNION_CURVE.GEOM) OVER (
						PARTITION BY
							UNION_CURVE.RING_HJID
						ORDER BY
							UNION_CURVE.CURVE_INDEX
					),
					FIRST_VALUE(UNION_CURVE.GEOM) OVER (
						PARTITION BY
							UNION_CURVE.RING_HJID
						ORDER BY
							UNION_CURVE.CURVE_INDEX ROWS BETWEEN UNBOUNDED PRECEDING
							AND UNBOUNDED FOLLOWING
					)
				) AS NEXT_GEOM,
				COALESCE(
					LEAD(UNION_CURVE.TYPE) OVER (
						PARTITION BY
							UNION_CURVE.RING_HJID
						ORDER BY
							UNION_CURVE.CURVE_INDEX
					),
					FIRST_VALUE(UNION_CURVE.TYPE) OVER (
						PARTITION BY
							UNION_CURVE.RING_HJID
						ORDER BY
							UNION_CURVE.CURVE_INDEX ROWS BETWEEN UNBOUNDED PRECEDING
							AND UNBOUNDED FOLLOWING
					)
				) AS NEXT_TYPE
			FROM
				UNION_CURVE
		),
		CUT_CURVE AS (
			SELECT
				ORDERED_CURVE.RING_HJID,
				ORDERED_CURVE.RING_INDEX,
				ORDERED_CURVE.INTERIOR_HJID,
				ORDERED_CURVE.CURVE_INDEX,
				CASE
					WHEN ORDERED_CURVE.TYPE::TEXT = 'REF'::TEXT THEN ST_SNAPTOGRID (
						ST_LINESUBSTRING (
							ORDERED_CURVE.GEOM,
							LEAST(ADJ.CUT_START, ADJ.CUT_END),
							GREATEST(ADJ.CUT_START, ADJ.CUT_END)
						),
						0.00001::DOUBLE PRECISION
					)
					ELSE ORDERED_CURVE.GEOM
				END AS GEOM
			FROM
				ORDERED_CURVE
				CROSS JOIN LATERAL (
					SELECT
						CASE
							WHEN ORDERED_CURVE.PREV_GEOM IS NOT NULL THEN ST_LINELOCATEPOINT (
								ORDERED_CURVE.GEOM,
								ST_ENDPOINT (ORDERED_CURVE.PREV_GEOM)
							)
							ELSE 0.0::DOUBLE PRECISION
						END AS CUT_START,
						CASE
							WHEN ORDERED_CURVE.NEXT_GEOM IS NOT NULL THEN ST_LINELOCATEPOINT (
								ORDERED_CURVE.GEOM,
								ST_STARTPOINT (ORDERED_CURVE.NEXT_GEOM)
							)
							ELSE 1.0::DOUBLE PRECISION
						END AS CUT_END
				) ADJ
			WHERE
				ORDERED_CURVE.CURVE_COUNT >= 2
		),
		CONCAVE_HULL AS (
			SELECT
				CUT_CURVE.RING_HJID,
				CUT_CURVE.RING_INDEX,
				CUT_CURVE.INTERIOR_HJID,
				ST_LINEMERGE (ST_COLLECT (CUT_CURVE.GEOM)) AS GEOM,
				ST_CONCAVEHULL (
					ST_COLLECT (ST_BOUNDARY (CUT_CURVE.GEOM)),
					0.99::DOUBLE PRECISION
				) AS CONCAVE_GEOM
			FROM
				CUT_CURVE
			GROUP BY
				CUT_CURVE.RING_HJID,
				CUT_CURVE.RING_INDEX,
				CUT_CURVE.INTERIOR_HJID
		),
		BOUNDARY_CURVE AS (
			SELECT
				CONCAVE_HULL.RING_HJID,
				CONCAVE_HULL.RING_INDEX,
				CONCAVE_HULL.INTERIOR_HJID,
				CONCAVE_HULL.GEOM,
				CASE
					WHEN ST_GEOMETRYTYPE (CONCAVE_HULL.CONCAVE_GEOM) = 'ST_LineString'::TEXT THEN CONCAVE_HULL.CONCAVE_GEOM
					ELSE ST_BOUNDARY (CONCAVE_HULL.CONCAVE_GEOM)
				END AS CONCAVE_GEOM
			FROM
				CONCAVE_HULL
		),
		COMBINED_RINGS AS (
			SELECT
				ORDERED_CURVE.RING_HJID,
				ORDERED_CURVE.RING_INDEX,
				ORDERED_CURVE.INTERIOR_HJID,
				ST_MAKEPOLYGON (
					ST_ADDPOINT (
						ORDERED_CURVE.GEOM,
						ST_STARTPOINT (ORDERED_CURVE.GEOM)
					)
				) AS GEOM
			FROM
				ORDERED_CURVE
			WHERE
				ORDERED_CURVE.CURVE_COUNT = 1
				AND ST_NPOINTS (ORDERED_CURVE.GEOM) >= 3
			UNION ALL
			SELECT
				BOUNDARY_CURVE.RING_HJID,
				BOUNDARY_CURVE.RING_INDEX,
				BOUNDARY_CURVE.INTERIOR_HJID,
				ST_BUILDAREA (
					ST_UNARYUNION (
						ST_COLLECT (BOUNDARY_CURVE.GEOM, BOUNDARY_CURVE.CONCAVE_GEOM),
						0.00001
					)
				) AS GEOM
			FROM
				BOUNDARY_CURVE
			GROUP BY
				BOUNDARY_CURVE.RING_HJID,
				BOUNDARY_CURVE.RING_INDEX,
				BOUNDARY_CURVE.INTERIOR_HJID,
				BOUNDARY_CURVE.GEOM,
				BOUNDARY_CURVE.CONCAVE_GEOM
		),
		ASSEMBLED_POLYGONS AS (
			SELECT
				POLYGON.POLYGON_HJID,
				EXTERIOR_RING.RING_HJID AS EXTERIOR_RING_HJID,
				CASE
					WHEN COUNT(INTERIOR_RING.GEOM) = 0 THEN EXTERIOR_RING.GEOM
					ELSE ST_MAKEPOLYGON (
						ST_EXTERIORRING (EXTERIOR_RING.GEOM),
						ARRAY_AGG(ST_EXTERIORRING (INTERIOR_RING.GEOM))
					)
				END AS GEOM
			FROM
				GML.POLYGON
				JOIN COMBINED_RINGS EXTERIOR_RING ON POLYGON.EXTERIOR_HJID = EXTERIOR_RING.RING_HJID
				LEFT JOIN COMBINED_RINGS INTERIOR_RING ON POLYGON.HJID = INTERIOR_RING.INTERIOR_HJID
			GROUP BY
				POLYGON.POLYGON_HJID,
				POLYGON.HJID,
				EXTERIOR_RING.RING_HJID,
				EXTERIOR_RING.GEOM
		)
	SELECT
		SURFACE.HJID,
		SURFACE.ID,
		ST_MULTI (ST_COLLECT (ASSEMBLED_POLYGONS.GEOM)) AS GEOM,
		ASSEMBLED_POLYGONS.EXTERIOR_RING_HJID
	FROM
		GML.SURFACE
		JOIN ASSEMBLED_POLYGONS ON SURFACE.HJID = ASSEMBLED_POLYGONS.POLYGON_HJID
	GROUP BY
		SURFACE.HJID,
		SURFACE.ID,
		ASSEMBLED_POLYGONS.EXTERIOR_RING_HJID
);

CREATE INDEX IF NOT EXISTS IDX_SURFACE_VIEW_HJID ON GML.SURFACE_VIEW (HJID);

CREATE INDEX IF NOT EXISTS IDX_SURFACE_VIEW_GEOM ON GML.SURFACE_VIEW USING GIST (GEOM);

CREATE MATERIALIZED VIEW GML.AIXM_SURFACE_PT_VIEW AS (
	SELECT
        GML.AIXM_SURFACE_PT.HJID,
		GML.SURFACE_VIEW.ID,
        AIXM_SURFACE.HORIZONTALACCURACY,
        AIXM_SURFACE.HORIZONTALACCURACY_UOM,
        AIXM_SURFACE.HORIZONTALACCURACY_ACCURACY,
        AIXM_SURFACE.HORIZONTALACCURACY_NILREASON,
		NOTE_P.HJID AS ANNOTATION_HJID,
		GML.SURFACE_VIEW.GEOM
	FROM
		GML.AIXM_SURFACE_PT
		INNER JOIN GML.AIXM_SURFACE ON AIXM_SURFACE_PT.SURFACE_HJID = AIXM_SURFACE.HJID
		INNER JOIN GML.SURFACE_VIEW ON AIXM_SURFACE.HJID = SURFACE_VIEW.HJID
		LEFT JOIN GML.AIXM_SURFACE_ANNOTATION_LINK ON AIXM_SURFACE.HJID = AIXM_SURFACE_ANNOTATION_LINK.AIXM_SURFACE_HJID
		LEFT JOIN NOTE.NOTE_P ON AIXM_SURFACE_ANNOTATION_LINK.ANNOTATION_HJID = NOTE_P.HJID
);

CREATE MATERIALIZED VIEW GML.AIXM_ELEVATED_SURFACE_PT_VIEW AS (
	SELECT
		GML.AIXM_ELEVATEDSURFACE_PT.HJID,
		GML.SURFACE_VIEW.ID,
        AIXM_ELEVATED_SURFACE.ELEVATION,
		AIXM_ELEVATED_SURFACE.ELEVATION_UOM,
        AIXM_ELEVATED_SURFACE.ELEVATION_ACCURACY,
		AIXM_ELEVATED_SURFACE.ELEVATION_NILREASON,
		AIXM_ELEVATED_SURFACE.GEOIDUNDULATION,
		AIXM_ELEVATED_SURFACE.GEOIDUNDULATION_UOM,
        AIXM_ELEVATED_SURFACE.GEOIDUNDULATION_ACCURACY,
		AIXM_ELEVATED_SURFACE.GEOIDUNDULATION_NILREASON,
		AIXM_ELEVATED_SURFACE.VERTICALDATUM,
		AIXM_ELEVATED_SURFACE.VERTICALDATUM_NILREASON,
		AIXM_ELEVATED_SURFACE.HORIZONTALACCURACY,
        AIXM_ELEVATED_SURFACE.HORIZONTALACCURACY_ACCURACY,
		AIXM_ELEVATED_SURFACE.HORIZONTALACCURACY_UOM,
		AIXM_ELEVATED_SURFACE.HORIZONTALACCURACY_NILREASON,
		NOTE_P.HJID AS ANNOTATION_HJID,
		GML.SURFACE_VIEW.GEOM
	FROM
		GML.AIXM_ELEVATEDSURFACE_PT
		JOIN GML.AIXM_ELEVATED_SURFACE ON AIXM_ELEVATEDSURFACE_PT.ELEVATED_SURFACE_HJID = AIXM_ELEVATED_SURFACE.HJID
		JOIN GML.SURFACE_VIEW ON AIXM_ELEVATED_SURFACE.HJID = SURFACE_VIEW.HJID
		LEFT JOIN GML.AIXM_ELEVATED_SURFACE_ANNOTATION_LINK ON AIXM_ELEVATED_SURFACE.HJID = AIXM_ELEVATED_SURFACE_ANNOTATION_LINK.AIXM_ELEVATED_SURFACE_HJID
		LEFT JOIN NOTE.NOTE_P ON AIXM_ELEVATED_SURFACE_ANNOTATION_LINK.ANNOTATION_HJID = NOTE_P.HJID
);