

INSERT INTO gml.curve_unlogged_table
	WITH
		NORMALIZED_CIRCLE AS (
			SELECT
				CIRCLE.HJID,
				CIRCLE.CURVE_HJID,
				CIRCLE.INDEX,
				POINT.GEOM::GEOGRAPHY AS GEOM,
				CASE CIRCLE.RADIUS_UOM
					WHEN 0 THEN CIRCLE.RADIUS_VALUE
					WHEN 1 THEN CIRCLE.RADIUS_VALUE * 1000::NUMERIC
					WHEN 2 THEN CIRCLE.RADIUS_VALUE * 0.3048
					WHEN 3 THEN CIRCLE.RADIUS_VALUE * 1609.344
					WHEN 4 THEN CIRCLE.RADIUS_VALUE * 1852::NUMERIC
					ELSE NULL::NUMERIC
				END AS RADIUS_M
			FROM
				GML.CIRCLE
				JOIN GML.GML_POINT ON CIRCLE.GML_POINT_HJID = GML_POINT.HJID
				JOIN GML.POINT ON POINT.HJID = GML_POINT.HJID
			WHERE CIRCLE.CURVE_HJID %% %1$d = %2$d
		),
		NORMALIZED_ARC AS (
			SELECT
				ARC.HJID,
				ARC.CURVE_HJID,
				ARC.INDEX,
				POINT.GEOM::GEOGRAPHY AS CENTER_GEOG,
				CASE ARC.RADIUS_UOM
					WHEN 0 THEN ARC.RADIUS_VALUE
					WHEN 1 THEN ARC.RADIUS_VALUE * 1000::NUMERIC
					WHEN 2 THEN ARC.RADIUS_VALUE * 0.3048
					WHEN 3 THEN ARC.RADIUS_VALUE * 1609.344
					WHEN 4 THEN ARC.RADIUS_VALUE * 1852::NUMERIC
					ELSE NULL::NUMERIC
				END AS RADIUS_M,
				CASE ARC.START_ANGLE_UOM
					WHEN 0 THEN RADIANS(ARC.START_ANGLE_VALUE::DOUBLE PRECISION)
					WHEN 1 THEN ARC.START_ANGLE_VALUE::DOUBLE PRECISION
					ELSE NULL::DOUBLE PRECISION
				END AS START_ANGLE_RAD,
				(
					CASE ARC.END_ANGLE_UOM
						WHEN 0 THEN RADIANS(ARC.END_ANGLE_VALUE::DOUBLE PRECISION)
						WHEN 1 THEN ARC.END_ANGLE_VALUE::DOUBLE PRECISION
						ELSE NULL::DOUBLE PRECISION
					END - CASE ARC.START_ANGLE_UOM
						WHEN 0 THEN RADIANS(ARC.START_ANGLE_VALUE::DOUBLE PRECISION)
						WHEN 1 THEN ARC.START_ANGLE_VALUE::DOUBLE PRECISION
						ELSE NULL::DOUBLE PRECISION
					END
				) / 32::DOUBLE PRECISION AS STEP_SIZE_RAD
			FROM
				GML.ARC
				JOIN GML.GML_POINT ON ARC.GML_POINT_HJID = GML_POINT.HJID
				JOIN GML.POINT ON POINT.HJID = GML_POINT.HJID
			WHERE ARC.CURVE_HJID %% %1$d = %2$d
		),
		SEGMENT AS (
			SELECT
				GEODESIC.HJID,
				GEODESIC.CURVE_HJID,
				GEODESIC.INDEX,
				ST_SEGMENTIZE (
					ST_MAKELINE (
						POINT.GEOM
						ORDER BY
							GEODESIC.INDEX,
							GML_POINT.INDEX
					)::GEOGRAPHY,
					1000::DOUBLE PRECISION
				)::GEOMETRY AS GEOM
			FROM
				GML.GEODESIC
				JOIN GML.GML_POINT ON GEODESIC.HJID = GML_POINT.GML_POINT_HJID
				JOIN GML.POINT ON GML_POINT.HJID = POINT.HJID
			WHERE GEODESIC.CURVE_HJID %% %1$d = %2$d
			GROUP BY
				GEODESIC.HJID
			UNION ALL
			SELECT
				GEODESIC.HJID,
				GEODESIC.CURVE_HJID,
				GEODESIC.INDEX,
				ST_SEGMENTIZE (GEODESIC.GEOM::GEOGRAPHY, 1000::DOUBLE PRECISION)::GEOMETRY AS GEOM
			FROM
				GML.GEODESIC
			WHERE
				GEODESIC.POS_LIST <> ''::TEXT
				AND
				GEODESIC.CURVE_HJID %% %1$d = %2$d
			UNION ALL
			SELECT
				LINESTRING.HJID,
				LINESTRING.CURVE_HJID,
				LINESTRING.INDEX,
				ST_MAKELINE (
					POINT.GEOM
					ORDER BY
						LINESTRING.INDEX,
						GML_POINT.INDEX
				) AS GEOM
			FROM
				GML.LINESTRING
				JOIN GML.GML_POINT ON LINESTRING.HJID = GML_POINT.GML_POINT_HJID
				JOIN GML.POINT ON GML_POINT.HJID = POINT.HJID
			WHERE LINESTRING.CURVE_HJID %% %1$d = %2$d
			GROUP BY
				LINESTRING.HJID
			UNION ALL
			SELECT
				LINESTRING.HJID,
				LINESTRING.CURVE_HJID,
				LINESTRING.INDEX,
				LINESTRING.GEOM
			FROM
				GML.LINESTRING
			WHERE
				LINESTRING.POS_LIST <> ''::TEXT
				AND
				LINESTRING.CURVE_HJID %% %1$d = %2$d
			UNION ALL
			SELECT
				NORMALIZED_CIRCLE.HJID,
				NORMALIZED_CIRCLE.CURVE_HJID,
				NORMALIZED_CIRCLE.INDEX,
				ST_BOUNDARY (
					ST_BUFFER (
						NORMALIZED_CIRCLE.GEOM,
						NORMALIZED_CIRCLE.RADIUS_M::DOUBLE PRECISION,
						'quad_segs=16'::TEXT
					)::GEOMETRY
				) AS GEOM
			FROM
				NORMALIZED_CIRCLE
			WHERE NORMALIZED_CIRCLE.CURVE_HJID %% %1$d = %2$d
			UNION ALL
			SELECT
				NORMALIZED_ARC.HJID,
				NORMALIZED_ARC.CURVE_HJID,
				NORMALIZED_ARC.INDEX,
				ST_MAKELINE (
					S.PT
					ORDER BY
						S.INCREMENT
				) AS GEOM
			FROM
				NORMALIZED_ARC
				CROSS JOIN LATERAL (
					SELECT
						INCREMENT.INCREMENT,
						ST_PROJECT (
							NORMALIZED_ARC.CENTER_GEOG,
							NORMALIZED_ARC.RADIUS_M::DOUBLE PRECISION,
							NORMALIZED_ARC.START_ANGLE_RAD + NORMALIZED_ARC.STEP_SIZE_RAD * INCREMENT.INCREMENT::DOUBLE PRECISION
						)::GEOMETRY AS PT
					FROM
						GENERATE_SERIES(0, 32) INCREMENT (INCREMENT)
				) S
			WHERE NORMALIZED_ARC.CURVE_HJID %% %1$d = %2$d
			GROUP BY
				NORMALIZED_ARC.HJID,
				NORMALIZED_ARC.CURVE_HJID,
				NORMALIZED_ARC.INDEX

		)
	SELECT
		CURVE.HJID,
		CURVE.ID,
		ST_MAKELINE (
			ST_SNAPTOGRID (SEGMENT.GEOM, 0.00001::DOUBLE PRECISION)
			ORDER BY
				SEGMENT.INDEX
		) AS GEOM
	FROM
		SEGMENT
		JOIN GML.CURVE ON SEGMENT.CURVE_HJID = CURVE.HJID
	GROUP BY
		CURVE.ID,
		CURVE.HJID