-- ========================================================
-- Phase 2a : Domain registered with checks
-- ========================================================

CREATE DOMAIN public.nilreason AS TEXT CHECK (VALUE ~ '^(inapplicable|missing|template|unknown|withheld|other:.+)$');
CREATE DOMAIN public.alpha AS TEXT CHECK (VALUE ~ '^([A-Z]*)$');
CREATE DOMAIN public.alphanumeric AS TEXT CHECK (VALUE ~ '^(([A-Z]|[0-9])*)$');
CREATE DOMAIN public.character1 AS TEXT CHECK (VALUE ~ '^(([A-Z]|[0-9])+([ \+\-/]*([A-Z]|[0-9])+)*)$');
CREATE DOMAIN public.character2 AS TEXT;
CREATE DOMAIN public.character3 AS TEXT CHECK (VALUE ~ '^(([A-Z]|[0-9]|[, !"&#$%''''\(\)\*\+\-\./:;<=>\?@\[\\]\^_\|\{\}])*)$');
CREATE DOMAIN public.uomfl AS TEXT CHECK ((VALUE IN ('FL', 'SM') OR VALUE ~ '^OTHER(:(\w|_){1,58})?$'));
CREATE DOMAIN public.uomdistance AS TEXT CHECK ((VALUE IN ('NM', 'KM', 'M', 'FT', 'MI', 'CM') OR VALUE ~ '^OTHER(:(\w|_){1,58})?$'));
CREATE DOMAIN public.uomdistancevertical AS TEXT CHECK ((VALUE IN ('FT', 'M', 'FL', 'SM') OR VALUE ~ '^OTHER(:(\w|_){1,58})?$'));
CREATE DOMAIN public.uomduration AS TEXT CHECK ((VALUE IN ('HR', 'MIN', 'SEC') OR VALUE ~ '^OTHER(:(\w|_){1,58})?$'));
CREATE DOMAIN public.uomfrequency AS TEXT CHECK ((VALUE IN ('HZ', 'KHZ', 'MHZ', 'GHZ') OR VALUE ~ '^OTHER(:(\w|_){1,58})?$'));
CREATE DOMAIN public.uompressure AS TEXT CHECK ((VALUE IN ('PA', 'MPA', 'PSI', 'BAR', 'TORR', 'ATM', 'HPA') OR VALUE ~ '^OTHER(:(\w|_){1,58})?$'));
CREATE DOMAIN public.uomspeed AS TEXT CHECK ((VALUE IN ('KM_H', 'KT', 'MACH', 'M_MIN', 'FT_MIN', 'M_SEC', 'FT_SEC', 'MPH') OR VALUE ~ '^OTHER(:(\w|_){1,58})?$'));
CREATE DOMAIN public.uomtemperature AS TEXT CHECK ((VALUE IN ('C', 'F', 'K') OR VALUE ~ '^OTHER(:(\w|_){1,58})?$'));
CREATE DOMAIN public.uomweight AS TEXT CHECK ((VALUE IN ('KG', 'T', 'LB', 'TON') OR VALUE ~ '^OTHER(:(\w|_){1,58})?$'));
CREATE DOMAIN public.uomdepth AS TEXT CHECK ((VALUE IN ('MM', 'CM', 'IN', 'FT') OR VALUE ~ '^OTHER(:(\w|_){1,58})?$'));
CREATE DOMAIN public.uomlightintensity AS TEXT CHECK ((VALUE IN ('CD') OR VALUE ~ '^OTHER(:(\w|_){1,58})?$'));
CREATE DOMAIN public.codeaircraftenginenumberbase AS TEXT CHECK ((VALUE IN ('1', '2', '3', '4', '6', '8', '2C') OR VALUE ~ '^OTHER(:(\w|_){1,58})?$'));
CREATE DOMAIN public.codeairspaceactivitybase AS TEXT CHECK ((VALUE IN ('AD_TFC', 'HELI_TFC', 'TRAINING', 'AEROBATICS', 'AIRSHOW', 'SPORT', 'ULM', 'GLIDING', 'PARAGLIDER', 'HANGGLIDING', 'PARACHUTE', 'AIR_DROP', 'BALLOON', 'RADIOSONDE', 'SPACE_FLIGHT', 'UAV', 'AERIAL_WORK', 'CROP_DUSTING', 'FIRE_FIGHTING', 'MILOPS', 'REFUEL', 'JET_CLIMBING', 'EXERCISE', 'TOWING', 'NAVAL_EXER', 'MISSILES', 'AIR_GUN', 'ARTILLERY', 'SHOOTING', 'BLASTING', 'WATER_BLASTING', 'ANTI_HAIL', 'BIRD', 'BIRD_MIGRATION', 'FIREWORK', 'HI_RADIO', 'HI_LIGHT', 'LASER', 'NATURE', 'FAUNA', 'NO_NOISE', 'ACCIDENT', 'POPULATION', 'VIP', 'VIP_PRES', 'VIP_VICE', 'OIL', 'GAS', 'REFINERY', 'CHEMICAL', 'NUCLEAR', 'TECHNICAL', 'ATS', 'PROCEDURE') OR VALUE ~ '^OTHER(:(\w|_){1,58})?$'));
CREATE DOMAIN public.codeaircraftcategorybase AS TEXT CHECK ((VALUE IN ('A', 'B', 'C', 'D', 'E', 'H', 'ALL') OR VALUE ~ '^OTHER(:(\w|_){1,58})?$'));
CREATE DOMAIN public.codefirefightingbase AS TEXT CHECK ((VALUE IN ('H1', 'H2', 'H3', 'A1', 'A2', 'A3', 'A4', 'A5', 'A6', 'A7', 'A8', 'A9', 'A10') OR VALUE ~ '^OTHER(:(\w|_){1,58})?$'));
CREATE DOMAIN public.codefuelbase AS TEXT CHECK ((VALUE IN ('AVGAS', 'AVGAS_LL', 'OCT73', 'OCT80', 'OCT82UL', 'OCT80_87', 'OCT91_98', 'OCT100_130', 'OCT108_135', 'OCT115_145', 'MOGAS', 'JET', 'A', 'A1', 'A1_PLUS', 'B', 'JP1', 'JP2', 'JP3', 'JP4', 'JP5', 'JP6', 'JPTS', 'JP7', 'JP8', 'JP8_HIGHER', 'JP9', 'JP10', 'F18', 'F34', 'F35', 'F40', 'F44', 'TR0', 'TR4', 'TS1', 'RT', 'ALL') OR VALUE ~ '^OTHER(:(\w|_){1,58})?$'));
CREATE DOMAIN public.codeoilbase AS TEXT CHECK ((VALUE IN ('PISTON', 'TURBO', 'HYDRAULIC') OR VALUE ~ '^OTHER(:(\w|_){1,58})?$'));
CREATE DOMAIN public.codedmechannelbase AS TEXT CHECK ((VALUE IN ('1X', '1Y', '2X', '2Y', '3X', '3Y', '4X', '4Y', '5X', '5Y', '6X', '6Y', '7X', '7Y', '8X', '8Y', '9X', '9Y', '10X', '10Y', '11X', '11Y', '12X', '12Y', '13X', '13Y', '14X', '14Y', '15X', '15Y', '16X', '16Y', '17X', '17Y', '17Z', '18X', '18W', '18Y', '18Z', '19X', '19Y', '19Z', '20X', '20W', '20Y', '20Z', '21X', '21Y', '21Z', '22X', '22W', '22Y', '22Z', '23X', '23Y', '23Z', '24X', '24W', '24Y', '24Z', '25X', '25Y', '25Z', '26X', '26W', '26Y', '26Z', '27X', '27Y', '27Z', '28X', '28W', '28Y', '28Z', '29X', '29Y', '29Z', '30X', '30W', '30Y', '30Z', '31X', '31Y', '31Z', '32X', '32W', '32Y', '32Z', '33X', '33Y', '33Z', '34X', '34W', '34Y', '34Z', '35X', '35Y', '35Z', '36X', '36W', '36Y', '36Z', '37X', '37Y', '37Z', '38X', '38W', '38Y', '38Z', '39X', '39Y', '39Z', '40X', '40W', '40Y', '40Z', '41X', '41Y', '41Z', '42X', '42W', '42Y', '42Z', '43X', '43Y', '43Z', '44X', '44W', '44Y', '44Z', '45X', '45Y', '45Z', '46X', '46W', '46Y', '46Z', '47X', '47Y', '47Z', '48X', '48W', '48Y', '48Z', '49X', '49Y', '49Z', '50X', '50W', '50Y', '50Z', '51X', '51Y', '51Z', '52X', '52W', '52Y', '52Z', '53X', '53Y', '53Z', '54X', '54W', '54Y', '54Z', '55X', '55Y', '55Z', '56X', '56W', '56Y', '56Z', '57X', '57Y', '58X', '58Y', '59X', '59Y', '60X', '60Y', '61X', '61Y', '62X', '62Y', '63X', '63Y', '64X', '64Y', '65X', '65Y', '66X', '66Y', '67X', '67Y', '68X', '68Y', '69X', '69Y', '70X', '70Y', '71X', '71Y', '72X', '72Y', '73X', '73Y', '74X', '74Y', '75X', '75Y', '76X', '76Y', '77X', '77Y', '78X', '78Y', '79X', '79Y', '80X', '80Y', '80Z', '81X', '81Y', '81Z', '82X', '82Y', '82Z', '83X', '83Y', '83Z', '84X', '84Y', '84Z', '85X', '85Y', '85Z', '86X', '86Y', '86Z', '87X', '87Y', '87Z', '88X', '88Y', '88Z', '89X', '89Y', '89Z', '90X', '90Y', '90Z', '91X', '91Y', '91Z', '92X', '92Y', '92Z', '93X', '93Y', '93Z', '94X', '94Y', '94Z', '95X', '95Y', '95Z', '96X', '96Y', '96Z', '97X', '97Y', '97Z', '98X', '98Y', '98Z', '99X', '99Y', '99Z', '100X', '100Y', '100Z', '101X', '101Y', '101Z', '102X', '102Y', '102Z', '103X', '103Y', '103Z', '104X', '104Y', '104Z', '105X', '105Y', '105Z', '106X', '106Y', '106Z', '107X', '107Y', '107Z', '108X', '108Y', '108Z', '109X', '109Y', '109Z', '110X', '110Y', '110Z', '111X', '111Y', '111Z', '112X', '112Y', '112Z', '113X', '113Y', '113Z', '114X', '114Y', '114Z', '115X', '115Y', '115Z', '116X', '116Y', '116Z', '117X', '117Y', '117Z', '118X', '118Y', '118Z', '119X', '119Y', '119Z', '120X', '120Y', '121X', '121Y', '122X', '122Y', '123X', '123Y', '124X', '124Y', '125X', '125Y', '126X', '126Y') OR VALUE ~ '^OTHER(:(\w|_){1,58})?$'));
CREATE DOMAIN public.codemlschannelbase AS TEXT CHECK ((VALUE IN ('500', '501', '502', '503', '504', '505', '506', '507', '508', '509', '510', '511', '512', '513', '514', '515', '516', '517', '518', '519', '520', '521', '522', '523', '524', '525', '526', '527', '528', '529', '530', '531', '532', '533', '534', '535', '536', '537', '538', '539', '540', '541', '542', '543', '544', '545', '546', '547', '548', '549', '550', '551', '552', '553', '554', '555', '556', '557', '558', '559', '560', '561', '562', '563', '564', '565', '566', '567', '568', '569', '570', '571', '572', '573', '574', '575', '576', '577', '578', '579', '580', '581', '582', '583', '584', '585', '586', '587', '588', '589', '590', '591', '592', '593', '594', '595', '596', '597', '598', '599', '600', '601', '602', '603', '604', '605', '606', '607', '608', '609', '610', '611', '612', '613', '614', '615', '616', '617', '618', '619', '620', '621', '622', '623', '624', '625', '626', '627', '628', '629', '630', '631', '632', '633', '634', '635', '636', '637', '638', '639', '640', '641', '642', '643', '644', '645', '646', '647', '648', '649', '650', '651', '652', '653', '654', '655', '656', '657', '658', '659', '660', '661', '662', '663', '664', '665', '666', '667', '668', '669', '670', '671', '672', '673', '674', '675', '676', '677', '678', '679', '680', '681', '682', '683', '684', '685', '686', '687', '688', '689', '690', '691', '692', '693', '694', '695', '696', '697', '698', '699') OR VALUE ~ '^OTHER(:(\w|_){1,58})?$'));
CREATE DOMAIN public.codetacanchannelbase AS TEXT CHECK ((VALUE IN ('1X', '1Y', '2X', '2Y', '3X', '3Y', '4X', '4Y', '5X', '5Y', '6X', '6Y', '7X', '7Y', '8X', '8Y', '9X', '9Y', '10X', '10Y', '11X', '11Y', '12X', '12Y', '13X', '13Y', '14X', '14Y', '15X', '15Y', '16X', '16Y', '17X', '17Y', '17Z', '18X', '18W', '18Y', '18Z', '19X', '19Y', '19Z', '20X', '20W', '20Y', '20Z', '21X', '21Y', '21Z', '22X', '22W', '22Y', '22Z', '23X', '23Y', '23Z', '24X', '24W', '24Y', '24Z', '25X', '25Y', '25Z', '26X', '26W', '26Y', '26Z', '27X', '27Y', '27Z', '28X', '28W', '28Y', '28Z', '29X', '29Y', '29Z', '30X', '30W', '30Y', '30Z', '31X', '31Y', '31Z', '32X', '32W', '32Y', '32Z', '33X', '33Y', '33Z', '34X', '34W', '34Y', '34Z', '35X', '35Y', '35Z', '36X', '36W', '36Y', '36Z', '37X', '37Y', '37Z', '38X', '38W', '38Y', '38Z', '39X', '39Y', '39Z', '40X', '40W', '40Y', '40Z', '41X', '41Y', '41Z', '42X', '42W', '42Y', '42Z', '43X', '43Y', '43Z', '44X', '44W', '44Y', '44Z', '45X', '45Y', '45Z', '46X', '46W', '46Y', '46Z', '47X', '47Y', '47Z', '48X', '48W', '48Y', '48Z', '49X', '49Y', '49Z', '50X', '50W', '50Y', '50Z', '51X', '51Y', '51Z', '52X', '52W', '52Y', '52Z', '53X', '53Y', '53Z', '54X', '54W', '54Y', '54Z', '55X', '55Y', '55Z', '56X', '56W', '56Y', '56Z', '57X', '57Y', '58X', '58Y', '59X', '59Y', '60X', '60Y', '61X', '61Y', '62X', '62Y', '63X', '63Y', '64X', '64Y', '65X', '65Y', '66X', '66Y', '67X', '67Y', '68X', '68Y', '69X', '69Y', '70X', '70Y', '71X', '71Y', '72X', '72Y', '73X', '73Y', '74X', '74Y', '75X', '75Y', '76X', '76Y', '77X', '77Y', '78X', '78Y', '79X', '79Y', '80X', '80Y', '80Z', '81X', '81Y', '81Z', '82X', '82Y', '82Z', '83X', '83Y', '83Z', '84X', '84Y', '84Z', '85X', '85Y', '85Z', '86X', '86Y', '86Z', '87X', '87Y', '87Z', '88X', '88Y', '88Z', '89X', '89Y', '89Z', '90X', '90Y', '90Z', '91X', '91Y', '91Z', '92X', '92Y', '92Z', '93X', '93Y', '93Z', '94X', '94Y', '94Z', '95X', '95Y', '95Z', '96X', '96Y', '96Z', '97X', '97Y', '97Z', '98X', '98Y', '98Z', '99X', '99Y', '99Z', '100X', '100Y', '100Z', '101X', '101Y', '101Z', '102X', '102Y', '102Z', '103X', '103Y', '103Z', '104X', '104Y', '104Z', '105X', '105Y', '105Z', '106X', '106Y', '106Z', '107X', '107Y', '107Z', '108X', '108Y', '108Z', '109X', '109Y', '109Z', '110X', '110Y', '110Z', '111X', '111Y', '111Z', '112X', '112Y', '112Z', '113X', '113Y', '113Z', '114X', '114Y', '114Z', '115X', '115Y', '115Z', '116X', '116Y', '116Z', '117X', '117Y', '117Z', '118X', '118Y', '118Z', '119X', '119Y', '119Z', '120X', '120Y', '121X', '121Y', '122X', '122Y', '123X', '123Y', '124X', '124Y', '125X', '125Y', '126X', '126Y') OR VALUE ~ '^OTHER(:(\w|_){1,58})?$'));
CREATE DOMAIN public.codehelicopterperformancebase AS TEXT CHECK ((VALUE IN ('1', '2', '3') OR VALUE ~ '^OTHER(:(\w|_){1,58})?$'));
CREATE DOMAIN public.codemarkerbeaconsignalbase AS TEXT CHECK ((VALUE IN ('FAN', 'LOW_PWR_FAN', 'Z', 'BONES') OR VALUE ~ '^OTHER(:(\w|_){1,58})?$'));
CREATE DOMAIN public.codendbusagebase AS TEXT CHECK ((VALUE IN ('ENR', 'L', 'MAR') OR VALUE ~ '^OTHER(:(\w|_){1,58})?$'));
CREATE DOMAIN public.codecolourbase AS TEXT CHECK ((VALUE IN ('YELLOW', 'RED', 'WHITE', 'BLUE', 'GREEN', 'PURPLE', 'ORANGE', 'AMBER', 'BLACK', 'BROWN', 'GREY', 'LIGHT_GREY', 'MAGENTA', 'PINK', 'VIOLET') OR VALUE ~ '^OTHER(:(\w|_){1,58})?$'));
CREATE DOMAIN public.codetimeeventcombinationbase AS TEXT CHECK ((VALUE IN ('EARLIEST', 'LATEST') OR VALUE ~ '^OTHER(:(\w|_){1,58})?$'));
CREATE DOMAIN public.codecomparisonbase AS TEXT CHECK ((VALUE IN ('LESS', 'LESS_OR_EQUAL', 'EQUAL', 'GREATER_OR_EQUAL', 'GREATER') OR VALUE ~ '^OTHER(:(\w|_){1,58})?$'));
CREATE DOMAIN public.codesurfacecompositionbase AS TEXT CHECK ((VALUE IN ('ASPH', 'ASPH_GRASS', 'CONC', 'CONC_ASPH', 'CONC_GRS', 'GRASS', 'SAND', 'WATER', 'BITUM', 'BRICK', 'MACADAM', 'STONE', 'CORAL', 'CLAY', 'LATERITE', 'GRAVEL', 'EARTH', 'ICE', 'SNOW', 'MEMBRANE', 'METAL', 'MATS', 'PIERCED_STEEL', 'WOOD', 'NON_BITUM_MIX') OR VALUE ~ '^OTHER(:(\w|_){1,58})?$'));
CREATE DOMAIN public.codesurfaceconditionbase AS TEXT CHECK ((VALUE IN ('GOOD', 'FAIR', 'POOR', 'UNSAFE', 'DEFORMED') OR VALUE ~ '^OTHER(:(\w|_){1,58})?$'));
CREATE DOMAIN public.codedaybase AS TEXT CHECK ((VALUE IN ('MON', 'TUE', 'WED', 'THU', 'FRI', 'SAT', 'SUN', 'WORK_DAY', 'BEF_WORK_DAY', 'AFT_WORK_DAY', 'HOL', 'BEF_HOL', 'AFT_HOL', 'ANY', 'BUSY_FRI') OR VALUE ~ '^OTHER(:(\w|_){1,58})?$'));
CREATE DOMAIN public.codealtitudeusebase AS TEXT CHECK ((VALUE IN ('ABOVE_LOWER', 'BELOW_UPPER', 'AT_LOWER', 'BETWEEN', 'RECOMMENDED', 'EXPECT_LOWER', 'AS_ASSIGNED') OR VALUE ~ '^OTHER(:(\w|_){1,58})?$'));
CREATE DOMAIN public.codedirectionbase AS TEXT CHECK ((VALUE IN ('FORWARD', 'BACKWARD', 'BOTH') OR VALUE ~ '^OTHER(:(\w|_){1,58})?$'));
CREATE DOMAIN public.codedirectionreferencebase AS TEXT CHECK ((VALUE IN ('TO', 'FROM') OR VALUE ~ '^OTHER(:(\w|_){1,58})?$'));
CREATE DOMAIN public.codedirectionturnbase AS TEXT CHECK ((VALUE IN ('LEFT', 'RIGHT', 'EITHER') OR VALUE ~ '^OTHER(:(\w|_){1,58})?$'));
CREATE DOMAIN public.codeverticalreferencebase AS TEXT CHECK ((VALUE IN ('SFC', 'MSL', 'W84', 'STD') OR VALUE ~ '^OTHER(:(\w|_){1,58})?$'));
CREATE DOMAIN public.coderadioemissionbase AS TEXT CHECK ((VALUE IN ('A2', 'A3A', 'A3B', 'A3E', 'A3H', 'A3J', 'A3L', 'A3U', 'J3E', 'NONA1A', 'NONA2A', 'PON', 'A8W', 'A9W', 'NOX', 'G1D') OR VALUE ~ '^OTHER(:(\w|_){1,58})?$'));
CREATE DOMAIN public.codeflowconditionoperationbase AS TEXT CHECK ((VALUE IN ('AND', 'ANDNOT', 'OR', 'SEQ', 'NONE') OR VALUE ~ '^OTHER(:(\w|_){1,58})?$'));
CREATE DOMAIN public.codeflightstatusbase AS TEXT CHECK ((VALUE IN ('HEAD', 'STATE', 'HUM', 'HOSP', 'SAR', 'ALL', 'EMERGENCY') OR VALUE ~ '^OTHER(:(\w|_){1,58})?$'));
CREATE DOMAIN public.codeflightbase AS TEXT CHECK ((VALUE IN ('OAT', 'GAT', 'ALL') OR VALUE ~ '^OTHER(:(\w|_){1,58})?$'));
CREATE DOMAIN public.codeprocedurefixrolebase AS TEXT CHECK ((VALUE IN ('IAF', 'IF', 'IF_IAF', 'FAF', 'VDP', 'SDF', 'FPAP', 'FTP', 'FROP', 'TP', 'MAPT', 'MAHF') OR VALUE ~ '^OTHER(:(\w|_){1,58})?$'));
CREATE DOMAIN public.codeaircrafticaobase AS VARCHAR(4) CHECK (LENGTH(VALUE) >= 1 AND VALUE ~ '^(([A-Z]|[0-9])*)$');
CREATE DOMAIN public.codeairportheliportdesignatorbase AS VARCHAR(6) CHECK (LENGTH(VALUE) >= 3 AND VALUE ~ '^(([A-Z]|[0-9])*)$');
CREATE DOMAIN public.codeairspacedesignatorbase AS VARCHAR(10) CHECK (LENGTH(VALUE) >= 1 AND VALUE ~ '^(([A-Z]|[0-9]|[, !"&#$%''''\(\)\*\+\-\./:;<=>\?@\[\\]\^_\|\{\}])*)$');
CREATE DOMAIN public.codespecialnavigationchaindesignatorbase AS VARCHAR(4) CHECK (LENGTH(VALUE) >= 1 AND VALUE ~ '^(([A-Z]|[0-9])*)$');
CREATE DOMAIN public.codedesignatedpointdesignatorbase AS VARCHAR(5) CHECK (LENGTH(VALUE) >= 1 AND VALUE ~ '^(([A-Z]|[0-9])*)$');
CREATE DOMAIN public.codeleveltabledesignatorbase AS TEXT CHECK ((VALUE IN ('IFR', 'IFR_METRES', 'VFR', 'VFR_METRES', 'IFR_RVSM', 'IFR_METRES_RVSM', 'VFR_RVMS', 'VFR_METRES_RVSM') OR VALUE ~ '^OTHER(:(\w|_){1,58})?$'));
CREATE DOMAIN public.codenavaiddesignatorbase AS VARCHAR(4) CHECK (LENGTH(VALUE) >= 1 AND VALUE ~ '^(([A-Z]|[0-9])*)$');
CREATE DOMAIN public.codeorganisationdesignatorbase AS VARCHAR(12) CHECK (LENGTH(VALUE) >= 1 AND VALUE ~ '^(([A-Z]|[0-9])+([ \+\-/]*([A-Z]|[0-9])+)*)$');
CREATE DOMAIN public.codeflightrestrictiondesignatorbase AS VARCHAR(16) CHECK (LENGTH(VALUE) >= 1 AND VALUE ~ '^(([A-Z]|[0-9])+([ \+\-/]*([A-Z]|[0-9])+)*)$');
CREATE DOMAIN public.coderouteoriginbase AS TEXT CHECK ((VALUE IN ('INTL', 'DOM', 'BOTH') OR VALUE ~ '^OTHER(:(\w|_){1,58})?$'));
CREATE DOMAIN public.codelightintensitybase AS TEXT CHECK ((VALUE IN ('LIL', 'LIM', 'LIH', 'LIL_LIH', 'PREDETERMINED') OR VALUE ~ '^OTHER(:(\w|_){1,58})?$'));
CREATE DOMAIN public.codelanguagebase AS TEXT CHECK (VALUE ~ '^([a-z]{3})$');
CREATE DOMAIN public.codeiatabase AS VARCHAR(3) CHECK (LENGTH(VALUE) >= 3 AND VALUE ~ '^([A-Z]*)$');
CREATE DOMAIN public.codeicaobase AS VARCHAR(4) CHECK (LENGTH(VALUE) >= 4 AND VALUE ~ '^([A-Z]*)$');
CREATE DOMAIN public.codeaviationstandardsbase AS TEXT CHECK ((VALUE IN ('ICAO', 'IATA', 'NATO', 'FAA') OR VALUE ~ '^OTHER(:(\w|_){1,58})?$'));
CREATE DOMAIN public.codelevelbase AS TEXT CHECK ((VALUE IN ('UPPER', 'LOWER', 'BOTH') OR VALUE ~ '^OTHER(:(\w|_){1,58})?$'));
CREATE DOMAIN public.codemilitarystatusbase AS TEXT CHECK ((VALUE IN ('MIL', 'CIVIL', 'ALL') OR VALUE ~ '^OTHER(:(\w|_){1,58})?$'));
CREATE DOMAIN public.codeairspaceaggregationbase AS TEXT CHECK ((VALUE IN ('BASE', 'UNION', 'INTERS', 'SUBTR') OR VALUE ~ '^OTHER(:(\w|_){1,58})?$'));
CREATE DOMAIN public.codeflightoriginbase AS TEXT CHECK ((VALUE IN ('NTL', 'INTL', 'ALL', 'HOME_BASED') OR VALUE ~ '^OTHER(:(\w|_){1,58})?$'));
CREATE DOMAIN public.codepcnmethodbase AS TEXT CHECK ((VALUE IN ('TECH', 'ACFT') OR VALUE ~ '^OTHER(:(\w|_){1,58})?$'));
CREATE DOMAIN public.codepcntyrepressurebase AS TEXT CHECK ((VALUE IN ('W', 'X', 'Y', 'Z') OR VALUE ~ '^OTHER(:(\w|_){1,58})?$'));
CREATE DOMAIN public.codepcnsubgradebase AS TEXT CHECK ((VALUE IN ('A', 'B', 'C', 'D') OR VALUE ~ '^OTHER(:(\w|_){1,58})?$'));
CREATE DOMAIN public.codepcnpavementbase AS TEXT CHECK ((VALUE IN ('RIGID', 'FLEXIBLE') OR VALUE ~ '^OTHER(:(\w|_){1,58})?$'));
CREATE DOMAIN public.codeprocedurephasebase AS TEXT CHECK ((VALUE IN ('RWY', 'COMMON', 'EN_ROUTE', 'APPROACH', 'FINAL', 'MISSED', 'MISSED_P', 'MISSED_S', 'ENGINE_OUT') OR VALUE ~ '^OTHER(:(\w|_){1,58})?$'));
CREATE DOMAIN public.codesurfacepreparationbase AS TEXT CHECK ((VALUE IN ('NATURAL', 'ROLLED', 'COMPACTED', 'GRADED', 'GROOVED', 'OILED', 'PAVED', 'PFC', 'AFSC', 'RFSC', 'NON_GROOVED') OR VALUE ~ '^OTHER(:(\w|_){1,58})?$'));
CREATE DOMAIN public.codeapronsectionbase AS TEXT CHECK ((VALUE IN ('EDGE') OR VALUE ~ '^OTHER(:(\w|_){1,58})?$'));
CREATE DOMAIN public.codepositioninilsbase AS TEXT CHECK ((VALUE IN ('OUTER', 'MIDDLE', 'INNER', 'BACKCOURSE') OR VALUE ~ '^OTHER(:(\w|_){1,58})?$'));
CREATE DOMAIN public.codesidebase AS TEXT CHECK ((VALUE IN ('LEFT', 'RIGHT', 'BOTH') OR VALUE ~ '^OTHER(:(\w|_){1,58})?$'));
CREATE DOMAIN public.coderunwaysectionbase AS TEXT CHECK ((VALUE IN ('TDZ', 'AIM', 'CL', 'EDGE', 'THR', 'DESIG', 'AFT_THR', 'DTHR', 'END', 'TWY_INT', 'RPD_TWY_INT', '1_THIRD', '2_THIRD', '3_THIRD') OR VALUE ~ '^OTHER(:(\w|_){1,58})?$'));
CREATE DOMAIN public.codetlofsectionbase AS TEXT CHECK ((VALUE IN ('AIM', 'EDGE') OR VALUE ~ '^OTHER(:(\w|_){1,58})?$'));
CREATE DOMAIN public.codetaxiwaysectionbase AS TEXT CHECK ((VALUE IN ('CL', 'EDGE', 'END', 'RWY_INT', 'TWY_INT') OR VALUE ~ '^OTHER(:(\w|_){1,58})?$'));
CREATE DOMAIN public.codeflightpurposebase AS TEXT CHECK ((VALUE IN ('SCHEDULED', 'NON_SCHEDULED', 'PRIVATE', 'AIR_TRAINING', 'AIR_WORK', 'ALL', 'PARTICIPANT') OR VALUE ~ '^OTHER(:(\w|_){1,58})?$'));
CREATE DOMAIN public.codelocationqualifierbase AS TEXT CHECK ((VALUE IN ('DEP', 'XNG', 'ARR', 'ACT', 'AVBL') OR VALUE ~ '^OTHER(:(\w|_){1,58})?$'));
CREATE DOMAIN public.codeatcreportingbase AS TEXT CHECK ((VALUE IN ('COMPULSORY', 'ON_REQUEST', 'NO_REPORT') OR VALUE ~ '^OTHER(:(\w|_){1,58})?$'));
CREATE DOMAIN public.codernpbase AS NUMERIC CHECK (VALUE::text ~ '^([0-9]{1,2}(\.[0-9]{1}){0,1})$');
CREATE DOMAIN public.coderouteavailabilitybase AS TEXT CHECK ((VALUE IN ('OPEN', 'COND', 'CLSD') OR VALUE ~ '^OTHER(:(\w|_){1,58})?$'));
CREATE DOMAIN public.codervsmpointrolebase AS TEXT CHECK ((VALUE IN ('IN', 'OUT', 'IN_OUT') OR VALUE ~ '^OTHER(:(\w|_){1,58})?$'));
CREATE DOMAIN public.codespecialdatebase AS TEXT CHECK ((VALUE IN ('HOL', 'BUSY_FRI') OR VALUE ~ '^OTHER(:(\w|_){1,58})?$'));
CREATE DOMAIN public.codespeedreferencebase AS TEXT CHECK ((VALUE IN ('IAS', 'TAS', 'GS') OR VALUE ~ '^OTHER(:(\w|_){1,58})?$'));
CREATE DOMAIN public.codetimeeventbase AS TEXT CHECK ((VALUE IN ('SR', 'SS') OR VALUE ~ '^OTHER(:(\w|_){1,58})?$'));
CREATE DOMAIN public.codetimereferencebase AS TEXT CHECK ((VALUE IN ('UTC', 'UTC-12', 'UTC-11', 'UTC-10', 'UTC-9', 'UTC-8', 'UTC-7', 'UTC-6', 'UTC-5', 'UTC-4', 'UTC-3', 'UTC-2', 'UTC-1', 'UTC+1', 'UTC+2', 'UTC+3', 'UTC+4', 'UTC+5', 'UTC+6', 'UTC+7', 'UTC+8', 'UTC+9', 'UTC+10', 'UTC+11', 'UTC+12', 'UTC+13', 'UTC+14') OR VALUE ~ '^OTHER(:(\w|_){1,58})?$'));
CREATE DOMAIN public.codeaircraftbase AS TEXT CHECK ((VALUE IN ('LANDPLANE', 'SEAPLANE', 'AMPHIBIAN', 'HELICOPTER', 'GYROCOPTER', 'TILT_WING', 'STOL', 'GLIDER', 'HANGGLIDER', 'PARAGLIDER', 'ULTRA_LIGHT', 'BALLOON', 'UAV', 'ALL') OR VALUE ~ '^OTHER(:(\w|_){1,58})?$'));
CREATE DOMAIN public.codeaircraftenginebase AS TEXT CHECK ((VALUE IN ('JET', 'PISTON', 'TURBOPROP', 'ALL') OR VALUE ~ '^OTHER(:(\w|_){1,58})?$'));
CREATE DOMAIN public.codeairportheliportbase AS TEXT CHECK ((VALUE IN ('AD', 'AH', 'HP', 'LS') OR VALUE ~ '^OTHER(:(\w|_){1,58})?$'));
CREATE DOMAIN public.codeairportheliportcollocationbase AS TEXT CHECK ((VALUE IN ('FULL', 'RWY', 'PARTIAL', 'UNILATERAL', 'SEPARATED') OR VALUE ~ '^OTHER(:(\w|_){1,58})?$'));
CREATE DOMAIN public.codegroundlightingbase AS TEXT CHECK ((VALUE IN ('BCN', 'IBN', 'HEL_BCN', 'ABN', 'MAR_BCN', 'RSP_BCN', 'TWR_BCN', 'HAZ_BCN') OR VALUE ~ '^OTHER(:(\w|_){1,58})?$'));
CREATE DOMAIN public.codeapproachlightingbase AS TEXT CHECK ((VALUE IN ('ALSAF', 'MALS', 'MALSR', 'SALS', 'SSALS', 'SSALR', 'LDIN', 'ODALS', 'AFOVRN', 'MILOVRN', 'CALVERT') OR VALUE ~ '^OTHER(:(\w|_){1,58})?$'));
CREATE DOMAIN public.codebearingbase AS TEXT CHECK ((VALUE IN ('TRUE', 'MAG', 'RDL', 'TRK', 'HDG') OR VALUE ~ '^OTHER(:(\w|_){1,58})?$'));
CREATE DOMAIN public.codeairspacebase AS TEXT CHECK ((VALUE IN ('NAS', 'FIR', 'FIR_P', 'UIR', 'UIR_P', 'CTA', 'CTA_P', 'OCA_P', 'OCA', 'UTA', 'UTA_P', 'TMA', 'TMA_P', 'CTR', 'CTR_P', 'OTA', 'SECTOR', 'SECTOR_C', 'TSA', 'CBA', 'RCA', 'RAS', 'AWY', 'MTR', 'P', 'R', 'D', 'ADIZ', 'NO_FIR', 'PART', 'CLASS', 'POLITICAL', 'D_OTHER', 'TRA', 'A', 'W', 'PROTECT', 'AMA', 'ASR', 'ADV', 'UADV', 'ATZ', 'ATZ_P', 'HTZ', 'NAS_P') OR VALUE ~ '^OTHER(:(\w|_){1,58})?$'));
CREATE DOMAIN public.codeauthoritybase AS TEXT CHECK ((VALUE IN ('OWN', 'DLGT', 'AIS') OR VALUE ~ '^OTHER(:(\w|_){1,58})?$'));
CREATE DOMAIN public.codeairspacepointrolebase AS TEXT CHECK ((VALUE IN ('ENTRY', 'EXIT', 'ENTRY_EXIT') OR VALUE ~ '^OTHER(:(\w|_){1,58})?$'));
CREATE DOMAIN public.codeorganisationhierarchybase AS TEXT CHECK ((VALUE IN ('MEMBER', 'OWNED_BY', 'SUPERVISED_BY') OR VALUE ~ '^OTHER(:(\w|_){1,58})?$'));
CREATE DOMAIN public.codemlsazimuthbase AS TEXT CHECK ((VALUE IN ('FWD', 'BWD') OR VALUE ~ '^OTHER(:(\w|_){1,58})?$'));
CREATE DOMAIN public.codecoursebase AS TEXT CHECK ((VALUE IN ('TRUE_TRACK', 'MAG_TRACK', 'TRUE_BRG', 'MAG_BRG', 'HDG', 'RDL') OR VALUE ~ '^OTHER(:(\w|_){1,58})?$'));
CREATE DOMAIN public.codedeclareddistancebase AS TEXT CHECK ((VALUE IN ('LDA', 'TORA', 'TODA', 'ASDA', 'DTHR', 'TODAH', 'RTODAH', 'LDAH') OR VALUE ~ '^OTHER(:(\w|_){1,58})?$'));
CREATE DOMAIN public.codedesignatedpointbase AS TEXT CHECK ((VALUE IN ('ICAO', 'COORD', 'CNF', 'DESIGNED', 'MTR', 'TERMINAL', 'BRG_DIST') OR VALUE ~ '^OTHER(:(\w|_){1,58})?$'));
CREATE DOMAIN public.codedmebase AS TEXT CHECK ((VALUE IN ('NARROW', 'PRECISION', 'WIDE') OR VALUE ~ '^OTHER(:(\w|_){1,58})?$'));
CREATE DOMAIN public.codeflightrulebase AS TEXT CHECK ((VALUE IN ('IFR', 'VFR', 'ALL') OR VALUE ~ '^OTHER(:(\w|_){1,58})?$'));
CREATE DOMAIN public.codegeoborderbase AS TEXT CHECK ((VALUE IN ('STATE', 'WATER', 'COAST', 'RIVER', 'BANK') OR VALUE ~ '^OTHER(:(\w|_){1,58})?$'));
CREATE DOMAIN public.codeholdingusagebase AS TEXT CHECK ((VALUE IN ('ENR', 'TER') OR VALUE ~ '^OTHER(:(\w|_){1,58})?$'));
CREATE DOMAIN public.codelightsourcebase AS TEXT CHECK ((VALUE IN ('FLOOD', 'STROBE') OR VALUE ~ '^OTHER(:(\w|_){1,58})?$'));
CREATE DOMAIN public.codemilitaryoperationsbase AS TEXT CHECK ((VALUE IN ('CIVIL', 'MIL', 'JOINT') OR VALUE ~ '^OTHER(:(\w|_){1,58})?$'));
CREATE DOMAIN public.coderadiofrequencyareabase AS TEXT CHECK ((VALUE IN ('COV', 'T_COV', 'SCL', 'RHG', 'UNREL', 'RES', 'UUS', 'OUT', 'ESV') OR VALUE ~ '^OTHER(:(\w|_){1,58})?$'));
CREATE DOMAIN public.codenitrogenbase AS TEXT CHECK ((VALUE IN ('LPNG', 'HPNG', 'LHNG', 'LNG', 'NGRB', 'HNGRB', 'LNGRB', 'NG') OR VALUE ~ '^OTHER(:(\w|_){1,58})?$'));
CREATE DOMAIN public.codenorthreferencebase AS TEXT CHECK ((VALUE IN ('TRUE', 'MAG', 'GRID') OR VALUE ~ '^OTHER(:(\w|_){1,58})?$'));
CREATE DOMAIN public.codeorganisationbase AS TEXT CHECK ((VALUE IN ('STATE', 'STATE_GROUP', 'ORG', 'INTL_ORG', 'ACFT_OPR', 'HANDLING_AGENCY', 'NTL_AUTH', 'ATS', 'COMMERCIAL') OR VALUE ~ '^OTHER(:(\w|_){1,58})?$'));
CREATE DOMAIN public.codeoxygenbase AS TEXT CHECK ((VALUE IN ('LPOX', 'HPOX', 'LHOX', 'LOX', 'OXRB', 'HOXRB', 'LOXRB', 'OX') OR VALUE ~ '^OTHER(:(\w|_){1,58})?$'));
CREATE DOMAIN public.codesegmentpathbase AS TEXT CHECK ((VALUE IN ('AF', 'HF', 'HA', 'HM', 'IF', 'PI', 'PT', 'TF', 'CA', 'CD', 'CI', 'CR', 'CF', 'DF', 'FA', 'FC', 'FT', 'FM', 'VM', 'FD', 'VR', 'VD', 'VI', 'VA', 'RF') OR VALUE ~ '^OTHER(:(\w|_){1,58})?$'));
CREATE DOMAIN public.coderunwayprotectionareabase AS TEXT CHECK ((VALUE IN ('CWY', 'RESA', 'OFZ', 'IOFZ', 'POFZ', 'ILS', 'VGSI', 'STOPWAY') OR VALUE ~ '^OTHER(:(\w|_){1,58})?$'));
CREATE DOMAIN public.codeflightrestrictionbase AS TEXT CHECK ((VALUE IN ('FORBID', 'MANDATORY', 'CLSD', 'ALLOWED') OR VALUE ~ '^OTHER(:(\w|_){1,58})?$'));
CREATE DOMAIN public.coderoutenavigationbase AS TEXT CHECK ((VALUE IN ('CONV', 'RNAV', 'TACAN') OR VALUE ~ '^OTHER(:(\w|_){1,58})?$'));
CREATE DOMAIN public.coderoutesegmentpathbase AS TEXT CHECK ((VALUE IN ('GRC', 'RHL', 'GDS') OR VALUE ~ '^OTHER(:(\w|_){1,58})?$'));
CREATE DOMAIN public.codeaircraftgroundservicebase AS TEXT CHECK ((VALUE IN ('DEICE', 'HAND', 'HANGAR', 'REPAIR', 'REMOVE') OR VALUE ~ '^OTHER(:(\w|_){1,58})?$'));
CREATE DOMAIN public.codespecialnavigationstationbase AS TEXT CHECK ((VALUE IN ('MASTER', 'SLAVE', 'RED_SLAVE', 'GREEN_SLAVE', 'PURPLE_SLAVE') OR VALUE ~ '^OTHER(:(\w|_){1,58})?$'));
CREATE DOMAIN public.codespecialnavigationsystembase AS TEXT CHECK ((VALUE IN ('LORANA', 'LORANC', 'LORAND', 'DECCA', 'GNSS') OR VALUE ~ '^OTHER(:(\w|_){1,58})?$'));
CREATE DOMAIN public.codeaircraftstandbase AS TEXT CHECK ((VALUE IN ('NI', 'ANG_NI', 'ANG_NO', 'PARL', 'RMT', 'ISOL') OR VALUE ~ '^OTHER(:(\w|_){1,58})?$'));
CREATE DOMAIN public.codetaxiwaybase AS TEXT CHECK ((VALUE IN ('AIR', 'GND', 'EXIT', 'FASTEXIT', 'STUB', 'TURN_AROUND', 'PARALLEL', 'BYPASS') OR VALUE ~ '^OTHER(:(\w|_){1,58})?$'));
CREATE DOMAIN public.codeunitbase AS TEXT CHECK ((VALUE IN ('ACC', 'ADSU', 'ADVC', 'ALPS', 'AOF', 'APP', 'APP_ARR', 'APP_DEP', 'ARO', 'ATCC', 'ATFMU', 'ATMU', 'ATSU', 'BOF', 'BS', 'COM', 'FCST', 'FIC', 'GCA', 'MET', 'MWO', 'NOF', 'OAC', 'PAR', 'RAD', 'RAFC', 'RCC', 'RSC', 'SAR', 'SMC', 'SMR', 'SRA', 'SSR', 'TAR', 'TWR', 'UAC', 'UDF', 'UIC', 'VDF', 'WAFC', 'ARTCC', 'FSS', 'TRACON', 'MIL', 'MILOPS') OR VALUE ~ '^OTHER(:(\w|_){1,58})?$'));
CREATE DOMAIN public.codeilsbackcoursebase AS TEXT CHECK ((VALUE IN ('YES', 'NO', 'RSTR') OR VALUE ~ '^OTHER(:(\w|_){1,58})?$'));
CREATE DOMAIN public.codevasisbase AS TEXT CHECK ((VALUE IN ('PAPI', 'APAPI', 'HAPI', 'VASIS', 'AVASIS', 'TVASIS', 'ATVASIS', '3B_VASIS', '3B_AVASIS', '3B_ATVASIS', 'PVASI', 'TRCV', 'PNI', 'ILU', 'OLS', 'LCVASI') OR VALUE ~ '^OTHER(:(\w|_){1,58})?$'));
CREATE DOMAIN public.codeusagelimitationbase AS TEXT CHECK ((VALUE IN ('PERMIT', 'CONDITIONAL', 'FORBID', 'RESERV') OR VALUE ~ '^OTHER(:(\w|_){1,58})?$'));
CREATE DOMAIN public.codeyesnobase AS TEXT CHECK ((VALUE IN ('YES', 'NO') OR VALUE ~ '^OTHER(:(\w|_){1,58})?$'));
CREATE DOMAIN public.datemonthdaybase AS TEXT CHECK (VALUE ~ '^((((0[1-9])|(1[0-9])|(2[0-9]))\-((0[1-9])|10|11|12))|(30\-(01|03|04|05|06|07|08|09|10|11|12))|(31\-(01|03|05|07|08|10|12))|SDLST|EDLST)$');
CREATE DOMAIN public.dateyearbase AS TEXT CHECK (VALUE ~ '^([1-9][0-9][0-9][0-9])$');
CREATE DOMAIN public.nonumberbase AS BIGINT CHECK (VALUE >= 0);
CREATE DOMAIN public.nosequencebase AS BIGINT CHECK (VALUE >= 0);
CREATE DOMAIN public.timebase AS TEXT CHECK (VALUE ~ '^((([0-1][0-9]|2[0-3]):[0-5][0-9])|(24:00))$');
CREATE DOMAIN public.textaddressbase AS VARCHAR(500) CHECK (LENGTH(VALUE) >= 1);
CREATE DOMAIN public.textinstructionbase AS VARCHAR(10000) CHECK (LENGTH(VALUE) >= 1);
CREATE DOMAIN public.textdesignatorbase AS VARCHAR(16) CHECK (LENGTH(VALUE) >= 1 AND VALUE ~ '^(([A-Z]|[0-9]|[, !"&#$%''''\(\)\*\+\-\./:;<=>\?@\[\\]\^_\|\{\}])*)$');
CREATE DOMAIN public.textsidstardesignatorbase AS VARCHAR(7) CHECK (LENGTH(VALUE) >= 1 AND VALUE ~ '^(([A-Z]|[0-9])+([ \+\-/]*([A-Z]|[0-9])+)*)$');
CREATE DOMAIN public.textnamebase AS VARCHAR(60) CHECK (LENGTH(VALUE) >= 1 AND VALUE ~ '^(([A-Z]|[0-9]|[, !"&#$%''''\(\)\*\+\-\./:;<=>\?@\[\\]\^_\|\{\}])*)$');
CREATE DOMAIN public.textremarkbase AS VARCHAR(5000) CHECK (LENGTH(VALUE) >= 1);
CREATE DOMAIN public.valanglebase AS NUMERIC CHECK (VALUE >= -180 AND VALUE <= 180);
CREATE DOMAIN public.valbearingbase AS NUMERIC CHECK (VALUE >= 000 AND VALUE <= 360);
CREATE DOMAIN public.valmagneticvariationbase AS NUMERIC CHECK (VALUE >= -180 AND VALUE <= 180);
CREATE DOMAIN public.valmagneticvariationchangebase AS NUMERIC CHECK (VALUE >= -180 AND VALUE <= 180);
CREATE DOMAIN public.valdistancebase AS NUMERIC CHECK (VALUE >= 0);
CREATE DOMAIN public.valdistanceverticalbase AS TEXT CHECK (VALUE ~ '^(((\+|\-){0,1}[0-9]{1,8}(\.[0-9]{1,4}){0,1})|UNL|GND|FLOOR|CEILING)$');
CREATE DOMAIN public.valdurationbase AS NUMERIC;
CREATE DOMAIN public.valflbase AS BIGINT CHECK (VALUE <= 999 AND VALUE >= 0);
CREATE DOMAIN public.valfrequencybase AS NUMERIC CHECK (VALUE > 0);
CREATE DOMAIN public.valhexbase AS TEXT CHECK (VALUE ~ '^(([A-F]|[0-9]){8})$');
CREATE DOMAIN public.vallcnbase AS NUMERIC;
CREATE DOMAIN public.valpcnbase AS NUMERIC CHECK (VALUE::text ~ '^([0-9]{1,3}(\.[0-9]){0,1})$');
CREATE DOMAIN public.valpressurebase AS NUMERIC;
CREATE DOMAIN public.valslopebase AS NUMERIC CHECK (VALUE >= -100 AND VALUE <= 100);
CREATE DOMAIN public.valspeedbase AS NUMERIC CHECK (VALUE >= 0);
CREATE DOMAIN public.valtemperaturebase AS NUMERIC;
CREATE DOMAIN public.valweightbase AS NUMERIC CHECK (VALUE >= 0);
CREATE DOMAIN public.codestatusconstructionbase AS TEXT CHECK ((VALUE IN ('IN_CONSTRUCTION', 'COMPLETED', 'DEMOLITION_PLANNED', 'IN_DEMOLITION ') OR VALUE ~ '^OTHER(:(\w|_){1,58})?$'));
CREATE DOMAIN public.codestatusoperationsbase AS TEXT CHECK ((VALUE IN ('NORMAL', 'DOWNGRADED', 'UNSERVICEABLE', 'WORK_IN_PROGRESS') OR VALUE ~ '^OTHER(:(\w|_){1,58})?$'));
CREATE DOMAIN public.codeverticalstructurebase AS TEXT CHECK ((VALUE IN ('AG_EQUIP', 'ANTENNA', 'ARCH', 'BRIDGE', 'BUILDING', 'CABLE_CAR', 'CATENARY', 'COMPRESSED_AIR_SYSTEM', 'CONTROL_MONITORING_SYSTEM', 'CONTROL_TOWER', 'COOLING_TOWER', 'CRANE', 'DAM', 'DOME', 'ELECTRICAL_EXIT_LIGHT', 'ELECTRICAL_SYSTEM', 'ELEVATOR', 'FENCE', 'FUEL_SYSTEM', 'GATE', 'GENERAL_UTILITY', 'GRAIN_ELEVATOR', 'HEAT_COOL_SYSTEM', 'INDUSTRIAL_SYSTEM', 'LIGHTHOUSE', 'MONUMENT', 'NATURAL_GAS_SYSTEM', 'NATURAL_HIGHPOINT', 'NAVAID', 'NUCLEAR_REACTOR', 'POLE', 'POWER_PLANT', 'REFINERY', 'RIG', 'SALTWATER_SYSTEM', 'SIGN', 'SPIRE', 'STACK', 'STADIUM', 'STORM_SYSTEM', 'TANK', 'TETHERED_BALLOON', 'TOWER', 'TRAMWAY', 'TRANSMISSION_LINE', 'TREE', 'URBAN', 'VEGETATION', 'WALL', 'WASTEWATER_SYSTEM', 'WATER_SYSTEM', 'WATER_TOWER', 'WINDMILL', 'WINDMILL_FARMS') OR VALUE ~ '^OTHER(:(\w|_){1,58})?$'));
CREATE DOMAIN public.codeverticalstructuremarkingbase AS TEXT CHECK ((VALUE IN ('MONOCOLOUR', 'CHEQUERED', 'HBANDS', 'VBANDS', 'FLAG', 'MARKERS') OR VALUE ~ '^OTHER(:(\w|_){1,58})?$'));
CREATE DOMAIN public.codecardinaldirectionbase AS TEXT CHECK ((VALUE IN ('N', 'NE', 'E', 'SE', 'S', 'SW', 'W', 'NW', 'NNE', 'ENE', 'ESE', 'SSE', 'SSW', 'WSW', 'WNW', 'NNW') OR VALUE ~ '^OTHER(:(\w|_){1,58})?$'));
CREATE DOMAIN public.codefreeflightbase AS TEXT CHECK ((VALUE IN ('PITCH', 'CATCH') OR VALUE ~ '^OTHER(:(\w|_){1,58})?$'));
CREATE DOMAIN public.codenavaidservicebase AS TEXT CHECK ((VALUE IN ('VOR', 'DME', 'NDB', 'TACAN', 'MKR', 'ILS', 'ILS_DME', 'MLS', 'MLS_DME', 'VORTAC', 'VOR_DME', 'NDB_DME', 'TLS', 'LOC', 'LOC_DME', 'NDB_MKR', 'DF', 'SDF') OR VALUE ~ '^OTHER(:(\w|_){1,58})?$'));
CREATE DOMAIN public.codeverticaldatumbase AS TEXT CHECK ((VALUE IN ('EGM_96', 'AHD', 'NAVD88') OR VALUE ~ '^OTHER(:(\w|_){1,58})?$'));
CREATE DOMAIN public.valdistancesignedbase AS NUMERIC;
CREATE DOMAIN public.coderoutedesignatorprefixbase AS TEXT CHECK ((VALUE IN ('K', 'U', 'S', 'T') OR VALUE ~ '^OTHER(:(\w|_){1,58})?$'));
CREATE DOMAIN public.codervsmbase AS TEXT CHECK ((VALUE IN ('RVSM', 'NON_RVSM') OR VALUE ~ '^OTHER(:(\w|_){1,58})?$'));
CREATE DOMAIN public.coderoutedesignatorletterbase AS TEXT CHECK ((VALUE IN ('A', 'B', 'G', 'H', 'J', 'L', 'M', 'N', 'P', 'Q', 'R', 'T', 'V', 'W', 'Y', 'Z') OR VALUE ~ '^OTHER(:(\w|_){1,58})?$'));
CREATE DOMAIN public.coderoutedesignatorsuffixbase AS TEXT CHECK ((VALUE IN ('F', 'G') OR VALUE ~ '^OTHER(:(\w|_){1,58})?$'));
CREATE DOMAIN public.codestatusairspacebase AS TEXT CHECK ((VALUE IN ('AVBL_FOR_ACTIVATION', 'ACTIVE', 'IN_USE', 'INACTIVE', 'INTERMITTENT') OR VALUE ~ '^OTHER(:(\w|_){1,58})?$'));
CREATE DOMAIN public.coderunwaypointrolebase AS TEXT CHECK ((VALUE IN ('START', 'THR', 'DISTHR', 'TDZ', 'MID', 'END', 'START_RUN', 'LAHSO', 'ABEAM_GLIDESLOPE', 'ABEAM_PAR', 'ABEAM_ELEVATION', 'ABEAM_TDR', 'ABEAM_RER') OR VALUE ~ '^OTHER(:(\w|_){1,58})?$'));
CREATE DOMAIN public.coderunwaybase AS TEXT CHECK ((VALUE IN ('RWY', 'FATO') OR VALUE ~ '^OTHER(:(\w|_){1,58})?$'));
CREATE DOMAIN public.codemarkingstylebase AS TEXT CHECK ((VALUE IN ('SOLID', 'DASHED', 'DOTTED') OR VALUE ~ '^OTHER(:(\w|_){1,58})?$'));
CREATE DOMAIN public.codefinalguidancebase AS TEXT CHECK ((VALUE IN ('LPV', 'LNAV_VNAV', 'LNAV', 'GLS', 'ASR', 'ARA', 'ARSR', 'PAR', 'ILS', 'ILS_DME', 'ILS_PRM', 'LDA', 'LDA_DME', 'LOC', 'LOC_BC', 'LOC_DME', 'LOC_DME_BC', 'MLS', 'MLS_DME', 'NDB', 'NDB_DME', 'SDF', 'TLS', 'VOR', 'VOR_DME', 'TACAN', 'VORTAC', 'DME', 'LP') OR VALUE ~ '^OTHER(:(\w|_){1,58})?$'));
CREATE DOMAIN public.codemissedapproachbase AS TEXT CHECK ((VALUE IN ('PRIMARY', 'SECONDARY', 'ALTERNATE', 'TACAN', 'TACANALT', 'ENGINEOUT') OR VALUE ~ '^OTHER(:(\w|_){1,58})?$'));
CREATE DOMAIN public.codeupperalphabase AS TEXT CHECK ((VALUE IN ('A', 'B', 'C', 'D', 'E', 'F', 'G', 'H', 'I', 'J', 'K', 'L', 'M', 'N', 'O', 'P', 'Q', 'R', 'S', 'T', 'U', 'V', 'W', 'X', 'Y', 'Z') OR VALUE ~ '^OTHER(:(\w|_){1,58})?$'));
CREATE DOMAIN public.codeapproachprefixbase AS TEXT CHECK ((VALUE IN ('HI', 'COPTER', 'CONVERGING') OR VALUE ~ '^OTHER(:(\w|_){1,58})?$'));
CREATE DOMAIN public.codeapproachbase AS TEXT CHECK ((VALUE IN ('ASR', 'ARA', 'ARSR', 'PAR', 'ILS', 'ILS_DME', 'ILS_PRM', 'LDA', 'LDA_DME', 'LOC', 'LOC_BC', 'LOC_DME', 'LOC_DME_BC', 'MLS', 'MLS_DME', 'NDB', 'NDB_DME', 'SDF', 'TLS', 'VOR', 'VOR_DME', 'TACAN', 'VORTAC', 'DME', 'DME_DME', 'RNP', 'GPS', 'GLONASS', 'GALILEO', 'RNAV', 'IGS') OR VALUE ~ '^OTHER(:(\w|_){1,58})?$'));
CREATE DOMAIN public.codeapprovalbase AS TEXT CHECK ((VALUE IN ('APPROVED', 'DISAPPROVED', 'NOT_AUTHORISED', 'RESTRICTED') OR VALUE ~ '^OTHER(:(\w|_){1,58})?$'));
CREATE DOMAIN public.codedesignstandardbase AS TEXT CHECK ((VALUE IN ('PANS_OPS', 'TERPS', 'CANADA_TERPS', 'NATO') OR VALUE ~ '^OTHER(:(\w|_){1,58})?$'));
CREATE DOMAIN public.codeapproachequipmentadditionalbase AS TEXT CHECK ((VALUE IN ('ADF', 'DME', 'RADAR', 'RADARDME', 'VORLOC', 'DUALVORDME', 'DUALADF', 'ADFMA', 'SPECIAL', 'DUALVHF', 'GPSRNP3', 'ADFILS', 'DUALADF_DME', 'RADAR_RNAV') OR VALUE ~ '^OTHER(:(\w|_){1,58})?$'));
CREATE DOMAIN public.codeequipmentunavailablebase AS TEXT CHECK ((VALUE IN ('STANDARD', 'NONSTANDARD') OR VALUE ~ '^OTHER(:(\w|_){1,58})?$'));
CREATE DOMAIN public.codeholdingusebase AS TEXT CHECK ((VALUE IN ('PT', 'ARRIVAL', 'MISSED_APPROACH', 'CLIMB', 'ATC') OR VALUE ~ '^OTHER(:(\w|_){1,58})?$'));
CREATE DOMAIN public.codeproceduredistancebase AS TEXT CHECK ((VALUE IN ('HAT', 'OM', 'MM', 'IM', 'PFAF', 'GSANT', 'FAF', 'MAP', 'THLD', 'VDP', 'RECH') OR VALUE ~ '^OTHER(:(\w|_){1,58})?$'));
CREATE DOMAIN public.codeminimafinalapproachpathbase AS TEXT CHECK ((VALUE IN ('STRAIGHT_IN', 'CIRCLING', 'SIDESTEP') OR VALUE ~ '^OTHER(:(\w|_){1,58})?$'));
CREATE DOMAIN public.codeminimumaltitudebase AS TEXT CHECK ((VALUE IN ('OCA', 'DA', 'MDA') OR VALUE ~ '^OTHER(:(\w|_){1,58})?$'));
CREATE DOMAIN public.codeminimumheightbase AS TEXT CHECK ((VALUE IN ('DH', 'OCH', 'MDH') OR VALUE ~ '^OTHER(:(\w|_){1,58})?$'));
CREATE DOMAIN public.codeprocedurecodingstandardbase AS TEXT CHECK ((VALUE IN ('PANS_OPS', 'ARINC_424_15', 'ARINC_424_18', 'ARINC_424_19') OR VALUE ~ '^OTHER(:(\w|_){1,58})?$'));
CREATE DOMAIN public.codesafealtitudebase AS TEXT CHECK ((VALUE IN ('MSA', 'ESA') OR VALUE ~ '^OTHER(:(\w|_){1,58})?$'));
CREATE DOMAIN public.codeobstacleassessmentsurfacebase AS TEXT CHECK ((VALUE IN ('40_TO_1', '72_TO_1', 'MA', 'FINAL', 'PT_ENTRY_AREA', 'PRIMARY', 'SECONDARY', 'ZONE1', 'ZONE2', 'ZONE3', 'AREA1', 'AREA2', 'AREA3', 'TURN_INITIATION', 'TURN', 'DER') OR VALUE ~ '^OTHER(:(\w|_){1,58})?$'));
CREATE DOMAIN public.codealtitudeadjustmentbase AS TEXT CHECK ((VALUE IN ('RA', 'AS', 'AT', 'AC', 'SI', 'XL', 'PR', 'HAA', 'MA', 'PT', 'DG', 'GS', 'CA', 'MT', 'MAH', 'SA', 'AAO', 'VA') OR VALUE ~ '^OTHER(:(\w|_){1,58})?$'));
CREATE DOMAIN public.codetaabase AS TEXT CHECK ((VALUE IN ('LEFT_BASE', 'RIGHT_BASE', 'STRAIGHT_IN') OR VALUE ~ '^OTHER(:(\w|_){1,58})?$'));
CREATE DOMAIN public.codearcdirectionbase AS TEXT CHECK ((VALUE IN ('CWA', 'CCA') OR VALUE ~ '^OTHER(:(\w|_){1,58})?$'));
CREATE DOMAIN public.codelevelseriesbase AS TEXT CHECK ((VALUE IN ('ODD', 'EVEN', 'ODD_HALF', 'EVEN_HALF') OR VALUE ~ '^OTHER(:(\w|_){1,58})?$'));
CREATE DOMAIN public.valalarmlimitbase AS NUMERIC CHECK (VALUE >= 0 AND VALUE <= 50.8);
CREATE DOMAIN public.valchannelnumberbase AS NUMERIC;
CREATE DOMAIN public.codesegmentterminationbase AS TEXT CHECK ((VALUE IN ('ALTITUDE', 'DISTANCE', 'DURATION', 'INTERCEPT') OR VALUE ~ '^OTHER(:(\w|_){1,58})?$'));
CREATE DOMAIN public.codereferencerolebase AS TEXT CHECK ((VALUE IN ('INTERSECTION', 'RECNAV', 'ATD', 'RAD_DME') OR VALUE ~ '^OTHER(:(\w|_){1,58})?$'));
CREATE DOMAIN public.codetrajectorybase AS TEXT CHECK ((VALUE IN ('STRAIGHT', 'ARC', 'PT', 'BASETURN', 'HOLDING') OR VALUE ~ '^OTHER(:(\w|_){1,58})?$'));
CREATE DOMAIN public.textnotebase AS VARCHAR(10000) CHECK (LENGTH(VALUE) >= 1);
CREATE DOMAIN public.coderunwaymarkingbase AS TEXT CHECK ((VALUE IN ('PRECISION', 'NONPRECISION', 'BASIC', 'NONE', 'RUNWAY_NUMBERS', 'NON_STANDARD', 'HELIPORT') OR VALUE ~ '^OTHER(:(\w|_){1,58})?$'));
CREATE DOMAIN public.codervrreadingbase AS TEXT CHECK ((VALUE IN ('TDZ', 'MID', 'TO') OR VALUE ~ '^OTHER(:(\w|_){1,58})?$'));
CREATE DOMAIN public.codestatusnavaidbase AS TEXT CHECK ((VALUE IN ('OPERATIONAL', 'UNSERVICEABLE', 'ONTEST', 'INTERRUPT', 'PARTIAL', 'CONDITIONAL', 'FALSE_INDICATION', 'FALSE_POSSIBLE', 'DISPLACED', 'IN_CONSTRUCTION') OR VALUE ~ '^OTHER(:(\w|_){1,58})?$'));
CREATE DOMAIN public.codeoperationairportheliportbase AS TEXT CHECK ((VALUE IN ('LANDING', 'TAKEOFF', 'TOUCHGO', 'TRAIN_APPROACH', 'ALTN_LANDING', 'AIRSHOW', 'ALL') OR VALUE ~ '^OTHER(:(\w|_){1,58})?$'));
CREATE DOMAIN public.codedistanceindicationbase AS TEXT CHECK ((VALUE IN ('DME', 'GEODETIC') OR VALUE ~ '^OTHER(:(\w|_){1,58})?$'));
CREATE DOMAIN public.codeobstacleareabase AS TEXT CHECK ((VALUE IN ('AREA1', 'AREA2', 'AREA3', 'AREA4', 'OLS', 'FAR77', 'MANAGED') OR VALUE ~ '^OTHER(:(\w|_){1,58})?$'));
CREATE DOMAIN public.codeairspaceclassificationbase AS TEXT CHECK ((VALUE IN ('A', 'B', 'C', 'D', 'E', 'F', 'G') OR VALUE ~ '^OTHER(:(\w|_){1,58})?$'));
CREATE DOMAIN public.codeapronelementbase AS TEXT CHECK ((VALUE IN ('NORMAL', 'PARKING', 'RAMP', 'CARGO', 'FUEL', 'HARDSTAND', 'MAINT', 'MILITARY', 'LOADING', 'TAXILANE', 'TURNAROUND', 'TEMPORARY', 'STAIRS') OR VALUE ~ '^OTHER(:(\w|_){1,58})?$'));
CREATE DOMAIN public.coderunwayelementbase AS TEXT CHECK ((VALUE IN ('NORMAL', 'INTERSECTION', 'DISPLACED', 'SHOULDER') OR VALUE ~ '^OTHER(:(\w|_){1,58})?$'));
CREATE DOMAIN public.codeauthorityrolebase AS TEXT CHECK ((VALUE IN ('OWN', 'OPERATE', 'SUPERVISE') OR VALUE ~ '^OTHER(:(\w|_){1,58})?$'));
CREATE DOMAIN public.codevorbase AS TEXT CHECK ((VALUE IN ('VOR', 'DVOR', 'VOT') OR VALUE ~ '^OTHER(:(\w|_){1,58})?$'));
CREATE DOMAIN public.codeapproachlightingicaobase AS TEXT CHECK ((VALUE IN ('SIMPLE', 'CAT1', 'CAT23', 'CIRCLING', 'LEADIN', 'NONE') OR VALUE ~ '^OTHER(:(\w|_){1,58})?$'));
CREATE DOMAIN public.codelightingjarbase AS TEXT CHECK ((VALUE IN ('FALS', 'IALS', 'BALS', 'NALS') OR VALUE ~ '^OTHER(:(\w|_){1,58})?$'));
CREATE DOMAIN public.codeworkareabase AS TEXT CHECK ((VALUE IN ('CONSTRUCTION', 'SURFACEWORK', 'PARKED') OR VALUE ~ '^OTHER(:(\w|_){1,58})?$'));
CREATE DOMAIN public.codeverticalstructurematerialbase AS TEXT CHECK ((VALUE IN ('ADOBE_BRICK', 'ALUMINIUM', 'BRICK', 'CONCRETE', 'FIBREGLASS', 'GLASS', 'IRON', 'MASONRY', 'METAL', 'MUD', 'PLANT', 'PRESTRESSED_CONCRETE', 'REINFORCED_CONCRETE', 'SOD', 'STEEL', 'STONE', 'TREATED_TIMBER', 'WOOD') OR VALUE ~ '^OTHER(:(\w|_){1,58})?$'));
CREATE DOMAIN public.codeguidancelinebase AS TEXT CHECK ((VALUE IN ('RWY', 'TWY', 'APRON', 'GATE_TLANE', 'LI_TLANE', 'LO_TLANE', 'AIR_TLANE') OR VALUE ~ '^OTHER(:(\w|_){1,58})?$'));
CREATE DOMAIN public.codeairportwarningbase AS TEXT CHECK ((VALUE IN ('WIP', 'EQUIP', 'BIRD', 'ANIMAL', 'RUBBER_REMOVAL', 'PARKED_ACFT', 'RESURFACING', 'PAVING', 'PAINTING', 'INSPECTION', 'GRASS_CUTTING', 'CALIBRATION') OR VALUE ~ '^OTHER(:(\w|_){1,58})?$'));
CREATE DOMAIN public.codeprotectareasectionbase AS TEXT CHECK ((VALUE IN ('EDGE', 'END', 'CL') OR VALUE ~ '^OTHER(:(\w|_){1,58})?$'));
CREATE DOMAIN public.coderoutebase AS TEXT CHECK ((VALUE IN ('ATS', 'NAT') OR VALUE ~ '^OTHER(:(\w|_){1,58})?$'));
CREATE DOMAIN public.codeairspacepointpositionbase AS TEXT CHECK ((VALUE IN ('IN', 'OUT', 'BORDER') OR VALUE ~ '^OTHER(:(\w|_){1,58})?$'));
CREATE DOMAIN public.valdepthbase AS NUMERIC;
CREATE DOMAIN public.codecontaminationbase AS TEXT CHECK ((VALUE IN ('NONE', 'DAMP', 'WATER', 'FROST', 'DRY_SNOW', 'WET_SNOW', 'SLUSH', 'ICE', 'COMPACT_SNOW', 'RUT', 'ASH', 'SAND', 'OIL', 'RUBBER', 'GRAS') OR VALUE ~ '^OTHER(:(\w|_){1,58})?$'));
CREATE DOMAIN public.codefrictiondevicebase AS TEXT CHECK ((VALUE IN ('BRD', 'GRT', 'MUM', 'RFT', 'SFH', 'SFL', 'SKH', 'SKL', 'TAP') OR VALUE ~ '^OTHER(:(\w|_){1,58})?$'));
CREATE DOMAIN public.codefrictionestimatebase AS TEXT CHECK ((VALUE IN ('GOOD', 'MEDIUM_GOOD', 'MEDIUM', 'MEDIUM_POOR', 'POOR', 'UNRELIABLE') OR VALUE ~ '^OTHER(:(\w|_){1,58})?$'));
CREATE DOMAIN public.codeheightreferencebase AS TEXT CHECK ((VALUE IN ('HAT', 'HAA', 'HAL', 'HAS') OR VALUE ~ '^OTHER(:(\w|_){1,58})?$'));
CREATE DOMAIN public.valfrictionbase AS NUMERIC CHECK (VALUE::text ~ '^(0\.[0-9]{2})$');
CREATE DOMAIN public.codeuuidbase AS TEXT CHECK (VALUE ~ '^(([A-F]|[a-f]|[0-9]|\-)*)$');
CREATE DOMAIN public.codeaerialrefuellingpointbase AS TEXT CHECK ((VALUE IN ('INITIAL', 'CONTROL', 'CHECK', 'EXIT', 'ENTRY', 'ANCHOR', 'PATTERN') OR VALUE ~ '^OTHER(:(\w|_){1,58})?$'));
CREATE DOMAIN public.codeaerialrefuellingbase AS TEXT CHECK ((VALUE IN ('TRACK', 'ANCHOR', 'BOTH') OR VALUE ~ '^OTHER(:(\w|_){1,58})?$'));
CREATE DOMAIN public.codeloadingbridgebase AS TEXT CHECK ((VALUE IN ('ARM', 'MOVABLE_ARM', 'PORTABLE_RAMP', 'PORTABLE_STAIRS') OR VALUE ~ '^OTHER(:(\w|_){1,58})?$'));
CREATE DOMAIN public.codeapproachguidancebase AS TEXT CHECK ((VALUE IN ('NON_PRECISION', 'ILS_PRECISION_CAT_I', 'ILS_PRECISION_CAT_II', 'ILS_PRECISION_CAT_IIIA', 'ILS_PRECISION_CAT_IIIB', 'ILS_PRECISION_CAT_IIIC', 'ILS_PRECISION_CAT_IIID', 'MLS_PRECISION') OR VALUE ~ '^OTHER(:(\w|_){1,58})?$'));
CREATE DOMAIN public.codeaircraftwingspanclassbase AS TEXT CHECK ((VALUE IN ('I', 'II', 'III', 'IV', 'V', 'VI') OR VALUE ~ '^OTHER(:(\w|_){1,58})?$'));
CREATE DOMAIN public.codearrestinggearengagedevicebase AS TEXT CHECK ((VALUE IN ('61QSII', '62NI', '63PI', 'NET_A30', 'NET_A40', 'BAK_11_STRUT', 'BAK_12', 'BAK_14_HOOK', 'BAK_15_STANCHION_NET', 'BAK_15_HOOK', 'EMAS', 'HOOK_CABLE', 'HP_NET', 'J_BAR', 'JET_BARRIER', 'MA_1_NET', 'MA_1A_HOOK_CABLE', 'NET', 'HOOK_H') OR VALUE ~ '^OTHER(:(\w|_){1,58})?$'));
CREATE DOMAIN public.codeobstructionidsurfacezonebase AS TEXT CHECK ((VALUE IN ('APPROACH', 'CONICAL', 'HORIZONTAL', 'PRIMARY', 'TRANSITION') OR VALUE ~ '^OTHER(:(\w|_){1,58})?$'));
CREATE DOMAIN public.codebuoybase AS TEXT CHECK ((VALUE IN ('BLACK_RED_FL2', 'GREEN', 'GREEN_RED_GFL', 'Q3_VQ3', 'Q6_VQ6', 'Q9_VQ9', 'Q_VQ', 'RED', 'RED_GREEN_RFL', 'RED_WHITE', 'WHITE', 'YELLOW') OR VALUE ~ '^OTHER(:(\w|_){1,58})?$'));
CREATE DOMAIN public.coderoadbase AS TEXT CHECK ((VALUE IN ('SERVICE', 'PUBLIC') OR VALUE ~ '^OTHER(:(\w|_){1,58})?$'));
CREATE DOMAIN public.codeaerialrefuellingprefixbase AS TEXT CHECK ((VALUE IN ('AR') OR VALUE ~ '^OTHER(:(\w|_){1,58})?$'));
CREATE DOMAIN public.codemilitarytrainingbase AS TEXT CHECK ((VALUE IN ('IR', 'VR', 'SR') OR VALUE ~ '^OTHER(:(\w|_){1,58})?$'));
CREATE DOMAIN public.codefacilityrankingbase AS TEXT CHECK ((VALUE IN ('PRIMARY', 'SECONDARY', 'ALTERNATE', 'EMERG', 'GUARD') OR VALUE ~ '^OTHER(:(\w|_){1,58})?$'));
CREATE DOMAIN public.codemilitaryroutepointbase AS TEXT CHECK ((VALUE IN ('S', 'T', 'X', 'AS', 'AX', 'ASX') OR VALUE ~ '^OTHER(:(\w|_){1,58})?$'));
CREATE DOMAIN public.codearrestinggearenergyabsorbbase AS TEXT CHECK ((VALUE IN ('ROTARY_1300', 'ROTARY_2800', 'ROTARY_34B_1A', 'ROTARY_34B_1B', 'ROTARY_34B_1C', 'ROTARY_34D_1F', 'ROTARY_44B_2C', 'ROTARY_44B_2D', 'ROTARY_44B_2E', 'ROTARY_44B_2F', 'ROTARY_44B_2H', 'ROTARY_44B_2I', 'ROTARY_44B_2L', 'ROTARY_44B_3A', 'ROTARY_44B_3H', 'ROTARY_44B_3L', 'ROTARY_44B_4C', 'ROTARY_44B_4E', 'ROTARY_44B_4H', 'ROTARY_500S', 'ROTARY_500S_4', 'ROTARY_500S_6', 'ROTARY_500S_8', 'ROTARYTRANS_500S_8', 'ROTARY_AAE_64', 'ROTARY_BAK_12A', 'ROTARY_BAK_12B', 'ROTARY_BAK_13', 'LINEAR_BAK_6', 'ROTARY_BAK_9', 'DISK_BEFAB_12_3', 'DISK_BEFAB_20_4', 'DISK_BEFAB_21_2', 'DISK_BEFAB_24_4', 'DISK_BEFAB_56_2', 'DISK_BEFAB_6_3', 'DISK_BEFAB_60_2', 'DISK_BEFAB_8_3', 'CHAIN_CHAG', 'ROTARY_DUAL_BAK_12', 'ROTARY_E15', 'ROTARY_E27', 'ROTARY_E28', 'CHAIN_E5', 'CHAIN_E5_1', 'CHAIN_E5_2', 'CHAIN_E5_3', 'CHAIN_E6', 'ROTARY_CHAIN_JETSTOP', 'MOBILROTARY_M21', 'MOBILROTARY_MAAS', 'MOBILROTARY_MAG_I', 'MOBILROTARY_MAG_II', 'MOBILROTARY_MAG_III', 'MOBILROTARY_MAG_IV', 'MOBILROTARY_MAG_IX', 'MOBILROTARY_MAG_VI', 'MOBILROTARY_MAG_VII', 'MOBILROTARY_MAG_VIII', 'MOBILROTARY_MAG_X', 'TEXTILE_MB_100', 'TEXTILE_MB_60', 'MOBILROTARY_HYDRAULIC_WATER', 'ROTARY_PUAG_MK_21', 'DISK_RAF_MK_12A', 'DISK_RAF_MK_6', 'RAF_PORTABLE_AGEAR', 'DISK_RAF_TYPEA_BEFAB_6_3', 'DISK_RAF_TYPEB_BEFAB_12_3', 'ROTARY_RHAG_MK_1', 'ROTARY_HYDRAULIC_WATER', 'BARRIER_DISK_SAFELAND', 'LINEAR_SPRAG_MK_1') OR VALUE ~ '^OTHER(:(\w|_){1,58})?$'));
CREATE DOMAIN public.codeemissionbandbase AS TEXT CHECK ((VALUE IN ('U', 'H', 'M') OR VALUE ~ '^OTHER(:(\w|_){1,58})?$'));
CREATE DOMAIN public.codemeteoconditionsbase AS TEXT CHECK ((VALUE IN ('IMC', 'VMC', 'ALL') OR VALUE ~ '^OTHER(:(\w|_){1,58})?$'));
CREATE DOMAIN public.codevalueinterpretationbase AS TEXT CHECK ((VALUE IN ('ABOVE', 'AT_OR_ABOVE', 'AT_OR_BELOW', 'BELOW') OR VALUE ~ '^OTHER(:(\w|_){1,58})?$'));
CREATE DOMAIN public.codenavigationareabase AS TEXT CHECK ((VALUE IN ('PNA', 'OMNI', 'DVA') OR VALUE ~ '^OTHER(:(\w|_){1,58})?$'));
CREATE DOMAIN public.codeprocedureavailabilitybase AS TEXT CHECK ((VALUE IN ('USABLE', 'UNUSABLE') OR VALUE ~ '^OTHER(:(\w|_){1,58})?$'));
CREATE DOMAIN public.codepilotcontrolledlightingbase AS TEXT CHECK ((VALUE IN ('STANDARD_FAA', 'NON_STANDARD') OR VALUE ~ '^OTHER(:(\w|_){1,58})?$'));
CREATE DOMAIN public.codeintensitystandbybase AS TEXT CHECK ((VALUE IN ('OFF', 'LOW') OR VALUE ~ '^OTHER(:(\w|_){1,58})?$'));
CREATE DOMAIN public.textphonebase AS TEXT CHECK (VALUE ~ '^((\+)?[0-9 \-\(\)]+)$');
CREATE DOMAIN public.codetelecomnetworkbase AS TEXT CHECK ((VALUE IN ('AFTN', 'AMHS', 'INTERNET', 'SITA', 'ACARS', 'ADNS') OR VALUE ~ '^OTHER(:(\w|_){1,58})?$'));
CREATE DOMAIN public.codeflightdestinationbase AS TEXT CHECK ((VALUE IN ('ARR', 'DEP', 'OVERFLY', 'ALL') OR VALUE ~ '^OTHER(:(\w|_){1,58})?$'));
CREATE DOMAIN public.codeserviceinformationbase AS TEXT CHECK ((VALUE IN ('AFIS', 'AIS', 'ATIS', 'BRIEFING', 'FIS', 'OFIS_VHF', 'OFIS_HF', 'NOTAM', 'INFO', 'RAF', 'METAR', 'SIGMET', 'TWEB', 'TAF', 'VOLMET', 'ALTIMETER', 'ASOS', 'AWOS') OR VALUE ~ '^OTHER(:(\w|_){1,58})?$'));
CREATE DOMAIN public.codeserviceatfmbase AS TEXT CHECK ((VALUE IN ('FPL', 'FPLV', 'ATFM', 'CLEARANCE', 'SCHED') OR VALUE ~ '^OTHER(:(\w|_){1,58})?$'));
CREATE DOMAIN public.codeserviceatcbase AS TEXT CHECK ((VALUE IN ('ACS', 'UAC', 'OACS', 'APP', 'TWR', 'ADVS', 'EFAS', 'CTAF') OR VALUE ~ '^OTHER(:(\w|_){1,58})?$'));
CREATE DOMAIN public.codeservicesarbase AS TEXT CHECK ((VALUE IN ('ALRS', 'SAR', 'RCC') OR VALUE ~ '^OTHER(:(\w|_){1,58})?$'));
CREATE DOMAIN public.codecommunicationchannelbase AS TEXT CHECK ((VALUE ~ '^OTHER(:(\w|_){1,58})?$'));
CREATE DOMAIN public.codepassengerservicebase AS TEXT CHECK ((VALUE IN ('CUST', 'SAN', 'SECUR', 'VET', 'HOTEL', 'TRANSPORT', 'REST', 'INFO', 'BANK', 'POST', 'MEDIC') OR VALUE ~ '^OTHER(:(\w|_){1,58})?$'));
CREATE DOMAIN public.codeservicegroundcontrolbase AS TEXT CHECK ((VALUE IN ('TWR', 'SMGCS', 'TAXI') OR VALUE ~ '^OTHER(:(\w|_){1,58})?$'));
CREATE DOMAIN public.codestatusservicebase AS TEXT CHECK ((VALUE IN ('NORMAL', 'LIMITED', 'ONTEST', 'UNSERVICEABLE') OR VALUE ~ '^OTHER(:(\w|_){1,58})?$'));
CREATE DOMAIN public.codecommunicationmodebase AS TEXT CHECK ((VALUE IN ('HF', 'VHF', 'VDL1', 'VDL2', 'VDL4', 'AMSS', 'ADS_B', 'ADS_B_VDL', 'HFDL', 'VHF_833', 'UHF') OR VALUE ~ '^OTHER(:(\w|_){1,58})?$'));
CREATE DOMAIN public.codecommunicationdirectionbase AS TEXT CHECK ((VALUE IN ('UPLINK', 'DOWNLINK', 'BIDIRECTIONAL', 'UPCAST', 'DOWNCAST') OR VALUE ~ '^OTHER(:(\w|_){1,58})?$'));
CREATE DOMAIN public.codecheckpointcategorybase AS TEXT CHECK ((VALUE IN ('A', 'G') OR VALUE ~ '^OTHER(:(\w|_){1,58})?$'));
CREATE DOMAIN public.codelightholdingpositionbase AS TEXT CHECK ((VALUE IN ('STOP_BAR', 'SIGN') OR VALUE ~ '^OTHER(:(\w|_){1,58})?$'));
CREATE DOMAIN public.codenavigationarearestrictionbase AS TEXT CHECK ((VALUE IN ('VECTOR', 'OMNIDIRECTIONAL') OR VALUE ~ '^OTHER(:(\w|_){1,58})?$'));
CREATE DOMAIN public.codesystemactivationbase AS TEXT CHECK ((VALUE IN ('ON', 'ON_OR_OFF', 'OFF') OR VALUE ~ '^OTHER(:(\w|_){1,58})?$'));
CREATE DOMAIN public.vallightintensitybase AS NUMERIC;
CREATE DOMAIN public.codewaketurbulencebase AS TEXT CHECK ((VALUE IN ('LOW', 'MEDIUM', 'HIGH') OR VALUE ~ '^OTHER(:(\w|_){1,58})?$'));
CREATE DOMAIN public.codeparbase AS TEXT CHECK ((VALUE IN ('FPN16', 'FPN62', 'GPN22', 'GPN25', 'MPN14K', 'TPN19') OR VALUE ~ '^OTHER(:(\w|_){1,58})?$'));
CREATE DOMAIN public.codeprimaryradarbase AS TEXT CHECK ((VALUE IN ('ASR', 'ARSR') OR VALUE ~ '^OTHER(:(\w|_){1,58})?$'));
CREATE DOMAIN public.coderadarservicebase AS TEXT CHECK ((VALUE IN ('PAR', 'ARSR', 'ASR', 'SSR') OR VALUE ~ '^OTHER(:(\w|_){1,58})?$'));
CREATE DOMAIN public.codereflectorbase AS TEXT CHECK ((VALUE IN ('TOUCHDOWN', 'RUNWAY_END', 'REFERENCE') OR VALUE ~ '^OTHER(:(\w|_){1,58})?$'));
CREATE DOMAIN public.codestandbypowerbase AS TEXT CHECK ((VALUE IN ('BATTERY', 'COMMERCIAL', 'GENERATOR', 'UNKNOWN', 'NONE') OR VALUE ~ '^OTHER(:(\w|_){1,58})?$'));
CREATE DOMAIN public.codetransponderbase AS TEXT CHECK ((VALUE IN ('MODE_1', 'MODE_2', 'MODE_3A', 'MODE_4', 'MODE_5', 'MODE_C', 'MODE_S') OR VALUE ~ '^OTHER(:(\w|_){1,58})?$'));
CREATE DOMAIN public.codeairspacedependencybase AS TEXT CHECK ((VALUE IN ('FULL_GEOMETRY', 'HORZ_PROJECTION') OR VALUE ~ '^OTHER(:(\w|_){1,58})?$'));
CREATE DOMAIN public.codeunitdependencybase AS TEXT CHECK ((VALUE IN ('OWNER', 'PROVIDER', 'ALTERNATE') OR VALUE ~ '^OTHER(:(\w|_){1,58})?$'));
CREATE DOMAIN public.codevisualdockingguidancebase AS TEXT CHECK ((VALUE IN ('AGNIS ', 'PAPA', 'SAFE_GATE', 'SAFE_DOC', 'APIS', 'A_VDGS', 'AGNIS_STOP ', 'AGNIS_PAPA') OR VALUE ~ '^OTHER(:(\w|_){1,58})?$'));
CREATE DOMAIN public.codemarkingconditionbase AS TEXT CHECK ((VALUE IN ('GOOD', 'FAIR', 'POOR', 'EXCELLENT') OR VALUE ~ '^OTHER(:(\w|_){1,58})?$'));
CREATE DOMAIN public.datebase AS DATE;
CREATE DOMAIN public.codenavaidpurposebase AS TEXT CHECK ((VALUE IN ('TERMINAL', 'ENROUTE', 'ALL') OR VALUE ~ '^OTHER(:(\w|_){1,58})?$'));
CREATE DOMAIN public.coderuleprocedurebase AS TEXT CHECK ((VALUE IN ('RULE', 'LAW', 'PROCEDURE', 'PRACTICE', 'ICAO_DIFF') OR VALUE ~ '^OTHER(:(\w|_){1,58})?$'));
CREATE DOMAIN public.coderuleproceduretitlebase AS TEXT CHECK ((VALUE IN ('ENTRY_TRANSIT_DEPARTURE_OF_AIRCRAFT', 'ENTRY_TRANSIT_DEPARTURE_SCHEDULED', 'ENTRY_TRANSIT_DEPARTURE_NON_SCHEDULED', 'ENTRY_TRANSIT_DEPARTURE_PRIVATE', 'PUBLIC_HEALTH_MEASURES_AIRCRAFT', 'CUSTOMS_REQUIREMENTS', 'IMMIGRATION_REQUIREMENTS', 'PUBLIC_HEALTH_MEASURES_PASSENGERS', 'ENTRY_TRANSIT_DEPARTURE_CARGO', 'AIRCRAFT_INSTRUMENTS_EQUIPMENT_FLIGHT_DOCUMENTS', 'NATIONAL_REGULATIONS', 'INTERNATIONAL_AGREEMENTS_CONVENTIONS', 'DIFFERENCES_ICAO_STANDARDS_RECOMMENDED_PRACTICES_PROCEDURES', 'MEASURING_SYSTEM_AIRCRAFT_MARKINGS_HOLIDAYS', 'ABBREVIATIONS_AIS_PUBLICATIONS', 'AERODROME_HELIPORT_CHARGES', 'AIR_NAVIGATION_SERVICES_CHARGES', 'FLIGHT_RULES_GENERAL', 'VISUAL_FLIGHT_RULES', 'INSTRUMENT_FLIGHT_RULES', 'ATS_AIRSPACE_CLASSIFICATION', 'HOLDING_ APPROACH_DEPARTURE_PROCEDURES', 'ATS_SURVEILLANCE_SERVICES_PROCEDURES', 'ALTIMETER_SETTING_PROCEDURES', 'REGIONAL_SUPPLEMENTARY_PROCEDURES', 'AIR_TRAFFIC_FLOW_MANAGEMENT', 'FLIGHT_PLANNING', 'ADDRESSING_FLIGHT_PLAN_MESSAGES', 'INTERCEPTION_CIVIL_AIRCRAFT', 'UNLAWFUL_INTERFERENCE', 'AIR_TRAFFIC_INCIDENTS', 'AERODROME_HELIPORT_AVAILABILITY', 'LOCAL_TRAFFIC_REGULATIONS', 'NOISE_ABATEMENT_PROCEDURES', 'AERODROME_FLIGHT_PROCEDURES', 'AERODROME_BIRD_CONCENTRATION') OR VALUE ~ '^OTHER(:(\w|_){1,58})?$'));
CREATE DOMAIN public.codegradeseparationbase AS TEXT CHECK ((VALUE IN ('UNDERPASS', 'OVERPASS') OR VALUE ~ '^OTHER(:(\w|_){1,58})?$'));
CREATE DOMAIN public.codetaxiwayelementbase AS TEXT CHECK ((VALUE IN ('NORMAL', 'INTERSECTION', 'SHOULDER', 'HOLDING_BAY') OR VALUE ~ '^OTHER(:(\w|_){1,58})?$'));
CREATE DOMAIN public.codeauralmorsebase AS TEXT CHECK (VALUE ~ '^(([\-\.]*))$');
CREATE DOMAIN public.coderadiosignalbase AS TEXT CHECK ((VALUE IN ('AZIMUTH', 'DISTANCE', 'BEAM', 'VOICE', 'DATALINK') OR VALUE ~ '^OTHER(:(\w|_){1,58})?$'));
CREATE DOMAIN public.codesignalperformanceilsbase AS TEXT CHECK ((VALUE IN ('I', 'II', 'III') OR VALUE ~ '^OTHER(:(\w|_){1,58})?$'));
CREATE DOMAIN public.codecoursequalityilsbase AS TEXT CHECK ((VALUE IN ('A', 'B', 'C', 'D', 'E', 'T') OR VALUE ~ '^OTHER(:(\w|_){1,58})?$'));
CREATE DOMAIN public.codeintegritylevelilsbase AS TEXT CHECK ((VALUE IN ('1', '2', '3', '4') OR VALUE ~ '^OTHER(:(\w|_){1,58})?$'));
CREATE DOMAIN public.codeholdingcategorybase AS TEXT CHECK ((VALUE IN ('NON_PRECISION', 'CAT_I', 'CAT_II_III') OR VALUE ~ '^OTHER(:(\w|_){1,58})?$'));
CREATE DOMAIN public.codenotepurposebase AS TEXT CHECK ((VALUE IN ('DESCRIPTION', 'REMARK', 'WARNING', 'DISCLAIMER') OR VALUE ~ '^OTHER(:(\w|_){1,58})?$'));
CREATE DOMAIN public.codenavigationequipmentbase AS TEXT CHECK ((VALUE IN ('DME', 'VOR_DME', 'DME_DME', 'TACAN', 'ILS', 'MLS', 'GNSS', 'WAAS', 'LORAN', 'INS', 'FMS') OR VALUE ~ '^OTHER(:(\w|_){1,58})?$'));
CREATE DOMAIN public.codenavigationspecificationbase AS TEXT CHECK ((VALUE IN ('RNAV_10', 'RNAV_5', 'RNAV_2', 'RNAV_1', 'RNP_4', 'RNP_2', 'BASIC_RNP_1', 'ADVANCED_RNP_1', 'RNP_APCH', 'RNP_AR_APCH') OR VALUE ~ '^OTHER(:(\w|_){1,58})?$'));
CREATE DOMAIN public.codeequipmentanticollisionbase AS TEXT CHECK ((VALUE IN ('ACAS_I', 'ACAS_II', 'GPWS') OR VALUE ~ '^OTHER(:(\w|_){1,58})?$'));
CREATE DOMAIN public.valpercentbase AS NUMERIC CHECK (VALUE >= 0 AND VALUE <= 100);
CREATE DOMAIN public.datetimebase AS TIMESTAMPTZ;
CREATE DOMAIN public.codelogicaloperatorbase AS TEXT CHECK ((VALUE IN ('AND', 'OR', 'NOT', 'NONE') OR VALUE ~ '^OTHER(:(\w|_){1,58})?$'));
CREATE DOMAIN public.codestatusairportbase AS TEXT CHECK ((VALUE IN ('NORMAL', 'LIMITED', 'CLOSED') OR VALUE ~ '^OTHER(:(\w|_){1,58})?$'));
CREATE DOMAIN public.codeoperationmanoeuvringareabase AS TEXT CHECK ((VALUE IN ('LANDING', 'TAKEOFF', 'TOUCHGO', 'TRAIN_APPROACH', 'TAXIING', 'CROSSING', 'AIRSHOW', 'ALL') OR VALUE ~ '^OTHER(:(\w|_){1,58})?$'));
CREATE DOMAIN public.textpropertynamebase AS VARCHAR(60) CHECK (LENGTH(VALUE) >= 1 AND VALUE ~ '^([a-z][A-Za-z]*)$');
CREATE DOMAIN public.coderelativepositionbase AS TEXT CHECK ((VALUE IN ('BEFORE', 'AT', 'AFTER') OR VALUE ~ '^OTHER(:(\w|_){1,58})?$'));
