CREATE INDEX IF NOT EXISTS IDX_POINT_HJID ON GML.POINT (HJID);

CREATE INDEX IF NOT EXISTS IDX_POINT_HJID_GEOM_COVER ON GML.POINT (HJID) INCLUDE (GEOM);

CREATE INDEX IF NOT EXISTS IDX_POINT_GEOM ON GML.POINT USING GIST (GEOM);

CREATE INDEX IF NOT EXISTS IDX_POINT_GML_POINT_HJID ON GML.GML_POINT (GML_POINT_HJID);

CREATE INDEX IF NOT EXISTS IDX_GML_POINT_INDEX ON GML.GML_POINT (INDEX);

CREATE INDEX IF NOT EXISTS IDX_GML_POINT_PARENT_LINK ON GML.GML_POINT (GML_POINT_HJID, HJID) INCLUDE (INDEX);

CREATE INDEX IF NOT EXISTS IDX_AIXM_POINT_HJID ON GML.AIXM_POINT (HJID);

CREATE INDEX IF NOT EXISTS IDX_AIXM_ELEVATED_POINT_HJID ON GML.AIXM_ELEVATED_POINT (HJID);

CREATE INDEX IF NOT EXISTS IDX_AIXM_ELEVATEDPOINT_PT_POINT_HJID ON GML.AIXM_POINT_PT (POINT_HJID);

CREATE INDEX IF NOT EXISTS IDX_AIXM_ELEVATEDPOINT_PT_HJID ON GML.AIXM_ELEVATEDPOINT_PT (HJID);

CREATE INDEX IF NOT EXISTS IDX_AIXM_ELEVATEDPOINT_PT_ELEVATED_POINT_HJID ON GML.AIXM_ELEVATEDPOINT_PT (ELEVATED_POINT_HJID);

CREATE MATERIALIZED VIEW GML.AIXM_POINT_PT_VIEW AS (
	SELECT
		GML.AIXM_POINT_PT.HJID,
		GML.POINT.ID,
		GML.AIXM_POINT.HORIZONTALACCURACY,
		GML.AIXM_POINT.HORIZONTALACCURACY_UOM,
		GML.AIXM_POINT.HORIZONTALACCURACY_NILREASON,
		(
			SELECT
				COALESCE(
					JSONB_AGG(
						JSONB_BUILD_OBJECT(
							'hjid',
							AIXM.AIXM_PROPERTY.HJID,
							'nilreason',
							AIXM.AIXM_PROPERTY.NIL_REASON
						)
					),
					'[]'::JSONB
				)
			FROM
				GML.AIXM_POINT_ANNOTATION_LINK
				JOIN AIXM.AIXM_PROPERTY ON GML.AIXM_POINT_ANNOTATION_LINK.ANNOTATION_HJID = AIXM.AIXM_PROPERTY.HJID
			WHERE
				GML.AIXM_POINT_ANNOTATION_LINK.AIXM_POINT_HJID = GML.AIXM_POINT.HJID
		) AS ANNOTATION,
		GML.POINT.GEOM AS GEOM
	FROM
		GML.AIXM_POINT_PT
		INNER JOIN GML.AIXM_POINT ON GML.AIXM_POINT_PT.POINT_HJID = GML.AIXM_POINT.HJID
		INNER JOIN GML.POINT ON GML.AIXM_POINT.HJID = GML.POINT.HJID
);

CREATE UNIQUE INDEX IF NOT EXISTS IDX_AIXM_POINT_PT_VIEW_HJID ON GML.AIXM_POINT_PT_VIEW (HJID);

CREATE INDEX IF NOT EXISTS IDX_AIXM_POINT_PT_VIEW_GEOM ON GML.AIXM_POINT_PT_VIEW USING GIST (GEOM);

CREATE MATERIALIZED VIEW GML.AIXM_ELEVATED_POINT_PT_VIEW AS (
	SELECT
		GML.AIXM_ELEVATEDPOINT_PT.HJID,
		GML.POINT.ID,
		GML.AIXM_ELEVATED_POINT.HORIZONTALACCURACY,
		GML.AIXM_ELEVATED_POINT.HORIZONTALACCURACY_UOM,
		GML.AIXM_ELEVATED_POINT.HORIZONTALACCURACY_NILREASON,
		GML.AIXM_ELEVATED_POINT.GEOIDUNDULATION,
		GML.AIXM_ELEVATED_POINT.GEOIDUNDULATION_UOM,
		GML.AIXM_ELEVATED_POINT.GEOIDUNDULATION_NILREASON,
		GML.AIXM_ELEVATED_POINT.VERTICALACCURACY,
		GML.AIXM_ELEVATED_POINT.VERTICALACCURACY_UOM,
		GML.AIXM_ELEVATED_POINT.VERTICALACCURACY_NILREASON,
		GML.AIXM_ELEVATED_POINT.ELEVATION,
		GML.AIXM_ELEVATED_POINT.ELEVATION_UOM,
		GML.AIXM_ELEVATED_POINT.ELEVATION_NILREASON,
		(
			SELECT
				COALESCE(
					JSONB_AGG(
						JSONB_BUILD_OBJECT(
							'hjid',
							AIXM.AIXM_PROPERTY.HJID,
							'nilreason',
							AIXM.AIXM_PROPERTY.NIL_REASON
						)
					),
					'[]'::JSONB
				)
			FROM
				GML.AIXM_ELEVATED_POINT_ANNOTATION_LINK
				JOIN AIXM.AIXM_PROPERTY ON GML.AIXM_ELEVATED_POINT_ANNOTATION_LINK.ANNOTATION_HJID = AIXM.AIXM_PROPERTY.HJID
			WHERE
				GML.AIXM_ELEVATED_POINT_ANNOTATION_LINK.AIXM_ELEVATED_POINT_HJID = GML.AIXM_ELEVATED_POINT.HJID
		) AS ANNOTATION,
		GML.POINT.GEOM AS GEOM
	FROM
		GML.AIXM_ELEVATEDPOINT_PT
		INNER JOIN GML.AIXM_ELEVATED_POINT ON GML.AIXM_ELEVATEDPOINT_PT.ELEVATED_POINT_HJID = GML.AIXM_ELEVATED_POINT.HJID
		INNER JOIN GML.POINT ON GML.AIXM_ELEVATED_POINT.HJID = GML.POINT.HJID
);

CREATE UNIQUE INDEX IF NOT EXISTS IDX_AIXM_ELEVATED_POINT_PT_VIEW_HJID ON GML.AIXM_ELEVATED_POINT_PT_VIEW (HJID);

CREATE INDEX IF NOT EXISTS IDX_AIXM_POINT_PT_VIEW_GEOM ON GML.AIXM_POINT_PT_VIEW USING GIST (GEOM);

CREATE INDEX IF NOT EXISTS IDX_ARC_HJID ON GML.ARC (HJID);

CREATE INDEX IF NOT EXISTS IDX_ARC_INDEX ON GML.ARC (INDEX);

CREATE INDEX IF NOT EXISTS IDX_ARC_GML_POINT_HJID ON GML.ARC (GML_POINT_HJID);

CREATE INDEX IF NOT EXISTS IDX_ARC_CURVE_HJID ON GML.ARC (CURVE_HJID);

CREATE INDEX IF NOT EXISTS IDX_ARC_BULK_COVERING ON GML.ARC (CURVE_HJID, HJID) INCLUDE (GML_POINT_HJID, INDEX);

CREATE INDEX IF NOT EXISTS IDX_CIRCLE_HJID ON GML.CIRCLE (HJID);

CREATE INDEX IF NOT EXISTS IDX_CIRCLE_INDEX ON GML.CIRCLE (INDEX);

CREATE INDEX IF NOT EXISTS IDX_CIRCLE_GML_POINT_HJID ON GML.CIRCLE (GML_POINT_HJID);

CREATE INDEX IF NOT EXISTS IDX_CIRCLE_CURVE_HJID ON GML.CIRCLE (CURVE_HJID);

CREATE INDEX IF NOT EXISTS IDX_CIRCLE_BULK_COVERING ON GML.CIRCLE (CURVE_HJID, HJID) INCLUDE (GML_POINT_HJID, INDEX);

CREATE INDEX IF NOT EXISTS IDX_GEODESIC_HJID ON GML.GEODESIC (HJID);

CREATE INDEX IF NOT EXISTS IDX_GEODESIC_INDEX ON GML.GEODESIC (INDEX);

CREATE INDEX IF NOT EXISTS IDX_GEODESIC_CURVE_HJID ON GML.GEODESIC (CURVE_HJID);

CREATE INDEX IF NOT EXISTS IDX_GEODESIC_GEOM ON GML.GEODESIC USING GIST (GEOM);

CREATE INDEX IF NOT EXISTS IDX_GEODESIC_BULK_COVERING ON GML.GEODESIC (CURVE_HJID, HJID, INDEX);

CREATE INDEX IF NOT EXISTS IDX_LINESTRING_HJID ON GML.LINESTRING (HJID);

CREATE INDEX IF NOT EXISTS IDX_LINESTRING_INDEX ON GML.LINESTRING (INDEX);

CREATE INDEX IF NOT EXISTS IDX_LINESTRING_CURVE_HJID ON GML.LINESTRING (CURVE_HJID);

CREATE INDEX IF NOT EXISTS IDX_LINESTRING_GEOM ON GML.LINESTRING USING GIST (GEOM);

CREATE INDEX IF NOT EXISTS IDX_LINESTRING_BULK_COVERING ON GML.LINESTRING (CURVE_HJID, HJID, INDEX);

CREATE INDEX IF NOT EXISTS IDX_CURVE_HJID ON GML.CURVE (HJID);

CREATE INDEX IF NOT EXISTS IDX_CURVE_ID_COVERING ON GML.CURVE (ID, HJID);

CREATE INDEX IF NOT EXISTS IDX_GML_CURVE_HREF_SUBSTRING ON GML.GML_CURVE (
	SUBSTRING(
		HREF
		FROM
			'([a-f0-9]{8}-[a-f0-9]{4}-[a-f0-9]{4}-[a-f0-9]{4}-[a-f0-9]{12})$'
	)
)
WHERE
	GEOMETRIC_TYPE = 'REF';

CREATE INDEX IF NOT EXISTS IDX_GML_CURVE_HJID ON GML.GML_CURVE (HJID);

CREATE INDEX IF NOT EXISTS IDX_GML_CURVE_INDEX ON GML.GML_CURVE (INDEX);

CREATE INDEX IF NOT EXISTS IDX_AIXM_CURVE_HJID ON GML.AIXM_CURVE (HJID);

CREATE INDEX IF NOT EXISTS IDX_AIXM_ELEVATED_CURVE_HJID ON GML.AIXM_ELEVATED_CURVE (HJID);

CREATE INDEX IF NOT EXISTS IDX_AIXM_CURVE_PT_HJID ON GML.AIXM_CURVE_PT (HJID);

CREATE INDEX IF NOT EXISTS IDX_AIXM_CURVE_PT_CURVE_HJID ON GML.AIXM_CURVE_PT (CURVE_HJID);

CREATE INDEX IF NOT EXISTS IDX_AIXM_CURVE_PT_COVERING ON GML.AIXM_CURVE_PT (HJID, CURVE_HJID);

CREATE INDEX IF NOT EXISTS IDX_AIXM_ELEVATEDCURVE_PT_HJID ON GML.AIXM_ELEVATEDCURVE_PT (HJID);

CREATE INDEX IF NOT EXISTS IDX_AIXM_ELEVATEDCURVE_PT_CURVE_HJID ON GML.AIXM_ELEVATEDCURVE_PT (ELEVATED_CURVE_HJID);

CREATE INDEX IF NOT EXISTS IDX_AIXM_ELEVATEDCURVE_PT_COVERING ON GML.AIXM_ELEVATEDCURVE_PT (HJID, ELEVATED_CURVE_HJID);

CREATE UNLOGGED TABLE IF NOT EXISTS GML.CURVE_UNLOGGED_TABLE (HJID BIGINT, ID VARCHAR, GEOM GEOMETRY);

CREATE UNIQUE INDEX IF NOT EXISTS IDX_CURVE_UNLOGGED_TABLE_HJID ON GML.CURVE_UNLOGGED_TABLE (HJID);

CREATE MATERIALIZED VIEW GML.CURVE_VIEW AS (
	SELECT
		GML.CURVE_UNLOGGED_TABLE.HJID,
		GML.CURVE_UNLOGGED_TABLE.ID,
		GML.CURVE_UNLOGGED_TABLE.GEOM
	FROM
		GML.CURVE_UNLOGGED_TABLE
);

CREATE UNIQUE INDEX IF NOT EXISTS IDX_CURVE_VIEW_HJID ON GML.CURVE_VIEW (HJID);

CREATE INDEX IF NOT EXISTS IDX_CURVE_VIEW_GEOM ON GML.CURVE_VIEW USING GIST (GEOM);

CREATE MATERIALIZED VIEW GML.AIXM_ELEVATED_CURVE_PT_VIEW AS (
	SELECT
		AIXM_ELEVATEDCURVE_PT.HJID,
		GML.CURVE_VIEW.ID,
		AIXM_ELEVATED_CURVE.ELEVATION,
		AIXM_ELEVATED_CURVE.ELEVATION_UOM,
		AIXM_ELEVATED_CURVE.ELEVATION_NILREASON,
		AIXM_ELEVATED_CURVE.GEOIDUNDULATION,
		AIXM_ELEVATED_CURVE.GEOIDUNDULATION_UOM,
		AIXM_ELEVATED_CURVE.GEOIDUNDULATION_NILREASON,
		AIXM_ELEVATED_CURVE.VERTICALDATUM,
		AIXM_ELEVATED_CURVE.VERTICALDATUM_NILREASON,
		AIXM_ELEVATED_CURVE.VERTICALACCURACY,
		AIXM_ELEVATED_CURVE.VERTICALACCURACY_UOM,
		AIXM_ELEVATED_CURVE.VERTICALACCURACY_NILREASON,
		AIXM_ELEVATED_CURVE.HORIZONTALACCURACY,
		AIXM_ELEVATED_CURVE.HORIZONTALACCURACY_UOM,
		AIXM_ELEVATED_CURVE.HORIZONTALACCURACY_NILREASON,
		(
			SELECT
				COALESCE(
					JSONB_AGG(
						JSONB_BUILD_OBJECT(
							'hjid',
							AIXM.AIXM_PROPERTY.HJID,
							'nilreason',
							AIXM.AIXM_PROPERTY.NIL_REASON
						)
					),
					'[]'::JSONB
				)
			FROM
				GML.AIXM_ELEVATED_CURVE_ANNOTATION_LINK
				JOIN AIXM.AIXM_PROPERTY ON GML.AIXM_ELEVATED_CURVE_ANNOTATION_LINK.ANNOTATION_HJID = AIXM.AIXM_PROPERTY.HJID
			WHERE
				GML.AIXM_ELEVATED_CURVE_ANNOTATION_LINK.AIXM_ELEVATED_CURVE_HJID = GML.AIXM_ELEVATED_CURVE.HJID
		) AS ANNOTATION,
		GML.CURVE_VIEW.GEOM
	FROM
		GML.AIXM_ELEVATEDCURVE_PT
		INNER JOIN GML.AIXM_ELEVATED_CURVE ON AIXM_ELEVATEDCURVE_PT.ELEVATED_CURVE_HJID = AIXM_ELEVATED_CURVE.HJID
		INNER JOIN GML.CURVE_VIEW ON AIXM_ELEVATED_CURVE.HJID = GML.CURVE_VIEW.HJID
);

CREATE UNIQUE INDEX IF NOT EXISTS IDX_AIXM_ELEVATED_CURVE_PT_VIEW_HJID ON GML.AIXM_ELEVATED_CURVE_PT_VIEW (HJID);

CREATE INDEX IF NOT EXISTS IDX_AIXM_ELEVATED_CURVE_PT_VIEW_GEOM ON GML.AIXM_ELEVATED_CURVE_PT_VIEW USING GIST (GEOM);

CREATE MATERIALIZED VIEW GML.AIXM_CURVE_PT_VIEW AS (
	SELECT
		AIXM_CURVE_PT.HJID,
		GML.CURVE_VIEW.ID,
		AIXM_CURVE.HORIZONTALACCURACY,
		AIXM_CURVE.HORIZONTALACCURACY_UOM,
		AIXM_CURVE.HORIZONTALACCURACY_NILREASON,
		(
			SELECT
				COALESCE(
					JSONB_AGG(
						JSONB_BUILD_OBJECT(
							'hjid',
							AIXM.AIXM_PROPERTY.HJID,
							'nilreason',
							AIXM.AIXM_PROPERTY.NIL_REASON
						)
					),
					'[]'::JSONB
				)
			FROM
				GML.AIXM_CURVE_ANNOTATION_LINK
				JOIN AIXM.AIXM_PROPERTY ON GML.AIXM_CURVE_ANNOTATION_LINK.ANNOTATION_HJID = AIXM.AIXM_PROPERTY.HJID
			WHERE
				GML.AIXM_CURVE_ANNOTATION_LINK.AIXM_CURVE_HJID = GML.AIXM_CURVE.HJID
		) AS ANNOTATION,
		GML.CURVE_VIEW.GEOM
	FROM
		GML.AIXM_CURVE_PT
		INNER JOIN GML.AIXM_CURVE ON AIXM_CURVE_PT.CURVE_HJID = AIXM_CURVE.HJID
		INNER JOIN GML.CURVE_VIEW ON AIXM_CURVE.HJID = GML.CURVE_VIEW.HJID
);

CREATE UNIQUE INDEX IF NOT EXISTS IDX_AIXM_CURVE_PT_VIEW_HJID ON GML.AIXM_CURVE_PT_VIEW (HJID);

CREATE INDEX IF NOT EXISTS IDX_AIXM_CURVE_PT_GEOM ON GML.AIXM_CURVE_PT_VIEW USING GIST (GEOM);

CREATE INDEX IF NOT EXISTS IDX_RING_HJID ON GML.RING (HJID);

CREATE INDEX IF NOT EXISTS IDX_RING_INDEX ON GML.RING (INDEX);

CREATE INDEX IF NOT EXISTS IDX_RING_HJID_INDEX ON GML.RING (HJID) INCLUDE (INDEX);

CREATE INDEX IF NOT EXISTS IDX_RING_INTERIOR_HJID ON GML.RING (INTERIOR_HJID);

CREATE INDEX IF NOT EXISTS IDX_RING_GML_CURVE_LINK_GML_CURVE_HJID ON GML.RING_GML_CURVE_LINK (GML_CURVE_HJID);

CREATE INDEX IF NOT EXISTS IDX_RING_GML_CURVE_LINK_RING_HJID ON GML.RING_GML_CURVE_LINK (RING_HJID);

CREATE INDEX IF NOT EXISTS IDX_RING_GML_CURVE_LINK_COMPOSITE ON GML.RING_GML_CURVE_LINK (GML_CURVE_HJID, RING_HJID);

CREATE INDEX IF NOT EXISTS IDX_POLYGON_HJID ON GML.POLYGON (HJID);

CREATE INDEX IF NOT EXISTS IDX_POLYGON_INDEX ON GML.POLYGON (INDEX);

CREATE INDEX IF NOT EXISTS IDX_INDEX_EXTERIOR_HJID ON GML.POLYGON (EXTERIOR_HJID);

CREATE INDEX IF NOT EXISTS IDX_INDEX_POLYGON_HJID ON GML.POLYGON (POLYGON_HJID);

CREATE INDEX IF NOT EXISTS IDX_SURFACE_HJID ON GML.SURFACE (HJID);

CREATE UNLOGGED TABLE IF NOT EXISTS GML.POLYGON_UNLOGGED_TABLE (
	HJID BIGINT,
	EXTERIOR_RING_HJID BIGINT,
	GEOM GEOMETRY
);

CREATE UNIQUE INDEX IF NOT EXISTS IDX_POLYGON_UNLOGGED_TABLE_HJID ON GML.POLYGON_UNLOGGED_TABLE (HJID);

CREATE MATERIALIZED VIEW GML.SURFACE_VIEW AS (
	SELECT
		SURFACE.HJID,
		SURFACE.ID,
		ST_MULTI (ST_COLLECT (GML.POLYGON_UNLOGGED_TABLE.GEOM)) AS GEOM
	FROM
		GML.SURFACE
		JOIN GML.POLYGON_UNLOGGED_TABLE ON SURFACE.HJID = GML.POLYGON_UNLOGGED_TABLE.HJID
	GROUP BY
		GML.SURFACE.HJID,
		GML.SURFACE.ID,
		GML.POLYGON_UNLOGGED_TABLE.EXTERIOR_RING_HJID
);

CREATE UNIQUE INDEX IF NOT EXISTS IDX_SURFACE_VIEW_HJID ON GML.SURFACE_VIEW (HJID);

CREATE INDEX IF NOT EXISTS IDX_SURFACE_VIEW_GEOM ON GML.SURFACE_VIEW USING GIST (GEOM);

CREATE MATERIALIZED VIEW GML.AIXM_SURFACE_PT_VIEW AS (
	SELECT
		AIXM_SURFACE_PT.HJID,
		GML.SURFACE_VIEW.ID,
		AIXM_SURFACE.HORIZONTALACCURACY,
		AIXM_SURFACE.HORIZONTALACCURACY_UOM,
		AIXM_SURFACE.HORIZONTALACCURACY_NILREASON,
		(
			SELECT
				COALESCE(
					JSONB_AGG(
						JSONB_BUILD_OBJECT(
							'hjid',
							AIXM.AIXM_PROPERTY.HJID,
							'nilreason',
							AIXM.AIXM_PROPERTY.NIL_REASON
						)
					),
					'[]'::JSONB
				)
			FROM
				GML.AIXM_SURFACE_ANNOTATION_LINK
				JOIN AIXM.AIXM_PROPERTY ON GML.AIXM_SURFACE_ANNOTATION_LINK.ANNOTATION_HJID = AIXM.AIXM_PROPERTY.HJID
			WHERE
				GML.AIXM_SURFACE_ANNOTATION_LINK.AIXM_SURFACE_HJID = GML.AIXM_SURFACE.HJID
		) AS ANNOTATION,
		GML.SURFACE_VIEW.GEOM
	FROM
		GML.AIXM_SURFACE_PT
		INNER JOIN GML.AIXM_SURFACE ON AIXM_SURFACE_PT.SURFACE_HJID = AIXM_SURFACE.HJID
		INNER JOIN GML.SURFACE_VIEW ON AIXM_SURFACE.HJID = SURFACE_VIEW.HJID
);

CREATE UNIQUE INDEX IF NOT EXISTS IDX_AIXM_SURFACE_PT_VIEW_HJID ON GML.AIXM_SURFACE_PT_VIEW (HJID);

CREATE INDEX IF NOT EXISTS IDX_AIXM_SURFACE_PT_VIEW_GEOM ON GML.AIXM_SURFACE_PT_VIEW USING GIST (GEOM);

CREATE MATERIALIZED VIEW GML.AIXM_ELEVATED_SURFACE_PT_VIEW AS (
	SELECT
		AIXM_ELEVATEDSURFACE_PT.HJID,
		GML.SURFACE_VIEW.ID,
		AIXM_ELEVATED_SURFACE.ELEVATION,
		AIXM_ELEVATED_SURFACE.ELEVATION_UOM,
		AIXM_ELEVATED_SURFACE.ELEVATION_NILREASON,
		AIXM_ELEVATED_SURFACE.GEOIDUNDULATION,
		AIXM_ELEVATED_SURFACE.GEOIDUNDULATION_UOM,
		AIXM_ELEVATED_SURFACE.GEOIDUNDULATION_NILREASON,
		AIXM_ELEVATED_SURFACE.VERTICALDATUM,
		AIXM_ELEVATED_SURFACE.VERTICALDATUM_NILREASON,
		AIXM_ELEVATED_SURFACE.VERTICALACCURACY,
		AIXM_ELEVATED_SURFACE.VERTICALACCURACY_UOM,
		AIXM_ELEVATED_SURFACE.VERTICALACCURACY_NILREASON,
		AIXM_ELEVATED_SURFACE.HORIZONTALACCURACY,
		AIXM_ELEVATED_SURFACE.HORIZONTALACCURACY_UOM,
		AIXM_ELEVATED_SURFACE.HORIZONTALACCURACY_NILREASON,
		(
			SELECT
				COALESCE(
					JSONB_AGG(
						JSONB_BUILD_OBJECT(
							'hjid',
							AIXM.AIXM_PROPERTY.HJID,
							'nilreason',
							AIXM.AIXM_PROPERTY.NIL_REASON
						)
					),
					'[]'::JSONB
				)
			FROM
				GML.AIXM_ELEVATED_SURFACE_ANNOTATION_LINK
				JOIN AIXM.AIXM_PROPERTY ON GML.AIXM_ELEVATED_SURFACE_ANNOTATION_LINK.ANNOTATION_HJID = AIXM.AIXM_PROPERTY.HJID
			WHERE
				GML.AIXM_ELEVATED_SURFACE_ANNOTATION_LINK.AIXM_ELEVATED_SURFACE_HJID = GML.AIXM_ELEVATED_SURFACE.HJID
		) AS ANNOTATION,
		GML.SURFACE_VIEW.GEOM
	FROM
		GML.AIXM_ELEVATEDSURFACE_PT
		INNER JOIN GML.AIXM_ELEVATED_SURFACE ON AIXM_ELEVATEDSURFACE_PT.ELEVATED_SURFACE_HJID = AIXM_ELEVATED_SURFACE.HJID
		INNER JOIN GML.SURFACE_VIEW ON AIXM_ELEVATED_SURFACE.HJID = SURFACE_VIEW.HJID
);

CREATE UNIQUE INDEX IF NOT EXISTS IDX_AIXM_ELEVATED_SURFACE_PT_VIEW_HJID ON GML.AIXM_ELEVATED_SURFACE_PT_VIEW (HJID);

CREATE INDEX IF NOT EXISTS IDX_AIXM_ELEVATED_SURFACE_PT_VIEW_GEOM ON GML.AIXM_ELEVATED_SURFACE_PT_VIEW USING GIST (GEOM);

DO $$
DECLARE
    r RECORD;
    idx_name TEXT;
    sql_stmt TEXT;
BEGIN
    FOR r IN
        WITH target_columns AS (
            -- Extract all columns containing 'hjid'
            SELECT
                n.nspname AS schema_name,
                t.relname AS table_name,
                a.attname AS column_name
            FROM pg_attribute a
            JOIN pg_class t ON a.attrelid = t.oid
            JOIN pg_namespace n ON t.relnamespace = n.oid
            WHERE t.relkind IN ('r', 'p')
              AND a.attnum > 0
              AND NOT a.attisdropped
              AND a.attname ILIKE '%hjid%'
              AND n.nspname NOT IN ('pg_catalog', 'information_schema')
        ),
        regular_indexed_columns AS (
            -- Get leading columns of standard B-tree indexes, explicitly EXCLUDING unique constraints/PKs
            SELECT
                n.nspname AS schema_name,
                t.relname AS table_name,
                a.attname AS column_name
            FROM pg_index i
            JOIN pg_class t ON i.indrelid = t.oid
            JOIN pg_namespace n ON t.relnamespace = n.oid
            JOIN pg_class idx ON i.indexrelid = idx.oid
            JOIN pg_attribute a ON a.attrelid = t.oid AND a.attnum = i.indkey[0]
            JOIN pg_am am ON idx.relam = am.oid
            WHERE am.amname = 'btree'
              AND NOT i.indisunique -- Exclude PKs and UNIQUE constraints
        )
        SELECT DISTINCT
            tc.schema_name,
            tc.table_name,
            tc.column_name
        FROM target_columns tc
        LEFT JOIN regular_indexed_columns idx
               ON tc.schema_name = idx.schema_name
              AND tc.table_name = idx.table_name
              AND tc.column_name = idx.column_name
        WHERE idx.column_name IS NULL
    LOOP
        idx_name := substring('idx_hjid_' || r.table_name || '_' || r.column_name FROM 1 FOR 63);

        sql_stmt := format(
            'CREATE INDEX IF NOT EXISTS %I ON %I.%I (%I);',
            idx_name,
            r.schema_name,
            r.table_name,
            r.column_name
        );

        RAISE NOTICE 'Executing: %', sql_stmt;
        EXECUTE sql_stmt;
    END LOOP;
END $$;