

INSERT INTO gml.polygon_unlogged_table
    WITH
		UNION_CURVE AS (
			SELECT
				UNIFIED.RING_HJID,
				UNIFIED.RING_INDEX,
				UNIFIED.INTERIOR_HJID,
				CURVE_UNLOGGED_TABLE.ID AS CURVE_ID,
				UNIFIED.CURVE_HJID,
				UNIFIED.CURVE_INDEX,
				CURVE_UNLOGGED_TABLE.GEOM,
				UNIFIED.TYPE
			FROM
				(
					SELECT
						RING.HJID AS RING_HJID,
						RING.INDEX AS RING_INDEX,
						RING.INTERIOR_HJID,
						GML_CURVE.HJID AS CURVE_HJID,
						GML_CURVE.INDEX AS CURVE_INDEX,
						GML_CURVE.HJID AS TARGET_LOOKUP_HJID,
						GML_CURVE.GEOMETRIC_TYPE AS TYPE
					FROM
						GML.RING
						JOIN GML.RING_GML_CURVE_LINK ON RING.HJID = RING_GML_CURVE_LINK.RING_HJID
						JOIN GML.GML_CURVE ON GML_CURVE.HJID = RING_GML_CURVE_LINK.GML_CURVE_HJID
					WHERE
						GML_CURVE.GEOMETRIC_TYPE::TEXT = 'GML'::TEXT
                        AND RING.HJID %% %1$d = %2$d
					UNION ALL
					SELECT
						RING.HJID AS RING_HJID,
						RING.INDEX AS RING_INDEX,
						RING.INTERIOR_HJID,
						GML_CURVE.HJID AS CURVE_HJID,
						GML_CURVE.INDEX AS CURVE_INDEX,
						AIXM_CURVE.HJID AS TARGET_LOOKUP_HJID,
						GML_CURVE.GEOMETRIC_TYPE AS TYPE
					FROM
						GML.RING
						JOIN GML.RING_GML_CURVE_LINK ON RING.HJID = RING_GML_CURVE_LINK.RING_HJID
						JOIN GML.GML_CURVE ON GML_CURVE.HJID = RING_GML_CURVE_LINK.GML_CURVE_HJID
                        JOIN AIXM.AIXM_FEATURE ON GML_CURVE.HREF_SUB = AIXM_FEATURE.IDENTIFIER::TEXT
						JOIN AIRSPACE.GEOBORDER_F ON AIXM_FEATURE.HJID = GEOBORDER_F.HJID
						JOIN AIRSPACE.GEOBORDER_TP ON GEOBORDER_F.HJID = GEOBORDER_TP.TIMESLICE_HJID
						JOIN AIRSPACE.GEOBORDER_T ON GEOBORDER_TP.GEOBORDERTIMESLICE_HJID = GEOBORDER_T.HJID
						JOIN AIXM.AIXM_TIMESLICE ON GEOBORDER_T.HJID = AIXM_TIMESLICE.HJID
						JOIN AIRSPACE.GBRDRTMSLCTP_BRDR_LINK ON GEOBORDER_T.HJID = GBRDRTMSLCTP_BRDR_LINK.GEOBORDER_T_HJID
						JOIN GML.AIXM_CURVE_PT ON GBRDRTMSLCTP_BRDR_LINK.BORDER_HJID = AIXM_CURVE_PT.HJID
						JOIN GML.AIXM_CURVE ON AIXM_CURVE_PT.CURVE_HJID = AIXM_CURVE.HJID
					WHERE
						GML_CURVE.GEOMETRIC_TYPE::TEXT = 'REF'::TEXT
                        AND RING.HJID %% %1$d = %2$d
				) UNIFIED
				JOIN GML.CURVE_UNLOGGED_TABLE ON UNIFIED.TARGET_LOOKUP_HJID = CURVE_UNLOGGED_TABLE.HJID
		),
		ORDERED_CURVE AS (
			SELECT
				UNION_CURVE.RING_HJID,
				UNION_CURVE.RING_INDEX,
				UNION_CURVE.INTERIOR_HJID,
				UNION_CURVE.CURVE_ID,
				UNION_CURVE.CURVE_HJID,
				UNION_CURVE.CURVE_INDEX,
				UNION_CURVE.TYPE,
				UNION_CURVE.GEOM,
				COUNT(*) OVER (
					PARTITION BY
						UNION_CURVE.RING_HJID
				) AS CURVE_COUNT,
				COALESCE(
					LAG(UNION_CURVE.GEOM) OVER (
						PARTITION BY
							UNION_CURVE.RING_HJID
						ORDER BY
							UNION_CURVE.CURVE_INDEX
					),
					LAST_VALUE(UNION_CURVE.GEOM) OVER (
						PARTITION BY
							UNION_CURVE.RING_HJID
						ORDER BY
							UNION_CURVE.CURVE_INDEX ROWS BETWEEN UNBOUNDED PRECEDING
							AND UNBOUNDED FOLLOWING
					)
				) AS PREV_GEOM,
				COALESCE(
					LAG(UNION_CURVE.TYPE) OVER (
						PARTITION BY
							UNION_CURVE.RING_HJID
						ORDER BY
							UNION_CURVE.CURVE_INDEX
					),
					LAST_VALUE(UNION_CURVE.TYPE) OVER (
						PARTITION BY
							UNION_CURVE.RING_HJID
						ORDER BY
							UNION_CURVE.CURVE_INDEX ROWS BETWEEN UNBOUNDED PRECEDING
							AND UNBOUNDED FOLLOWING
					)
				) AS PREV_TYPE,
				COALESCE(
					LEAD(UNION_CURVE.GEOM) OVER (
						PARTITION BY
							UNION_CURVE.RING_HJID
						ORDER BY
							UNION_CURVE.CURVE_INDEX
					),
					FIRST_VALUE(UNION_CURVE.GEOM) OVER (
						PARTITION BY
							UNION_CURVE.RING_HJID
						ORDER BY
							UNION_CURVE.CURVE_INDEX ROWS BETWEEN UNBOUNDED PRECEDING
							AND UNBOUNDED FOLLOWING
					)
				) AS NEXT_GEOM,
				COALESCE(
					LEAD(UNION_CURVE.TYPE) OVER (
						PARTITION BY
							UNION_CURVE.RING_HJID
						ORDER BY
							UNION_CURVE.CURVE_INDEX
					),
					FIRST_VALUE(UNION_CURVE.TYPE) OVER (
						PARTITION BY
							UNION_CURVE.RING_HJID
						ORDER BY
							UNION_CURVE.CURVE_INDEX ROWS BETWEEN UNBOUNDED PRECEDING
							AND UNBOUNDED FOLLOWING
					)
				) AS NEXT_TYPE
			FROM
				UNION_CURVE
		),
		CUT_CURVE AS (
			SELECT
				ORDERED_CURVE.RING_HJID,
				ORDERED_CURVE.RING_INDEX,
				ORDERED_CURVE.INTERIOR_HJID,
				ORDERED_CURVE.CURVE_INDEX,
				CASE
					WHEN ORDERED_CURVE.TYPE::TEXT = 'REF'::TEXT THEN ST_SNAPTOGRID (
						ST_LINESUBSTRING (
							ORDERED_CURVE.GEOM,
							LEAST(ADJ.CUT_START, ADJ.CUT_END),
							GREATEST(ADJ.CUT_START, ADJ.CUT_END)
						),
						0.00001::DOUBLE PRECISION
					)
					ELSE ORDERED_CURVE.GEOM
				END AS GEOM
			FROM
				ORDERED_CURVE
				CROSS JOIN LATERAL (
					SELECT
						CASE
							WHEN ORDERED_CURVE.PREV_GEOM IS NOT NULL THEN ST_LINELOCATEPOINT (
								ORDERED_CURVE.GEOM,
								ST_ENDPOINT (ORDERED_CURVE.PREV_GEOM)
							)
							ELSE 0.0::DOUBLE PRECISION
						END AS CUT_START,
						CASE
							WHEN ORDERED_CURVE.NEXT_GEOM IS NOT NULL THEN ST_LINELOCATEPOINT (
								ORDERED_CURVE.GEOM,
								ST_STARTPOINT (ORDERED_CURVE.NEXT_GEOM)
							)
							ELSE 1.0::DOUBLE PRECISION
						END AS CUT_END
				) ADJ
			WHERE
				ORDERED_CURVE.CURVE_COUNT >= 2
		),
		CONCAVE_HULL AS (
			SELECT
				CUT_CURVE.RING_HJID,
				CUT_CURVE.RING_INDEX,
				CUT_CURVE.INTERIOR_HJID,
				ST_LINEMERGE (ST_COLLECT (CUT_CURVE.GEOM)) AS GEOM,
				ST_CONCAVEHULL (
					ST_COLLECT (ST_BOUNDARY (CUT_CURVE.GEOM)),
					0.99::DOUBLE PRECISION
				) AS CONCAVE_GEOM
			FROM
				CUT_CURVE
			GROUP BY
				CUT_CURVE.RING_HJID,
				CUT_CURVE.RING_INDEX,
				CUT_CURVE.INTERIOR_HJID
		),
		BOUNDARY_CURVE AS (
			SELECT
				CONCAVE_HULL.RING_HJID,
				CONCAVE_HULL.RING_INDEX,
				CONCAVE_HULL.INTERIOR_HJID,
				CONCAVE_HULL.GEOM,
				CASE
					WHEN ST_GEOMETRYTYPE (CONCAVE_HULL.CONCAVE_GEOM) = 'ST_LineString'::TEXT THEN CONCAVE_HULL.CONCAVE_GEOM
					ELSE ST_BOUNDARY (CONCAVE_HULL.CONCAVE_GEOM)
				END AS CONCAVE_GEOM
			FROM
				CONCAVE_HULL
		),
		COMBINED_RINGS AS (
			SELECT
				ORDERED_CURVE.RING_HJID,
				ORDERED_CURVE.RING_INDEX,
				ORDERED_CURVE.INTERIOR_HJID,
				ST_MAKEPOLYGON (
					ST_ADDPOINT (
						ORDERED_CURVE.GEOM,
						ST_STARTPOINT (ORDERED_CURVE.GEOM)
					)
				) AS GEOM
			FROM
				ORDERED_CURVE
			WHERE
				ORDERED_CURVE.CURVE_COUNT = 1
				AND ST_NPOINTS (ORDERED_CURVE.GEOM) >= 3
			UNION ALL
			SELECT
				BOUNDARY_CURVE.RING_HJID,
				BOUNDARY_CURVE.RING_INDEX,
				BOUNDARY_CURVE.INTERIOR_HJID,
				ST_BUILDAREA (
					ST_UNARYUNION (
						ST_COLLECT (BOUNDARY_CURVE.GEOM, BOUNDARY_CURVE.CONCAVE_GEOM),
						0.00001
					)
				) AS GEOM
			FROM
				BOUNDARY_CURVE
			GROUP BY
				BOUNDARY_CURVE.RING_HJID,
				BOUNDARY_CURVE.RING_INDEX,
				BOUNDARY_CURVE.INTERIOR_HJID,
				BOUNDARY_CURVE.GEOM,
				BOUNDARY_CURVE.CONCAVE_GEOM
		)
	SELECT
		POLYGON.POLYGON_HJID,
		EXTERIOR_RING.RING_HJID AS EXTERIOR_RING_HJID,
		CASE
			WHEN COUNT(INTERIOR_RING.GEOM) = 0 THEN EXTERIOR_RING.GEOM
			ELSE ST_MAKEPOLYGON (
				ST_EXTERIORRING (EXTERIOR_RING.GEOM),
				ARRAY_AGG(ST_EXTERIORRING (INTERIOR_RING.GEOM))
			)
		END AS GEOM
	FROM
		GML.POLYGON
		JOIN COMBINED_RINGS EXTERIOR_RING ON POLYGON.EXTERIOR_HJID = EXTERIOR_RING.RING_HJID
		LEFT JOIN COMBINED_RINGS INTERIOR_RING ON POLYGON.HJID = INTERIOR_RING.INTERIOR_HJID
	GROUP BY
		POLYGON.POLYGON_HJID,
		POLYGON.HJID,
		EXTERIOR_RING.RING_HJID,
		EXTERIOR_RING.GEOM
