name: "Delorean CLI Task Example"
version: "1.0"
verbose: true
logging: "DEBUG"

containers:
  container-A:
    database:
      url: "jdbc:postgresql://localhost:5433/aixm51"
      username: "postgres"
      password: "postgres"
      hbm2ddl: "create"

pipeline:
  set_context:
    name: "AIXM 5.1 Context"
    description: "Context for AIXM 5.1 processing"

  unmarshal: 
    target: "container-A"
    path: "C:/Users/rapha/Downloads/aixm51/baseline.xml"

  sax_validation: 
    target: "container-A"

  startup:
    target: "container-A"

  persist:
    target: "container-A"

  extract:
    target: "container-A"

  marshal: 
    target: "container-A"
    path: "C:/Users/rapha/Downloads/aixm51/output.xml"